### ISSUE TITLE
Bug report: Unsynced data from MongoDB to Relational tables in Metabase

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#1001]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### App version

17.11.8

### Details

When looking at the synced data generated from Cotalker (Bank Client in Production) for "searches" in the main search screen, and the notes opened by a user (procedures) that this client has, the data generated by those actions, seems to stay in MongoBD but is not in sync with relational database in Metabase. In fact there is an active dashboard with an SQL query that brings all generated data, and we analyzed it is not bringing data since last days of May 2022 to the relational tables for this customer.

Similar and related issue happens with customer deployed in production this year which has no updates to its "sessions" table in Metabase so even though we know they have usage from different users, that is not reflecting in the updated "sessions" in the Metabase table

### Steps to reproduce

1. Open dashboard called "dashboard Indicadores" under folder from this Bank customer
2. Filter any data from May onwards
3. Look at results form searches and ranking of "notes" viewed (it will bring no results)

In other client mentioned, please look at most recent event for modifieddat in "sessions" table

### Expected result

1. After making the appropiate filters in dashboard for Bank client, it is expected that any date chosen after May brings updated data of the already built SQL queries

2. In other customer, it is expected that "sessions" table brings updated data of usage as users as entering on a daily basis to use their prod environment

### Additional data

Company Id for Bank client: 6147c23a9c5e6f8dbc0b982e
Comany Id for customer with sessions issue: 6094654ad59bb03e2fc15dd0

**Comment by agallardol** [comment]
Done
