### ISSUE TITLE
Survey Builder: Para la visualización condicional  (isCommander) agregar Criterio "Distinto a"

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1006]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.11.8 (271) 

### Details

Actualmente los criterios existentes son estos:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/61419471/177821634-8f3fe0a0-46eb-4c88-9b0f-c483c1649326.png">

El detalle es el siguiente:

Tengo una componente de tipo colección "A", donde quiero colocar una componente de Respuesta escrita "B", y que sea comandada por "A", con todos los elementos exceptuando uno de ellos (puede ser otros, por ejemplo).

Una de las maneras es usa la "expresión regular" y colocando todos los valores que sean necesarios con la expresion (Elemento|Elemento2|ElementoN). El problema es que si se agregan nuevos elementos a la colección "A", éstos se deben agregar de manera manual.

Por lo que creo que debe haber un criterio distinto a, para colocar el valor que no se debe permitir aparecer la componente comandada

### Steps to reproduce

No aplica 

### Expected result

Que agreguen esa condición

### Additional data

No aplica

**Comment by acedward** [comment]
Se puede hacer un regex negativo:
```
^(?!bar$).*
```
Todo lo diferente a `bar` va ser 'verdadero'

<img width="301" alt="image" src="https://user-images.githubusercontent.com/3951895/181842973-34fae225-d6c6-49a5-aa4f-47585892030d.png">
