### ISSUE TITLE
Bug report: Workflow visible to all users even when not assigning permissions

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#1025]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.11.8

### Details

When creating a new workflow for Bank customer with "Knowledge base solution", the new workflow created remains visible to all users regardless of their permissions. New workflow before assigning any permissions and saving this, makes the workflow visible to all active users. This creates confussion to active users that might see apear a new "channel" in the left menu but no procedures will be there.

<img width="778" alt="Captura de Pantalla 2022-07-18 a la(s) 09 47 18" src="https://user-images.githubusercontent.com/96496507/179525574-94e2a195-b448-4711-8e0f-b4b10898696a.png">

### Steps to reproduce

1. Try to create a new workflow taking as example a previously created one for this customer
2. DO NOT assign any new permissions
3. Try to log with any other user created to check if they have the new workflow visible as a new channel (they will see it!)

### Expected result

The expected result is that after creating a new workflow only roles assigned to have permissions to see that workflow can see it, and nobody else. This will allow the admin to configure new procedures for its user only, before opening up the permissions to certain users that will need to check the new procedures

### Additional data

Company ID: 6147c23a9c5e6f8dbc0b982e

**Comment by ccarrascor** [comment]
Cuando introdujimos los permisos globales y por propiedad a los workflows eliminamos del admin los permisos de lectura y escritura del grupo. Los permisos globales afectan directamente a las tareas del grupo, no al grupo mismo.

No podemos agregar los campos al admin ahora, pero por mientras se podria setear por api las variables `writePermissions` y `readPermissions` del taskgroup. Esas variables son las que chequean la visibilidad del grupo para los usuarios.

**Comment by DavidEhrenfeld** [comment]
Si hacemos eso Cami, para cada workflow que se cree nuevo, puede dejarse que se cree con writePermissions y readPermissions = null o false por default, hasta que le agreguemos esos permisos por api a ciertos usuarios específicos? Si no, al crear un nuevo workflow para el caso de este cliente, cerca de 800 usuarios verán el canal por default, cuando en realidad hay que asignarle visibilidad a cerca de 60-80

**Comment by agallardol** [comment]
El comportamiento pareciera ser el esperado pero por error se eliminó la sección del admin que permitía configurar esto. Debería volver a estar disponible en 17.12.4
