### ISSUE TITLE
Bug report: Startform solo visible en Taskview. Se abre panel de creación de canal en vez del form.

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1028]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0

### Details

Al hacer click para desplegar el Startform en vista de canales, se despliega el panel de creación de canales y no el startform.
En cambio en la vista de tareas el startform se despliega correctamente.

### Steps to reproduce

- Solicitar acceso a la compañía afectada
- Ingresar con un usuario con permisos para  enviar el form 
- hacer clik en el botón (+)
- hacer clik en "crear incidencia"

Se desplegará el siguiente panel:
<img width="1259" alt="Captura de Pantalla 2022-07-18 a la(s) 16 16 06" src="https://user-images.githubusercontent.com/98488087/179609498-d29545e1-cdec-48b9-9d75-7ec0cd63b16a.png">

### Expected result

Que se  despliegue el startform como siempre y no el panel de creación de canales.

**Comment by agallardol** [comment]
Corregido en 17.12.1
