### ISSUE TITLE
Bug report: Sections dissapear randomly when using categories

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#1031]
### Affected system

Cotalker Web Application

### Affected environment

Development

### App version

Latest

### Details

Usando la última versión de Cotalker con "Categories", a veces desaparecen las secciones de manera random:
![image](https://user-images.githubusercontent.com/34345309/180011944-15608209-f620-4564-9133-c3b92e3a2f25.png)

Normalmente debería verse así:
![image](https://user-images.githubusercontent.com/34345309/180012075-14263553-dd46-47f0-ac78-f7b9c488e7f3.png)

### Steps to reproduce

Configurar una "Category" y agregar secciones a esa category.

Al parecer cuando se ejecuta el endpoint de visibility de las secciones muchas quedan en "false" y se empiezan a ocultar. Luego de un reload (Cmd+R) vuelven a aparecer.

### Expected result

Que aparezcan las secciones correctamente.

**Comment by agallardol** [comment]
Closed, disponible en 17.12.2
