### ISSUE TITLE
Bug report: Contador de tareas falla si existen 10 tareas en el estado

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1046]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Affected environment (other)

CLiente infra dedicada 

### App version

Version 17.11.8 (271)

### Details

En estado 4.1 cerrados se muestra +10 en el contador de tasks y el boton cargar más al final de la última task. Al presionar el contador o el botón cargar más no ocurre nada. Se revisa vs vista de canales y solo existen 10 tareas  activas.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/50208672/180893036-52c82a1e-0097-47f2-a5a9-07635d482b17.png">

### Steps to reproduce

1. Ingresar con cuenta administrador (solicitar a creador de incidencia)
2. Ver tareas en estado 4.1 Cerrados

### Expected result

Que si son 10 tareas no se muestre el botón cargar más , ni el contador 10+.

**Comment by jdurandpaz** [comment]
Issue no permitirá que cliente apruebe QA para paso a prod

**Comment by jdurandpaz** [comment]
hola @ccarrascor has podido revisar este tema? dado que cliente nos esta presionando para pasar a productivo.

**Comment by ccarrascor** [comment]
@jdurandpaz  Probablemente miercoles vuelva a ver este tema.
