### ISSUE TITLE
Bug report: Agregar un subordinado no actualiza el boss del otro usuario

### ISSUE THREAD

**Issue by maramire** [Cotalker/documentation#1049]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected environment

Staging

### App version

Versión 17.12.4 (278)

### Details

Hola como están,

Estoy reviviendo esta [discussion](https://github.com/Cotalker/documentation/discussions/347) de Nico Peña, donde uno en el admin puede agregar subordinados, pero en el subordinado no se está reflejando el boss. 

Necesitamos esto funcional en una implementación, por ahora workaround que tenemos es traer todos los users y verificar si está el user en los subordinates, y así poder saber quién es el boss, pero no es lo óptimo.

User con un subordinado:
<img width="338" alt="Captura de Pantalla 2022-07-27 a la(s) 13 13 56" src="https://user-images.githubusercontent.com/31930273/181308878-488ba1ba-a813-403d-afee-fc5c1b775cbd.png">

El subordinado:
<img width="253" alt="Captura de Pantalla 2022-07-27 a la(s) 13 14 43" src="https://user-images.githubusercontent.com/31930273/181308899-233bcbe2-fa08-495e-9806-b9bbf91e0921.png">

Saludos.

### Steps to reproduce

1. Crear un usuario con un subordinado.
2. Consultar por api al subordinado y ver que no tiene el boss.

### Expected result

Debería reflejarse en el subordinado el boss correspondiente.

**Comment by acedward** [comment]
@maramire @jdurandpaz 

Lamento la confusión aquí.
**El campo BOSS y PEERS está deprecado hace un tiempo ya.**

En el admin solo se pueden agregar subordinados por esta misma razón:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/3951895/184023478-c22d3dd5-fbad-44f9-939e-33f598dfc017.png">

Esta funcionalidad se puede lograr con los **webhooks** + **schema-instance** para usuarios.

Un webhook que se active al modificar usuarios, que actualize un campo del schema-instance del `user.schema_instance.MIS_RELACIONES.MI_JEFE_DIRECTO` o algo así.
