### ISSUE TITLE
Bug report: Dessinconización tablas metabase 

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#1052]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.12.4

### Details

Tabla de company especifica no tiene actualizada la tabla sessions. Teniendo información actualizada hasta ale 16/12/2021

<img width="797" alt="image" src="https://user-images.githubusercontent.com/96496507/181380580-a31d80b7-a3bf-4f1a-ba43-99d05ebaedfb.png">

### Steps to reproduce

1. Entrar a Metabase
2. Buscar compañía 6094654ad59bb03e2fc15dd0
3. Buscar tabla sessions y verificar ultima sesión de usuario
4. Revisar logs de autentificación de usuarios reales utilizando esta company y ver que tiene usabilidad reciente

### Expected result

Tener tabla "sessions" de esta compañia actualizada

**Comment by martinmiranda14** [comment]
Había un problema de configuración en la base de datos de metabase.
