### ISSUE TITLE
Bug report: Tareas de sub flujo no se asocian a tarea padre

### ISSUE THREAD

**Issue by AlejandroLoraG** [Cotalker/documentation#1054]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0

## Hola a tod@s! Espero que se encuentren de maravillas y estén teniendo una hermosa semana. 💕

Ayer hice una actualización de versión a unas etapas de tipo **ITERAR** en una rutina de startForm. Esto lo hice porque existe un bug conocido en [**ITERAR v1**](https://github.com/Cotalker/documentation/issues/1010).
Al hacer esta actualización de iterar, de pronto mi rutina empezó a fallar al crear las tareas hijas de este flujo. Donde existía un campo **_parent_** en la respuesta de PBCreateTask (fig 1), ahora no existe (fig 2) (pienso que esto debe tener mucho que ver).

Además, dejaron de funcionar muchas cosas de la creación de las tareas hijas, y esto solo porque actualicé estas 2 etapas de **ITERAR** a v2.

Fig 1
![fig 1](https://user-images.githubusercontent.com/51095635/181598142-2002398f-63d0-45d9-ba61-ba7af7b8afa3.png)

Fig 2
![fig 2](https://user-images.githubusercontent.com/51095635/181598233-83f034cd-0ad8-4510-b14c-c5c9a401d035.png)

### Steps to reproduce

1. Comunicarse con alelo

### Expected result

1. La rutina debió haber mantenido su comportamiento normal.

**Comment by acedward** [comment]
FCEach 2.0 no tiene acceso a la data del padre.
Fix con workaround.
Agregar etapa CCJS previa al FCEach y modificar data de control con datos necesarios.

e.g.,
1. FCEach es originalmente control = [{ a:1 }, { a: 2}, {a: 3} ]
2. En CCJS ` return  [{ a:1 }, { a: 2}, {a: 3}].map ( x => ({ ...x, myData: "Valor Constante }) )
3. En FCEach control = CCJS.data
4.
