### ISSUE TITLE
Bug report: No se actualiza de manera instantánea la creación de un elemento dentro del mismo formulario

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1055]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.12.5 (279)

### Details

Si en un fomrulario tengo una pregunta de clientes (componente colección), tengo una opción de otro, donde al presionar en "otro", me aparece un campo de texto en la cualquier me permitirá agregar el nuevo cliente a la lista una vez que envío el formulario (ya sea por una acción proveniente de un bot channel, como tambien acción de un fab).

El problema es, cuando quiero levantar nuevamente un nuevo formulario usando dentro de la lista de "clientes", el nuevo cliente agregado no aparece.

La unica forma en que aparezca es que actualice el navegador y eso no debería ocurrir.

Adjunto link del video:  https://drive.google.com/file/d/1do0E9m6alfro_S3iHvXxrnL08Iw5f0UR/view?usp=sharing

### Steps to reproduce

0.- Crear un formulario con lo siguiente:
1.- crear una componente colección + un elemento "otros"
2.- crear una componente de texto que sea comandado por otros
3.- guardar
4.- Crear un bot channel o u fab, asociado a dicho formulario con una rutina de condicional + create property
5.- Realizar pruebas 2 veces
6.- Esperar resultados 

### Expected result

Debería actualizar de manera correcta el listado

**Comment by acedward** [comment]
Propiedad creada por API no aparece en UI de forma inmediata. Hay que refrezcar.

**Comment by NicolasPLG** [comment]
Es el comportamiento esperado o es la única forma de hacerlo para que se sea visible?.  Lo pregunto porque qué pasaría si durante el día debo ingresar 50 ticket, en la cual existen X clientes y cada uno puede tener más de 1 ticket asociado, pero no son de manera secuencial. Adicionalmente los X clientes no están creados, por lo que se crean dentro del mismo formulario de registro. tendría que actualizar el navegador, cada vez que agregue un nuevo cliente para que aparezca en el listado?.

y a nivel de App ¿cómo sería?, se debe hacer un relogin? o allí si se carga de manera automática?.

La única forma en que se pueda ver el listado actualizado es usando el external-form, dado que desde el fab y el bot channel, requieren de hacer refesh para que aparezca (esos dos casos finales los probé y está relacionado a este issue, mientras que el external-form lo tengo implementado en otra compañía y no tengo problemas).

:) :(

**Comment by eduborgono** [comment]
Resuelto en webclient 17.13.14
