### ISSUE TITLE
Bug report: hide unique 

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#1057]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Asset : Unique 

no debe aparecer.
 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/3951895/181791982-e956ce60-e84a-457a-b672-68429abeb565.png">

### Steps to reproduce

1. Admin 
2. Workflow
3. State Machine

### Expected result

No debe visualizarse el campo

**Comment by agallardol** [comment]
Corregido, disponible a partie del 02/08/2022
