### ISSUE TITLE
Bug report: Cliente infra dedicada: No funcionan los reportes

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#1059]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.12.4 (278)

### Details

Reportes no están funcionando en cliente con infra dedicada.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/12589784/181845192-e12573d1-e5c0-420e-a865-0f6c0c471740.png">

### Steps to reproduce

ir a reportes en cliente con infra dedicada

### Expected result

mostrar reportes

**Comment by acedward** [comment]
@SeIturra por favor contactar @martinmiranda14 para datos de infra

**Comment by martinmiranda14** [comment]
Se Corrige usuario de metabase en infraestructura de copec
