### ISSUE TITLE
Bug report:  Search no muestra todos los resultados

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1062]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Version 17.12.4 (278)

### Details

Al buscar tasks con un nombre en específico se muestran menos resultados de los que realmente existen.

**Vista taks:**

<img width="548" alt="image" src="https://user-images.githubusercontent.com/50208672/182421935-35b5e6e3-9e62-4967-bca9-67f4251dbc45.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/50208672/182422007-157d36d4-1fc6-43a5-8cfb-de058aacd477.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/50208672/182422151-762c0a4d-7932-4c54-9ba4-122dc070152b.png">

**Buscador:**

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/50208672/182422244-5f9d405a-c28c-47d1-8db0-f9041a4e92d5.png">

La única particularidad de estas tasks es que su nombre es actualizado mediante un SLA como se ve en la siguiente imagen:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/50208672/182422602-d529354b-581d-4f6a-a10d-6ad96be424c5.png">

### Steps to reproduce

Buscar tasks con nombre SLA VENCIDO y ver cantidad de resultados.

### Expected result

Que se muestren la totalidad de los casos que existen, o en su defecto se muestre una cantidad y se puedan ver más resultados.

**Comment by acedward** [comment]
Nota: al parecer el índice está desincronizado. 
Al editar una tarea, apareció en la búsqueda

**Comment by agallardol** [comment]
Se envió a resincronización

**Comment by jdurandpaz** [comment]
con eso ahora se reflejan correctamente, muchas gracias
