### ISSUE TITLE
Bug report: Tabla sessions desaparecida en Metabase

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#1063]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Favor revisar tablas de company 585b022b7b3293170c1d68e8 (Operador Portuario) que anteriormente contaba con tabla "sessions" y aparentemente ya no se ve disponible para obtener indicadores como usabilidad actual

### Steps to reproduce

1. Ingresar a Metabase
2. Buscar company subdomain de operador portuario con referencia de company Id indicado arriba
3. Buscar tabla sessions

### Expected result

Tabla sessions debería verse, y verificar que tenga sesiones de usuarios reciente ya que esta compañía tiene uso diario por aprox 50-60 usuarios

### Additional data

company ID: 585b022b7b3293170c1d68e8

**Comment by agallardol** [comment]
Fixed. Disponible desde 03/08/2022
