### ISSUE TITLE
Bug report: En la vista de tareas, las tareas no cambian visualmente de estado hasta que recargas. 

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1064]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0 

### Details

En una empresa específica, en un flujo específico, las tareas no se mueven visualmente de estado hasta que recargas la página (pero la rutina se ejecuta correctamente y si llegan los mensajes de cambio de estado).

### Steps to reproduce

1) ingresar a la empresa específica (solicitarme las credenciales) 
2) ingresar al flujo de presupuestos ( licitaciones)
3) cambiar una licitación de estado

En la imagen se puede ver que la tarea se encuentra en el estado "Esperando Presupuesto" mientras que en el canal se indica que fue cambiada al estado  "1. Evaluación Nivel 1".  

<img width="891" alt="Captura de Pantalla 2022-08-03 a la(s) 17 11 04" src="https://user-images.githubusercontent.com/98488087/182712571-4bd3a290-6a6b-4e6d-af83-5aa18493d16b.png">

Una vez recargas, cambia correctamente de estado: 

<img width="899" alt="Captura de Pantalla 2022-08-03 a la(s) 17 13 30" src="https://user-images.githubusercontent.com/98488087/182713006-47667a2e-38f1-4a2c-8b89-1365932fd674.png">

### Expected result

Que se mueva al estado correspondiente.

**Comment by agallardol** [comment]
Corregido. Disponible en staging a partir de 09/08/2022

En production estará disponible en 17.12.7

**Comment by maramire** [comment]
> Corregido. Disponible en staging a partir de 09/08/2022
> 
> En production estará disponible en 17.12.7

Sigue pasando en Staging.
