### ISSUE TITLE
Bug report: Campo de Código QR no muestra la información leída hasta que se abre y cierra la cámara nuevamente 

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1065]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0 

### Details

Para ver el código captado con el QR se debe abrir y cerrar la cámara nuevamente.

Uploading WhatsApp Video 2022-08-03 at 4.16.06 PM.mp4…

### Steps to reproduce

Leer QR
Esperar a que lo procese 
Volver a abrir la cámara 
Cerrar la cámara y se verá el código

Observaciones adicionales (no se si son bugs o feature requests) 
- una vez obtenido el código hay que manualmente ejecutar la llamada asíncrona (ideal sería que fuese automático).
- el botón de borrar sale casi en el mismo lugar que el botón de ejecutar.

Video de ejemplo:
https://user-images.githubusercontent.com/98488087/182716332-89f49bf4-62ee-48f0-8218-543b6d68563d.mp4

### Expected result

Que se cargue el código identificado y se ejecuten las acciones asociadas a este.

**Comment by agallardol** [comment]
Corregido, disponible a partir de 04/08/2022
