### ISSUE TITLE
Bug report: Se cambia a vista de archivos luego de ejecutar una acción (tras abrir una nota embebida)

### ISSUE THREAD

**Issue by maramire** [Cotalker/documentation#1067]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.12.6 (280)

### Details

Hola como están, 

En staging pasa algo parecido a lo reportado en coopeuch en #1029 , pero con distinto comportamiento. Luego de abrir una nota desde la tarea, y volver a ejecutar una accíon desde el chat, se cambia a la vista de archivos con la nota que se había abierto anteriormente, dejo video:

https://user-images.githubusercontent.com/31930273/182886188-7528900b-8c71-47e3-b493-0f3438752ef0.mov

Que estén muy bien!

### Steps to reproduce

1. En una tarea en la vista tareas crear una nota
2. Hacer clic en la nota desde la vista lista.
3. Cambiarse a vista chat y ejecutar en acción
4. Ver como la pestaña cambia a vista archivos.

### Expected result

Al ejecutar una acción en la vista chat no debería volver a la nota creada.

**Comment by agallardol** [comment]
Corregido, disponible en staging 09-08-2022

En production, disponible en 17.12.7

**Comment by maramire** [comment]
> Corregido, disponible en staging 09-08-2022
> 
> En production, disponible en 17.12.7

@agallardol  Sigue pasando en Versión 17.12.7 de production

**Comment by jdurandpaz** [comment]
@maramire según comentario anteriopr de matías sigue pasando.

**Comment by agallardol** [comment]
Gracias @julio probamos con @maramire y hay un caso donde ocurrre esto que no habíamos testeado

**Comment by agallardol** [comment]
Done
