### ISSUE TITLE
Bug report: Rutina se actualiza y guarda con cambios pero al hacer F5, se resetea con config anterior

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#1070]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.12.6

### Details

Al intentar cambiar elementos de una rutina (agregar cuentas distintas para envío de correo o nuevo user para agregar a un canal) en una rutina previamente construida, se pueden realizar y guardar los cambios que se ven reflejados desde el front. Sin embargo, al apretar F5 y volver a la rutina guardada, no se ven reflejados

### Steps to reproduce

1. Ingresar a cuenta de cliente con gestión de contratos
2. Ir a flujo de trabajo de gestión de contratos
3. Ingresar a la rutina asociada al formulario de inicio
4. Cambiar etapa de rutina por cuenta de email a enviar o agregar nuevo user ID y guardar
5. Luego verificar cambios sin F5 y ver que efectivamente se ven cambiados
6. Sin embargo al hacer F5 y verificar los cambios ingresados, se verá que no se realizaron

### Expected result

1. Cambios que deje guardar en una rutina pre configurada, se deberían reflejar como guardados para que opere correctamente

### Additional data

https://user-images.githubusercontent.com/96496507/183765496-93939bef-04f3-47ec-86a4-77d5b494976e.mov

**Comment by acedward** [comment]
@DavidEhrenfeld es un problema de UI.
@agallardol detectó el problema.

**Comment by acedward** [comment]
El save que aparece en una rutina no guarda realmente :(

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/3951895/183907581-b319188e-aa1c-4217-9961-3652336bc733.png">
este es el que persiste la data

**Comment by DavidEhrenfeld** [comment]
Vale entiendo. Gracias Eddie y Alfredo por ver esto. Quizás debiesemos tener una alerta que al salir del flujo de trabajo sin haber apretado el Guardar general, diga algo como "hay cambios ingresados que no han quedado guardados" o algo asi.
