### ISSUE TITLE
Bug report: Step de FCEach 2.0 no puede usar $OUTPUT de etapas anteriores

### ISSUE THREAD

**Issue by maramire** [Cotalker/documentation#1075]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.12.6 (280)

### Details

Hola como están,

Estoy teniendo problemas al usar el output de una etapa en el step de un iterar (usando la version 2.0). Por ejemplo tengo esta rutina:

<img width="278" alt="Captura de Pantalla 2022-08-12 a la(s) 13 59 15" src="https://user-images.githubusercontent.com/31930273/184416629-5e595cf7-55d1-4f8a-bc58-8bf2b8fc05da.png">

Donde en la etapa `send_email`, que se hace dentro de un iterate, necesito el output de `get_pdf_as_base64`, sin embargo con la versión del iterate 2.0 no lo puedo hacer y necesito este workaround https://github.com/Cotalker/documentation/issues/1054#issuecomment-1199930861, o cambiar la versión del bot por base de datos.

### Steps to reproduce

1. Crear una rutina con una etapa previo a al iterar.
2. Usar el `output` de la etapa en un step del iterar.
3. Ver que el `output` no se puede usar en la iteración.

### Expected result

Se debe poder tener el output de etapas anteriores al iterate en el contexto de este para usarlo en las distintas iteraciones.

**Comment by SeIturra** [comment]
El mismo problema nos pega para otro cliente para mejorar el tiempo de ejecución de una rutina en la que tenemos que pedir datos en cada iteración en vez de sólo al inicio antes de iterar.

**Comment by ValeMP** [comment]
Hable con Mati y me decía que aplicaron workaround!

**Comment by acedward** [comment]
Fixed fceeach 3.0
