### ISSUE TITLE
Bug report: category only groups if there are a channel

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#1082]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

En producto ahora se usará la agrupación de los flujos de trabajo para limpiar la vista del usuario. Sin embargo, la categoría no agrupa si no hay canales asociado, lo cual va a ocurrir en una compañía nueva de prueba porque se entrega sin task al usuario.

Foto de Ejemplo: 

Cotizaciones de servicio y orden de servicio también deberían estar en una categoría:

<img width="258" alt="Captura de Pantalla 2022-08-18 a la(s) 22 06 36" src="https://user-images.githubusercontent.com/42095617/185527550-e31cbd4e-8971-4ef9-a6c0-202a9a12357b.png">
<img width="265" alt="Captura de Pantalla 2022-08-19 a la(s) 09 12 06" src="https://user-images.githubusercontent.com/42095617/185626108-83f25170-6dd7-43d0-8b54-e396b0e3b5d4.png">

### Steps to reproduce

1. Crear categoria de workflow sin task
2. observar que no agrupa hasta tener una task creada

### Expected result

que se agrupe a pesar de que no tenga canales / task

**Comment by guillevalin** [comment]
Este bug nos afecta el viaje de los leads inbound y los demos comerciales.
