### ISSUE TITLE
Bug report: Search no permite buscar por números del nombre de una tarea

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1083]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### Affected environment (other)

Cliente infra dedicada 

### App version

Version 17.12.6 (280)

### Details

No se obtienen resultados en el search cuando se busca por algún número presente en el nombre de la tarea. Por ejemplo si intentamos buscar alguna de estas dos tareas:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/50208672/185621659-e62d6b36-5017-41a7-86d6-62464cc02904.png">

Si busco por el número de aviso (última parte del nombre de la tarea) se obtiene:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/50208672/185621876-af3ced2b-efdd-4568-b6a2-2611d1a755f3.png">

Si busco por instalación (primera parte del nombre de la tarea), se ven algunos canales pero no las tasks buscadas

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/50208672/185622001-43b39493-0149-4b92-9458-aef70bf11ccf.png">

Si busco por la parte de texto del nombre se obtienen resultados:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/50208672/185622289-f6b1f2ac-03fa-4857-9007-20328dcc972a.png">

### Steps to reproduce

Buscar tareas por alguno de los valores númericos que tiene en el nombre.

### Expected result

Que se pueda buscar por esos valores y encontrar la tarea que representa a ese número de aviso o instalación.

**Comment by DavidEhrenfeld** [comment]
Hola, podemos subir este bug a prioridad crítica. Usuario principal no puede quiere ocupar workaround y es importante para continuidad del negocio que buscador de avisos funcione óptimamente

**Comment by DavidEhrenfeld** [comment]
No quedó bien cerrado esto. Hay que reabrir

**Comment by martinmiranda14** [comment]
Cambios aplicados en infraestructura dedidaca
