### ISSUE TITLE
Bug report: No se actualizan las referencias (properties, roles, etc de los usuarios al editarlos en el admin).

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#1084]
### Affected system

Cotalker Web Application

### Affected environment

Staging, Development

### Details

Estaba trabajando en el producto de mantenimiento, donde el formulario de crear aviso tiene un filtro por subproperty-user. El tema es que si al usuario le actualizaba las propiedades que tiene, no se observa los cambios en el filtro. 

Haciendo una investigación @guillevalin encontró que no se actualiza el storage del usuario para estos filtros. Solo se actualiza cuando se inicia sesión

**Workaround**: Si se cambia las propiedades del usuario, se debe hacer log out y log in.

### Steps to reproduce

1. Entrar al producto de mantenimiento
2. Quitarle propiedades al usuario de "Workstation" / "Puesto de trabajo"
3. Observar que no se actualizan los valores posibles de sector de equipamiento al crear aviso.
4. Log out
5. Log in
6. Observar que si se hace el filtro

### Expected result

Que se haga el filtro sin tener que decirle a los usuarios que hagan logout y login para actualizar sus referencias.

### Additional data

Alex también encontró el bug implementando

**Comment by DavidEhrenfeld** [comment]
Yo también tengo un tema con este issue para compañia nueva de solutions que está en onboarding y necesita sus usuarios con visibilidad de las propiedades asociadas a su puesto de trabajo, cosa que puede ver solamente si se deslogea y vuelve a logearse

**Comment by agallardol** [comment]
Reabrí este issue ya que el fix que se hizo provocó otros problemas

**Comment by DavidEhrenfeld** [comment]
Este bug no ha sido solucionado 100%: https://www.loom.com/share/0c452e2cea3241efbbb827acdfa812ef ...aun se tiene que seguir haciendo logout y luego login para que aparezcan las asociaciones de datos a usuario. Dejé un video en loom con ejemplo
