### ISSUE TITLE
Bug report: Problema con los filtros de las tasks ("ha ocurrido un error desconocido)

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#1085]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Hola team!!

Me pasa cada vez que aprieto un workflow y me lleva a la vista de tasks, me aparece el mensaje de "Ha ocurrido un error desconocido".
Viendo los logs, fallan las llamadas de los filtros: "TypeError: Cannot read property 'count' of undefined".

### Steps to reproduce

1. Moverse entre distintos workflows en la vista de tasks y aparece el mensaje de error

### Expected result

Que no fallen las llamadas de los filtros :) 

Graciaaaas team por la ayuda!!! 🙌🙌

**Comment by agallardol** [comment]
Corregido, ya disponible en staging
