### ISSUE TITLE
Bug report: PBCopySurvey crash core pod 

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#1088]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging, Development

### Details

Estoy trabajando con una rutina de un pbscript que contiene un pbcopysurvey y al llegar a esta etapa bota el pod de core en dev. 

Estuvimos conversando con @martinmiranda14 el viernes de esto, y encontramos que en prod también se caía pero como habían más pod andando no botaba todo. 

La llamada de red que realiza el pbcopysurvey buscando los message se ejecuta bien. 

### Steps to reproduce

1. Usar el create work order del producto de mantenimiento
2. Observar el pod de core

### Expected result

Esperar que se copie el formulario sin crushear core

**Comment by martinmiranda14** [comment]
Lo que se descubrió el día viernes fue que estas caídas ocurren justo después de que hubieran consumos anormalmente altos de ram al ejecutar esta rutina (sae observaron las graficas en grafana )

**Comment by agallardol** [comment]
Solucionado, en development y staging. Este bug y su correspondiente corrección no llegaron a los ambientes de production
