### ISSUE TITLE
Bug report: andina.cotalker.com is not redirecting to /login and gets stuck in a logout loop

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#1095]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0

### Details

In a good percentage of cases (~70%), navigating to andina.cotalker.com causes the web page to become stuck in a loop. A lot of network requests are made in this state to the logout endpoint. The redirect to the login page is never achieved.
![image](https://user-images.githubusercontent.com/45186006/186766279-446be8b5-9baf-40f2-989f-b08fffac1637.png)

### Steps to reproduce

1. Navigate to andina.cotalker.com

### Expected result

Redirect working consistently

**Comment by agallardol** [comment]
Corregido
