### ISSUE TITLE
Bug report: Push notifications not working on iOS

### ISSUE THREAD

**Issue by AcencioMauricioIcinf** [Cotalker/documentation#1099]
### Affected system

Cotalker iOS Application

### Affected environment

Production

### App version

17.12.2

### Details

The iOS app is no longer sending notifications of new messages in channels or tasks, including not showing a notification bubble in the app's icon.

### Steps to reproduce

1. Make sure that your device (i.e. your iPhone) has notifications enabled for Cotalker.
2. Login to the iOS app, with your usual Cotalker account.
3. Leave the app in background (while still open), and wait for new messages to arrive.

### Expected result

Every new message should be notified on screen.

**Comment by agallardol** [comment]
Solucionado y disponible a partir del 31 de Agosto de 2022.

Ahora aparecen las notificaciones pero el badge en el ícono de la app es algo que será imoplementado como feature request en release futuros. Posiblemente Septiembre / Octubre
