### ISSUE TITLE
Bug report: Group link (with no access roles) dosen't appear in the menu 

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#1100]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Probando con Nico, nos dimos cuenta que los group link que no tienen acceso roles configurado, no aparece en el menu de cotalker. 

Esto nos afecta en la visualización de los dashboards en los productos. 

Si es que no es posible tomar el caso, se puede conversar acerca del workaround que sería algo para desarrollar.

### Steps to reproduce

1. Crear un group link sin access roles
2. visualizar que no se ven en el menú principal

### Expected result

Se espera que todos los usuarios vean el group link

**Comment by CVargasGando** [comment]
Revisando el tema de este bug, nos dimos cuenta que estos groups links no se veían en el menú porque estos se creaban a través de una api de groups y no desde el admin, y en esta llamada para crear el group link el body venía sin el "nestedGroups". Esto provocaba que cuando se creaba el group link, el nestedGroups de este nuevo group link se colocaba "[]" en vez de null, lo cual hace que no se vea el group link en el menú. La solución es en la llamada a la api de groups atajar "[ ]" del nestedGroups, o que el default sea null.

Pensamos que podía ser el tema de los permisos el problema, porque al agregar un accessrole que el usuario sí tenía, ahí se arreglaba y el usuario podía ver el group link, pero se arreglaba porque se hacía una llamada patch y en esa llamada se enviaba también el nestedGroups: null, por lo que arreglaba el problema. (si le saco el accessrole después, sigue funcionando, ya que ya se reemplazó con el nestedGroups: null)

Si se crea un group link desde el admin, se observa que la llamada que se hace sí tiene el nestedGroups por lo que sí funciona.

**Comment by MiikeVi** [comment]
> Revisando el tema de este bug, nos dimos cuenta que estos groups links no se veían en el menú porque estos se creaban a través de una api de groups y no desde el admin, y en esta llamada para crear el group link el body venía sin el "nestedGroups". Esto provocaba que cuando se creaba el group link, el nestedGroups de este nuevo group link se colocaba "[]" en vez de null, lo cual hace que no se vea el group link en el menú. La solución es en la llamada a la api de groups atajar "[ ]" del nestedGroups, o que el default sea null.
> 
> Pensamos que podía ser el tema de los permisos el problema, porque al agregar un accessrole que el usuario sí tenía, ahí se arreglaba y el usuario podía ver el group link, pero se arreglaba porque se hacía una llamada patch y en esa llamada se enviaba también el nestedGroups: null, por lo que arreglaba el problema. (si le saco el accessrole después, sigue funcionando, ya que ya se reemplazó con el nestedGroups: null)
> 
> Si se crea un group link desde el admin, se observa que la llamada que se hace sí tiene el nestedGroups por lo que sí funciona.

Buena @CVargasGando , el fix fue justamente relacionado con nestedGroups y en sí era un problema de la api, ahora no deberían tener que preocuparse por si es que están o no mandando nestedGroups, funcionará ya sea null o [ ] (esto de momento está solo en staging) saludos!
