### ISSUE TITLE
Bug report: Groups (of workflows) visualization permissions

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#1104]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### Details

probando el perfilamiento de usuarios, nos dimos cuenta de lo siguientes:
- los workflows view permission, logran visualizar los grupos solo para los usuarios que tienen permisos
- los workflows edit permission, no logran cumplir con la regla de visualización

El workaorund es que solo se use view workflow permission

<img width="1069" alt="Captura de Pantalla 2022-08-30 a la(s) 18 08 37" src="https://user-images.githubusercontent.com/42095617/187552533-e64abf2c-be76-444c-ac97-64e0e2d8ae9c.png">
<img width="340" alt="Captura de Pantalla 2022-08-30 a la(s) 18 10 47" src="https://user-images.githubusercontent.com/42095617/187553011-41fa7596-5850-487c-b13d-cadcd8ddaf8e.png">

El service order debería estar oculto

### Steps to reproduce

1. crear un cworkflow y darle permisos al edit workflow permission que no tengo el usuario
2. visualizar que se ve de igual forma le grupo

### Expected result

Que no se visualice el workflow si no tengo el permiso

**Comment by digutier** [comment]
# Propuesta de solución
### El fix para este issue va a consistir en lo siguiente:
- El hecho de que si el usuario **tiene algún** permiso ya sea de la lista de **read permissions** o **write permissions**, entonces va a poder visualizar el grupo.
- Si un campo tiene permisos y otro no, el usuario **podrá ver el grupo si tiene algún permiso** del campo que sí tiene permisos.
- Si **ambos** campos están vacíos, **todos** los usuarios podrán ver el grupo.

Cualquier feedback bienvenido sea.

**Comment by digutier** [comment]
- Resuelto en release de staging # 247.
- En producción estará una vez se haga el release de hoy 1 de Septiembre.
