### ISSUE TITLE
Bug report: Cuando ingreso una password incorrecta el sistema se queda en bucle infinito

### ISSUE THREAD

**Issue by martinmiranda14** [Cotalker/documentation#1106]
### Affected system

Cotalker Web Application

### Affected environment

Staging, Development

### Details

Cuando ingreso una contraseña errónea el sistema no indica que se ingresaron datos de manera incorrecta

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/29107230/187696154-ca29dfdc-3e09-460c-b1dd-fcb54652232b.png">

### Steps to reproduce

Ir al login
Ingresar un usuario o una contraseña erronea

### Expected result

Que el sistema indique que los datos no son correctos

**Comment by martinmiranda14** [comment]
Bug ahora está pasando en demo

**Comment by Sadaka1234** [comment]
> Bug ahora está pasando en demo

Agregando eso, al crear la compañia en demo, el usuario intenta loggear y queda con el ícono pegado como si cargara, pero en realidad "se equivoco de contraseña"

al probar por api, efectivamente se puede loggear a demo y no a prod (lo cual es correcto)

**Comment by agallardol** [comment]
@Sadaka1234 este issue está relacionado con lo que comentaste de demo
