### ISSUE TITLE
Bug report: readOnlyUsers verification causes public survey error

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#1113]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

17.12.7

### Details

Form doesn't load. Consoler shows type error related to readOnlyUsers

### Steps to reproduce

1. Go to public survey
2. open console
![image](https://user-images.githubusercontent.com/45186006/188172074-94764571-1f3f-4a5c-8697-22232ad3b30f.png)

### Expected result

public survey loading

### Additional data

<img width="961" alt="image" src="https://user-images.githubusercontent.com/45186006/188172016-3204d53a-75a7-4606-846f-d3e7f2b95d6a.png">

**Comment by agallardol** [comment]
Solved, disponible en 17.13.1
