### ISSUE TITLE
Bug report: No sincroniza complemente la BD para BI, incluso reiniciandola

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1114]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected environment

Staging

### App version

 Versión 15.0.0 (713) 

### Details

Hemos tratado de dropear las tablas para obtener información, pero no hemos tenido éxito

### Steps to reproduce

1.- hablar por interno

### Expected result

Que se pued edropear de manera correcta

**Comment by acedward** [comment]
El log contiene información condifencial. Tengo los datos, por favor pedir.

**Comment by digutier** [comment]
### Update del issue 12 de Septiembre:
Se ha detectado el problema asociado a la falla de sincronización de la base de datos:
- Esto se debe a que hubo una combinación de códigos de property type/schema instance que combinados (más un '_') resulta un nombre de columna de PostgreSQL de largo 64, siendo que esta base de datos sólo soporta de largo 63 coincidentemente. Lo cual hizo que automáticamente se truncara, eliminando la última letra del nombre de la columna.
- Lo mencionado anteriormente hace que haya una inconsistencia de columnas en la base de datos al momento de hacer la sincronización automática, lo cual conlleva al error asociado impediendo esta sincronización, haciendo que se deje de ver la data en el BI.

### Solución:
- No se puede aumentar el máximo ni cambiar la forma en la que se crean las columnas de las tablas de PostgreSQL. Por ende, ya se le notificó al usuario (Nico) el problema y la solución correspondiente que en este caso sería ingresar un código más pequeño (1 letra menos) de tal forma de que no ocurra el problema mencionado.
- Como fix preventivo para futuras ocasiones se va a desarrollar una solución que permita validar el correcto ingreso de una combinación de códigos válida (propertyType/schemaInstance). Esto es con el fin de que no vuelva a ocurrir este tipo de problemas, ya que actualmente no se está manejando la restricción que existe en PostgreSQL.

**Comment by digutier** [comment]
## Update del issue 19 de Octubre:

Se ha hecho el update en **staging** con respecto a la solución acordada el 12 de Septiembre.
