### ISSUE TITLE
Bug report: PBPdf no carga las imágenes

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#1117]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Hola team!! Espero que estén teniendo un día bacan 🥰

Les vengo a pedir ayuda con un bug porfis.
Me pasa que la etapa de rutina para crear pdf (PBPdf) no me carga las imágenes.

Si pruebo el link con el que se genera el pdf en mi navegador, sí se me ven las imágenes, pero si con ese mismo link lo pongo en la etapa para crear el pdf, no se me ven las imágenes.
El link es: https://9kqrfooa1j.execute-api.us-east-1.amazonaws.com/dev/maintenance/get-report/63163121ab0bd9c841e53003/6318f326da135822a5f8bcc3 
Si lo abro desde el navegador me aparece:
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/73865460/188972101-8562d0f4-268c-4dea-86e2-21e3e24e17c2.png">
Y si lo ejecuto desde el PBPdf se ve así (https://cotalker-us-dev.s3.amazonaws.com/uploads/comercialdemo/document/6318f397da1358bc2ef8bccc.pdf):
<img width="806" alt="image" src="https://user-images.githubusercontent.com/73865460/188972161-e9f625ae-1934-4cfb-bee4-31b7cdf5b8fc.png">

El código que utilizo es:
```
const imageCloseWorkOrder = task.answerCloseOt.data.find(i => i.identifier === "cm_cwo_photos")?.responses;
let imageCloseWorkOrderHtml = imageCloseWorkOrder.map(img => `<img src="${JSON.parse(img).original}" alt="Image not found">`);
```

### Steps to reproduce

1. Abrir el siguiente link en el navegador y ver que sí aparece la imagen: https://9kqrfooa1j.execute-api.us-east-1.amazonaws.com/dev/maintenance/get-report/63163121ab0bd9c841e53003/6318f326da135822a5f8bcc3
2. El siguiente link es lo que retorna le etapa de crear pdf: https://cotalker-us-dev.s3.amazonaws.com/uploads/comercialdemo/document/6318f397da1358bc2ef8bccc.pdf. En este no se ven las imágenes.

### Expected result

Que PBPdf sí pueda cargar las imágenes

**Comment by CVargasGando** [comment]
También pasaba lo mismo con links del estilo del pdf, que el PBPdf no los considera, entonces al parecer es un problema con que no carga cualquier tipo de link

**Comment by ValeMP** [comment]
Es importante que se desarrolle este proyecto dado que los clientes nuevos usan estas funcionalidad, y no podrán visualizar las imágenes dentro del pdf

**Comment by agallardol** [comment]
Estará corregido a partir del 28 de Septiembre del 2022
