### ISSUE TITLE
Bug report: Aplicación iOS no carga sesión (Web y Android si funcionan)

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#1118]
### Affected system

Cotalker iOS Application

### Affected environment

Production

### App version

Latest

### Details

Al iniciar sesión con una cuenta en particular en la aplicación de iOS, se queda pegado en un loop y no logra iniciar sesión:

![image](https://user-images.githubusercontent.com/34345309/189126712-4fbf9354-56fc-4814-8e0c-2acb9aaa6bc6.png)

Este error no logra ser replicado en otras plataformas.

### Steps to reproduce

1. Iniciar sesión con esta cuenta en particular en la aplicación de iOS (solicitar datos a Mauricio)
2. Quedará pegadfo en el loop descrito arriba.

### Expected result

Poder iniciar sesión.

**Comment by agallardol** [comment]
Esto ocurre en iOS y Android para cuentas de compañía demo. Estará solucionado en la versión 17.13.9
