### ISSUE TITLE
Bug report: No se pueden agregar rutinas a bot desde la colección bots

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1124]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.13.9 (291)

### Details

en el momento de crear y configurar un bot, éte no me permite edtiar sus datos ni agregar rutinas, tengo permisos full admin

adjunnt videoi: https://drive.google.com/file/d/1GWY-Z9fptIZGPpgW5npyDHQYCZqGe0qu/view?usp=sharing

### Steps to reproduce

1.- ir a bot
2.- crear un bot
3.- ingresar los datos
4.- guardar
5.- volver a ingresar

### Expected result

deberia agregar rutinas

**Comment by NicolasPLG** [comment]
@gmoplaza reactvo pensando que estaba abierto

**Comment by digutier** [comment]
Ahora, el día de hoy 30 de Septiembre se hizo un fix que hace que desde ahora los bots nuevos volveran a ser v3. Se revierte la creación de bots v4 lo cual solucionaría todos los problemas. Se cierra el issue.
