### ISSUE TITLE
Bug report:  Redireccionamiento después de leer un QR y hacer Login

### ISSUE THREAD

**Issue by martinmiranda14** [Cotalker/documentation#1127]
### Affected system

Cotalker Web Application

### Affected environment

Development

### App version

14.4.2

### Details

Despues de logearme dado que escanie un qr y no estaba logeado y despues de que el sistema me muestra la vista de un elemento cuando cambio de elemto y lo desactivo el sistema me muestra la vista del elemento asociado al qr escaneado

[EDITADO]

### Steps to reproduce

Escanear un QR no logueado
Logearse con un usuario que tenga los permisos apropiados
Cambiar a otro elemento
Desactivar ese elemento

### Expected result

Que no se abra nuevamente la vista del elemento original

**Comment by acedward** [comment]
Pedir video directamente a @martinmiranda14
