### ISSUE TITLE
Bug report: Categorías no editables desde el admin

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#1130]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Intentando editar las categorías que se tiene por defecto en los productos, la pantalla de edición se mostraba sin autorellenar los campos.

Y si miraba la url, se indicaba el correcto id de la categoría que se intenta editar

Aún no pruebo si aparecen las categorías creadas desde el mismo admin, dado que no puedo crear una desde el admin

Aquí les dejo imágenes de referencia:
<img width="1132" alt="Captura de Pantalla 2022-09-13 a la(s) 15 09 07" src="https://user-images.githubusercontent.com/42095617/190007446-1f982ef8-36b2-41e9-bbbf-2937eb50b00a.png">
<img width="1154" alt="Captura de Pantalla 2022-09-13 a la(s) 15 09 02" src="https://user-images.githubusercontent.com/42095617/190007456-beeb0602-3d79-4e23-b143-1f1b9ff34372.png">

### Steps to reproduce

1. ir a una compañía con productos
2. intentar editar las categorías
3. observar que no se puede

### Expected result

Debería poder editarlo

**Comment by ccarrascor** [comment]
Duplicado del issue [#1122](https://github.com/Cotalker/documentation/issues/1122)
