### ISSUE TITLE
Bug report: Formularios no terminan de cargar en canal de tarea

### ISSUE THREAD

**Issue by maramire** [Cotalker/documentation#1136]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.13.15 (298)

### Details

Hola,

Tengo un problema. de visualización en la UI, cuando ingreso a una tarea el form de inicio se me queda cargando infinitamente y pareciera que se cortara. Dejo evidencia:

<img width="917" alt="Captura de Pantalla 2022-09-21 a la(s) 17 04 10" src="https://user-images.githubusercontent.com/31930273/191600098-aaed648b-6662-4296-9f54-e53118632d1d.png">

El problema se soluciona recargando la página, pero es muy molesto.

Saludos.

### Steps to reproduce

Hablar conmigo para entregar credenciales de compañía donde está sucediendo.

### Expected result

Debería mostrarse el form completo, sin quedar carganbdo infinitamente.

**Comment by acedward** [comment]
¿Esto pasa 100% de las veces?

**Comment by maramire** [comment]
> ¿Esto pasa 100% de las veces?

No

**Comment by acedward** [comment]
Podría estar corregido. Podemos confirmar?

**Comment by jdurandpaz** [comment]
sigue pasando en web.staging. Sin embargo no ocurre el 100% de las veces que se crea una tarea.

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/50208672/206719311-dad9cc6f-4d9f-4ce9-a759-def763b57c72.png">
