### ISSUE TITLE
Bug report: webhook no se gatilla si la edición de la task es cambiar un schemaInstance a null

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#1141]
### Affected system

Cotalker Web Application

### Affected environment

Staging, Development

### Details

Hola team!! 
Quería pedirles ayuda con otro bug pequeño de webhook porfis :) (y ya no los molesto más 😂)

Que tengo un webhook que se gatilla con la creación/edición/eliminación de una task de un workflow específico.
Y lo que me pasa es que puedo editar el detalle de una task de este workflow específico de 3 formas:
1. Cambiar un schemaInstance de X a Y: esto sí me entrega correctamente el body del webhook con lo que se editó:
```
"/extensions/am_m_asset/parentstatus_equipmentsector": {
      "previous": "5f57d3d99da20e10988108ae",
      "changedTo": "5f57d3d91aae0210928102ae"
    },
```
2. Cambiar un schemaInstance de null a X: esto sí me entrega correctamente el body del webhook con lo que se editó:
```
"/extensions/am_m_asset/parentstatus_equipmentsector": {
      "previous": null,
      "changedTo": "5f57d3d99d700e0008cc08ae"
    },
```
3. Cambiar un schemaInstance de X a null: esto no me aparece en el body del webhook con lo editado (parentstatus_equipmentsector). Sí se gatilla el webhook (en este caso particular porque considera un cambio de asset_url_photos), pero entrega solamente lo que aparace a continuación y no aparece la edición del schemaInstance parentstatus_equipmentsector.
```
"diff": {
    "/modifiedAt": {
      "previous": "2022-09-27T16:38:52.762Z",
      "changedTo": "2022-09-27T16:39:17.468Z"
    },
    "/extensions/am_m_asset/asset_url_photos": {
      "previous": null,
      "changedTo": []
    }
  }
```

### Steps to reproduce

En el video se ven los pasos para reproducir:
1. Crear el webhook
2. Editar un schemaInstance de X a Y y se observa que sí aparece en el body el schemainstance editado (caso 1 explicado antes).
3. Editar el schemaInstance de Y a null y observar que en el body no aparece el schemaInstance editado (caso 3 explicado antes).

https://user-images.githubusercontent.com/73865460/192588161-f1e2a3fe-129b-4897-a02c-1498cc757f43.mov

### Expected result

Que si se edita un schemaInstance de la task cambiándolo a null, también se considere como algo que se editó en la task y se gatille el webhook correctamente.

Muchas gracias!! son los mejores 🙌
Que tengan un buen día!!

**Comment by gmoplaza** [comment]
Arreglado en monorepo
