### ISSUE TITLE
Bug report: No funciona los question exec y selector multiples en ciertos formularios

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1144]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Affected environment (other)

Versión 17.14.0 (300)

### App version

Versión 17.14.0 (300)

### Details

Cliente reporta que no puede levantar un formulario
 Adjunto un gif de una compañia de prueba, sobre lo que sucede
![selectores con problema](https://user-images.githubusercontent.com/61419471/193289322-ecf23482-576b-42e6-bac2-0d009850e940.gif)

### Steps to reproduce

1.- Seguir los puntos hablados anteriormente

### Expected result

que pueda ingresar :)

**Comment by agallardol** [comment]
Solucionado
