### ISSUE TITLE
Bug report: Theres a number of schemaNodes big enough to crash the admin

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#1149]
### Affected system

Cotalker Web Application

### Affected system (other)

Admin

### Affected environment

Production, Staging, Development

### App version

15.0.0

### Details

When a propertyType has around 70 or 100 schemaNodes, the /collections/edit/:id page starts to become unresponsive.
In some cases with more nodes the browser throws the Not Responding dialog
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/45186006/194661469-0ba4baf3-e891-4586-b673-7eae64d26474.png">
And the page crashes after that. This becomes a barrier of use for collections with a large number of fields.

### Steps to reproduce

Generate a propertyType with schemaNode ~100 schemaNodes. Check response time and loading time of the edition section of the collection

### Expected result

Page not crashing

**Comment by digutier** [comment]
El fix se encuentra actualmente en Staging, queda pendiente por realizar el hotfix a prod (hoy).
