### ISSUE TITLE
Bug report: Survey editable con survey+survey abre todos los subformularios a la vez

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#1155]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.12.4 (278)

### Details

La situación ocurre cuando se deja editable un formulario con survey+surveys utilizando PBEditableSurvey.
Cada vez que se abre el canal que tiene el formulario editable, se muestran todos los subformularios a la vez, uno encima de otro.

### Steps to reproduce

1. Enviar un formulario.
2. Ejecutar la etapa PEditableSurvey 2.0.1
3. Recargar el canal
4. Se mostrarán todos los subformularios a la vez

### Expected result

sólo se debería abrir el canal y no mostrar subformularios

**Comment by jdurandpaz** [comment]
@acedward @Sadaka1234 en windows sigue pasando 
![IMG_20221102_155029](https://user-images.githubusercontent.com/50208672/199577781-00fca161-a6f3-4e4d-acb1-d5f365abfe3d.jpg)

**Comment by acedward** [comment]
Fixed

**Comment by jdurandpaz** [comment]
@acedward

**Comment by guillevalin** [comment]
Está resuelto en la última versión de iOS (18.0.2). Segun @jdurandpaz solo pasa en iOS.
