### ISSUE TITLE
Bug report: Webhook de tareas no se está gatillando

### ISSUE THREAD

**Issue by maramire** [Cotalker/documentation#1156]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.14.4 (304)

### Details

Hola como están,

En staging tenemos un webhook que al actualizar una tarea (desde la vista de detalle) se ejecuta una función de serverless, pero al revisar los logs vemos que no se ha gatillado el webhook desde el mes pasado. 

Volvimos a crear un nuevo webhook para probar y no están llegando las actualizaciones.

Ojalá nos puedan ayudar con esto, que estén muy bien!

### Steps to reproduce

1. Crear un webhook de tareas para un flujo especifico.
2. Crear una tarea o editarla.
3. Revisar logs del webhook

### Expected result

Debería gatillarse la url del webhook cada vez que se edite o cree una tarea.

**Comment by agallardol** [comment]
Estará disponible en el siguiente paso a production. Estamos planificando para esta semana
