### ISSUE TITLE
Feature Request: Asset Forms (Reports&Actions):  id fijo en el modelo de propertyreports de metabase

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#1168]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Hola team! Espero que tengan un buen lunes :)

Tenemos un problemilla para poder exportar una compañía con Reportes (modelo propertyreports), ya que el modelo hace referencia a un "id" que corresponde al id de la tabla en metabase, y ese id es dinámico dependiendo de la compañía.

Por ejemplo, en el modelo de la base de datos se guarda así:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/73865460/196208793-1c05266b-5c05-4229-93c2-3aba9cf55c18.png">
Donde el id "11067" hace referencia a la tabla de metabase "task_m_work_orders" de esta compañía.

### Steps to reproduce

1. Crear un reporte desde el admin
2. Ver su modelo en la base de datos

### Expected result

Una opción podría ser eliminar del modelo el "id", y que la búsqueda se haga a partir del nombre de la tabla, y a partir de eso y de la compañía se podría obtener el id. Así no se pondría el "id" harcodeado.

**Comment by acedward** [comment]
Fixed
