### ISSUE TITLE
Bug Report: Cuando son muchos, no se pueden ver ni editar los subelementos de un elemento en su ficha  

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1174]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Al ingresar a la base de datos del administrador e intentar editar los sub elementos en la ficha de un elemento con más de 100 de estos, la colección y los elementos no se muestran.

### Steps to reproduce

Ingresar a base de datos
ingresara a una collection
Buscar un elemento con muchos sub elementos (ni idea con cuantos falla)
Abrir su ficha e intentar editar algún sub elemento  
No se verá nada, solo la opción de agregar un nuevo elemento.

https://user-images.githubusercontent.com/98488087/196447000-e648220e-eaf9-403c-81cf-c083a9350648.mov

### Expected result

Que se muestre el listado de sub elementos y poder editarlo.

**Comment by guillevalin** [comment]
@acedward una property con muchas subproperties utiliza el queryParam ids con todas las subproperties... lo que da un error:

414 Request-URI Too Large
