### ISSUE TITLE
Bug report: Bot pbsendemail no adjunta correctamente los archivos

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1176]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Version 17.14.4 (304)

### Details

Al adjuntar un link de un pdf en un pb send email, este se adjunta corrupto.

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/50208672/197206765-c306f57f-f6b1-4059-a125-327e1fbf6c40.png">

<img width="1152" alt="Screen Shot 2022-10-21 at 10 02 28" src="https://user-images.githubusercontent.com/50208672/197206029-49a43eea-0c1e-4d4c-8a2b-2ee847720a26.png">

### Steps to reproduce

1. Ejecutar bot test que deje en Cotalker https://web.cotalker.com/admin/bots/edit/635298735afdca000841ddeb 
2. Verificar que archivo se adjunta corrupto

### Expected result

Que el archivo se adjunte correctamente y se pueda descargar

**Comment by DavidEhrenfeld** [comment]
Esto está afectando a mismo cliente en productivo que ya impactamos por otro bug ((https://github.com/Cotalker/documentation/issues/1173)) por lo que necesitamos prioridad por favor

**Comment by ValeMP** [comment]
@DavidEhrenfeld @jdurandpaz les sigue sucediendo ??

**Comment by guillevalin** [comment]
Nosotros hemos probado intensivamente el envío de correos y funcionan correctamente en los ambientes de desarrollo, staging y demo (que tiene las mismas versiones que productivo). Sigue pasando?

**Comment by jdurandpaz** [comment]
entiendo que ya esta solucionado 

<img width="866" alt="image" src="https://user-images.githubusercontent.com/50208672/202553887-81d13fc5-8a07-4a4a-a059-6806a00206c2.png">
