### ISSUE TITLE
Bug report: Set Survey to Edition Mode hides the complete survey

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#1178]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

17.14.4

### Details

[VIDEO](https://drive.google.com/file/d/1NnKlyeAZ9hOvc546B8eAEUu7OdKXpR62/view?usp=sharing)

Using PBEditableSurvey over a recently sent survey collapses and requires a refresh to correctly view the edition mode

### Steps to reproduce

Can't reproduce yet, but access to the company in web.dev.cotalker.com
  {
    "email": "admin@bugfeofeo.cotalker.com",
    "password": "*********"
  }
  
  Create task, send form 1 in "de lolo" state

### Expected result

edition mode survey loading correctly

**Comment by SeIturra** [comment]
I could reproduce it! This is a Widows only bug.

![image](https://user-images.githubusercontent.com/12589784/198027735-6cdef01f-bb84-432a-9e37-b436156d2537.png)

**Comment by SeIturra** [comment]
No, I used Set Survey to Edition Mode as you did and it has the same behavior.

**Comment by agallardol** [comment]
Corregido, estará disponible en 17.15.3

**Comment by SeIturra** [comment]
![IMG_20221121_155107](https://user-images.githubusercontent.com/12589784/203137395-972d4770-632c-416c-949b-c358d733a583.jpg)

Same behavior in Windows. 
Cotalker version: 18.0.0
