### ISSUE TITLE
Bug report: property tree selector con muchos elementos: 414 Request-URI Too Large

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#1189]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.15.2 (308)

### Details

Cuando se envía una request muy larga se llega a este error

### Steps to reproduce

Enviar una request de 15 Kb de URI

### Expected result

La request debería poder procesarse

**Comment by acedward** [comment]
Pude reproducir el error. 
Por favor pedir script a @acedward y/o datos para reproducción
