### ISSUE TITLE
Bug report: ValidationError in patch property (Path $id and $ref is required)

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#1190]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

Hoola team! espero que estén teniendo un excelente día :)

Quería pedirles ayuda con un problema que tuve al hacer un patch property en dev. Este problema me pasa solo en dev, en staging la misma llamada me funciona perfect.

El curl de la llamada es el siguiente:
```
curl --location --request PATCH 'https://dev.cotalker.com/api/v3/properties/636a9fc44f56761e1dd4cbc2' \
--header 'admin: true' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmM5ZmZjN2YyNWFjNDJmMDQyMDM3OWUiLCJyb2xlIjoidXNlciIsImNvbXBhbnkiOiI1ZjNlN2RhYTYxOGNlNjAwMDhiMGFlMjQiLCJkYXRlIjoxNjY3OTMyNTM1NjY1LCJpcnQiOnRydWUsImlhdCI6MTY2NzkzMjUzNSwiZXhwIjoxNjcwNTI0NTM1fQ.QGKwyTEC3jVj7KYRfiQMswoj2ngnzaXyVOXGWUMYWnQ' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": {"display": "hola"}
}
```

Y me entrega un error 500
<img width="921" alt="image" src="https://user-images.githubusercontent.com/73865460/200657675-051c17e3-29e2-46bc-bc88-b0acb1ee2674.png">

Si hago un get property de esa misma property, me entrega el siguiente objeto (es una propiedad de una task):
```
{
        "_id": "636a9fc44f56761e1dd4cbc2",
        "company": "5f3e7daa618ce60008b0ae24",
        "propertyType": "data_failure_catalog",
        "subproperty": [],
        "name": {
            "code": "unique-636a9fc44f56761e1dd4cb96",
            "display": "test1"
        },
        "isActive": true,
        "owner": {
            "$ref": "task-products-workflow_create_failurecatalogs",
            "$id": "636a9fc44f56761e1dd4cb96",
            "_id": "636a9fc54f56761e1dd4cc63"
        },
        "createdAt": "2022-11-08T18:28:20.528Z",
        "modifiedAt": "2022-11-08T18:28:21.322Z",
        "schemaInstance": {}
    },
```

### Steps to reproduce

1. Hacer una llamada patch property en dev
2. No permite hacer la llamada

### Expected result

Poder hacer llamada patch property

**Comment by acedward** [comment]
fixed
