### ISSUE TITLE
Bug report: En infra prod dedicada, cuando se crea una tarea no aparece de manera automática la vista de chat, aparece la vista de archivo

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1192]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

3.3.7

### Details

Cada vez que se crea una nueva tarea está aparece por defecto la vista de archivos y debería verse la vista de chat, como en otras cias

ADjunto SS
![Uploading image.png…]()

### Steps to reproduce

Entrar a la infra dedicada, hacer pruebas y eviar

### Expected result

deberia ser de manera automatica como en las otras infraestrcuturas

**Comment by martinmiranda14** [comment]
Fixed
