### ISSUE TITLE
Bug report: Sync SQL interrumpida en compañía "products" de staging

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#1195]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Hola team!
Espero que tengan un buen día :)

Quería pedirles ayuda con este bug de sincronización de SQL porfis 🙌

Estamos teniendo problemas para modelar dashboards en la compañía de seed de products. Y con esto también para tener los reportes en la sección de Reports&Actions (Forms) en el producto.
Actualmente svc-sql arroja un error que interrumpe la sincronización de la compañía, quedando incompleta (hay varias tablas que nunca se sincronizan).

El error ocurre al sincronizar la propertyType "data_failure_catalog":

```
info [2022-11-10T19:10:40.363Z] Property query # 9 (5f3e7daa618ce60008b0ae24) @ {"propertyType":"data_failure_catalog"} 

error [2022-11-10T19:10:40.371Z] ERROR: 0 Cannot resolve extra: {
"e": {
"stack": "TypeError: Cannot read property 'type' of undefined\n    at /app/node_modules/@cotalker/lib-sql-names/dist/utils/property-type-extra-model.js:95:25\n    at Array.map (<anonymous>)\n    at PropertyTypeExtraModelClass.getValues (/app/node_modules/@cotalker/lib-sql-names/dist/utils/property-type-extra-model.js:91:37)\n    at PropertyModel.<anonymous> (/app/dist/models/properties/property.model.js:106:21)\n    at Generator.next (<anonymous>)\n    at /app/dist/models/properties/property.model.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/dist/models/properties/property.model.js:4:12)\n    at /app/dist/models/properties/property.model.js:92:98\n    at COTMongoDB.<anonymous> (/app/dist/services/dbs/COTMongoDB.js:243:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/services/dbs/COTMongoDB.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
"message": "Cannot read property 'type' of undefined"
}
}
nyi [2022-11-10T19:10:40.372Z] NYI : reportError
```

El propertyType está definido de la siguiente forma en el seed:
```
{
       "_id": ObjectId("5f57d5169d700e0008cc0a07"),
       "create": {
           "requiredPermission": []
       },
       "isActive": true,
       "sextras": false,
       "viewPermissions": [],
       "code": "data_failure_catalog",
       "display": "[[SYMPTOM]]",
       "company": ObjectId("5f3e7daa618ce60008b0ae24"),
       "createdAt": ISODate("2020-09-08T19:01:42.889Z"),
       "modifiedAt": ISODate("2020-09-08T19:01:42.889Z"),
       "__v": 2,
       "schemaNodes": [
           {
               "validators": {
                   "required": true,
                   "validator": []
               },
               "isArray": false,
               "weight": 1,
               "isActive": true,
               "_id": ObjectId("6131261b1292ab1782f80a49"),
               "key": "parentselfstatus_failuregroup",
               "display": "[[FAILURE-GROUP]]",
               "description": "",
               "basicType": "COTProperty",
               "subType": "data_failure_group"
           },
           {
               "validators": {
                   "required": true,
                   "validator": []
               },
               "isArray": false,
               "weight": 2,
               "isActive": true,
               "_id": ObjectId("6131261b1292ab0009f80a49"),
               "key": "status_priority",
               "display": "[[PRIORITY]]",
               "description": "",
               "basicType": "COTProperty",
               "subType": "data_priority"
           }
       ],
       "visualization": {
           "schemaNodesGroups": []
       }
   },
```

Creemos que el error podría estar en una rutina del svc-sql (podría ser que la variable **map** bajo ciertas condiciones quede **undefined**)

Muchas gracias team! Cualquier cosa me dicen :)

### Steps to reproduce

1. Sincronizar en sql la compañía "products"
2. Notar que no se sincronizan todas las tablas por un error que ocurre durante la sincronización que provoca su corte.

### Expected result

Sincronizar todas las tablas de la base de datos de "products" (seed) exitosamente en svc-sql

**Comment by Sadaka1234** [comment]
Se encontró el posible problema: 
- El nombre del schemaNode: "parentselfstatus_failuregroup_causes" es muy largo. Debido a las restricciones de postgres, el nombre de la columna es de 64 caracteres. Sin embargo, cuando se crea todo, el nombre de la columna queda como:
    "data_failure_catalog_causes_parentselfstatus_failuregroup_cause" <- Se aprecia que se cortó el "causes" a "cause" porque se cortó automaticamente el nombre
    
  Soluciones: 
  - La complicada: Cambiar backend (esta medio dificil pero se está ponderando)
  - La facil: Que el nombre de alguno de los factores (del property, o del schemaNode) se acorten. Actualmente se pasa por solo 1 caracter

**Comment by Sadaka1234** [comment]
Se habló con la parte del equipo afectada, y reducir el nombre de la columna y/o schemaNode como workaround funcionó para resolver el issue. Se creará un nuevo issue asociado a este bug de forma general, pero este issue  que es más particular pasará a cerrado :3
