### ISSUE TITLE
Bug report: No está configurado metabase prod infradedicada

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1199]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 18.0.0 (300)

### Details

En el momento de ingresar metabase de infra dedicada, ambiente prod, me arroja esta imagen

<img width="990" alt="image" src="https://user-images.githubusercontent.com/61419471/201735384-5ad15057-52b1-406d-a79f-237aaa767c8a.png">

Para poder cerrar el proyecto de nuestro lado necesitariamos que nos configuraran dicho ambiente

### Steps to reproduce

1.- preguntar por interno la cia respectiva

### Expected result

se pueda acceder

**Comment by guillevalin** [comment]
Resuelto
