### ISSUE TITLE
Bug report: Scheduler process tiene un aumento excesivo de memoria ram

### ISSUE THREAD

**Issue by martinmiranda14** [Cotalker/documentation#1201]
### Affected system

Cotalker Api

### Affected environment

Staging, Development

### App version

18.0.0

### Details

En la version 1.16.0 se observa un aumento anormal en el uso de ram de svc-scheduler-proces. 

Se detecta que comienza a ocurrir desde el commit https://github.com/Cotalker/svc-scheduler-process/commit/ad23eabcc4ea33dd53e86aebe9f9b9816acc1582

Se recomienta utilizar el commit https://github.com/Cotalker/svc-scheduler-process/commit/c821a2580bd7579c7ce22b9fcd48f4ea474d1924 dado que soluciona problemas de configuracion del dockerfile

### Steps to reproduce

Levantar scheduler process en una máquina local con 20 workers

### Expected result

Que el consumo de ram no sea superior a 2 Gi en memoria ram, (limite del pod en development)

**Comment by acedward** [comment]
@martinmiranda14 hemos encontrado la causa de issue.
