### ISSUE TITLE
Bug report: Diff de hook de actualización de tarea tiene distinta estructura al crear un campo en extensions

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1203]
### Affected system

Cotalker Api

### Affected environment

Production, Staging

### App version

Version 15.0.0 (756)

### Details

**Diff "creando nuevo campo""**

"diff": {
    "/modifiedAt": {
      "previous": "2022-11-14T21:31:34.293Z",
      "changedTo": "2022-11-14T21:31:46.839Z"
    },
    "/extensions/tasks__servicio26": {
      "previous": null,
      "changedTo": {
        "codigo_de_obra": "CGED-21014675",
        "nombre_contratista___servicio_1": "FL INGENIERIA LTDA",
        "nombre_contratista___servicio_2": "FL INGENIERIA LTDA",
        "nombre_contratista___servicio_3": "FL INGENIERIA LTDA",
        "nombre_contratista___servicio_4": "FL INGENIERIA LTDA",
        "comuna": "Cauquenes",
        "numero_de_formulario": "1",
        "otros": "Generar OC segÃºn EDP adjunto",
        "texto_cabecera_oc": "FL INGENIERIA LTDA",
        "cantidad_oc": 1,
        "cantidad_de_reservas": 0,
        "numero_oc": "41771293",
        "numero_de_reservas": "",
        "informacion_adicional": ""
      }
    }
  }

**Diff "actualizando campos ya existentes"**
  "diff": {
    "/modifiedAt": {
      "previous": "2022-11-15T14:25:42.337Z",
      "changedTo": "2022-11-15T14:26:22.634Z"
    },
    "/extensions/tasks__servicio26/nombre_contratista___servicio_1": {
      "previous": "FL INGENIERIA LTDA",
      "changedTo": "FL INGENIERIA LTDA."
    },
    "/extensions/tasks__servicio26/nombre_contratista___servicio_2": {
      "previous": "FL INGENIERIA LTDA",
      "changedTo": "FL INGENIERIA LTDA."
    },
    "/extensions/tasks__servicio26/nombre_contratista___servicio_3": {
      "previous": "FL INGENIERIA LTDA",
      "changedTo": "FL INGENIERIA LTDA."
    },
    "/extensions/tasks__servicio26/nombre_contratista___servicio_4": {
      "previous": "FL INGENIERIA LTDA",
      "changedTo": "FL INGENIERIA LTDA."
    },
    "/extensions/tasks__servicio26/otros": {
      "previous": "Generar OC según EDP adjunto..",
      "changedTo": "Generar OC según EDP adjunto...."
    },
    "/extensions/tasks__servicio26/texto_cabecera_oc": {
      "previous": "FL INGENIERIA LTDA",
      "changedTo": "FL INGENIERIA LTDA."
    }
  }

### Steps to reproduce

.

### Expected result

Que se reciba de la misma forma el diff independiente de si existe o no el campo.

**Comment by gonzalo-d** [comment]
El issue se logró replicar cuando el objeto extensions pasa de un estado vacío:
`{}` a un objeto con profundidad como: `{ propertyName: { schemaInstance1: "value" } }`
Ahora los objetos, cuando se creen las extensions, se verán con su path:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/29810844/208785031-23ac7277-bd10-450b-b47b-e694f6cacd7e.png">

En el proceso, se encontró otro bug que entorpeció un poco el arreglo de este issue. Se creará el issue correspondiente.

Falta hacer QA al fix pero ya está :D
