### ISSUE TITLE
Bug report: En el selector múltiple de tipo usuarios, no aparece uno mismo en la lista cuando se levanta

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1209]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 18.0.0 (310)

### Details

Actualmente la componente de usuarios, no muestra al usuario quien levanta dicho formulario.
Por ejemplo:
Debo levantar un formulario de cierre de un tarea y en el momento de seleccionar el responsable no aparezco y deba "seleccionar" otra persona.

Adjunto un video de prueba donde quiero buscar el administrador usando la componente selector multiple de tipo usuario
![usuario](https://user-images.githubusercontent.com/61419471/202768655-5bf608d5-1463-4fac-9379-93be0fd182fd.gif)

### Steps to reproduce

1.- probar una componente user 
2.- ver si se puede autoasignarse

### Expected result

Es que el usuario pueda verse y poder autoseleccionarse

**Comment by ValeMP** [comment]
@NicolasPLG esto pasa hace mucho tiempo! 
Lo que hacemos en producto es siempre invitar al usuario que respondió el formulario a las tareas. 
Pero si lo que quieres es hacerlo opcional, podrías modelar un componente preguntando si se incluye o no; para así modelar bien a quien invitar a la tarea. 
Te sirve alguna de estas opciones ?

**Comment by NicolasPLG** [comment]
@ValeMP 
En realidad no me sirve eso, porque la persona que registra el fromulario, ya se encuentra en el canal. Además es como decir, registre la persona quien entregó un documento, y en el selector (de usuarios), debería salir quien levanta el fomrulario (como diciendo que fue el/la misma.
:(, pero @gmoplaza lo puede sacar :D

**Comment by ValeMP** [comment]
Perfect, se agrego a la lista de bugs.

**Comment by Sadaka1234** [comment]
Se subirá el fix a staging en los próximos minutos. Ojalá se pueda probar y confirmar si se arregló :D
