### ISSUE TITLE
Bug report: Survey Survey no se despliegan al seleccionarlos 

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1223]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 18.1.1

### Details

En una compañía especifica en prod, al seleccionar los SS en dos formularios específicos, estos no se despliegan. 
Anteriormente estos funcionaban. No se han realizado modificaciones en la implementación).

https://user-images.githubusercontent.com/98488087/205940619-8c8e39af-4659-45b9-8afe-486860a2e170.mov

### Steps to reproduce

Entrar a la compañía
Seleccionar el form correspondiente 
intentar selecciona cualquiera de los 4 SS 

### Expected result

Que se despliegue el SS y poder ingresar respuesta

### Additional data

Al seleccionar el SS de materiales, una vez si se desplegó, al tratar de abrirlo nuevamente (de inmediato) no lo permitió.

**Comment by jdurandpaz** [comment]
@AlexBaader fue en android? ios?

**Comment by AlexBaader** [comment]
android

**Comment by AlexBaader** [comment]
ahora con el mismo usuario y misma tarea, en web muestra 2 formularios (como corresponde) y en la app muestra 5.

https://user-images.githubusercontent.com/98488087/207668909-1920ebd9-29c8-4bcc-951d-19058222a2f5.mp4

Misma OT:

![image](https://user-images.githubusercontent.com/98488087/207668981-52e06997-c3ff-41cb-89bd-0835b06d373c.png)

**Comment by AlexBaader** [comment]
además en la app queda cargando infinito el formulario que queremos revisar (no termina de abrir). En la web si funciona.


https://user-images.githubusercontent.com/98488087/207669346-1c15740a-f645-4bd4-9343-02f2417e03a1.mp4

**Comment by martinmiranda14** [comment]
Subida la versión 18.1.5 en apps móviles donde está corregido el error.
