### ISSUE TITLE
Bug report:  Bucle de llamadas de red al avanzar en el flujo de ordenes de compra

### ISSUE THREAD

**Issue by martinmiranda14** [Cotalker/documentation#1226]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

Cundo cambio el estado de una orden de compra a través del flujo webclient comienza a bombardear con llamadas de red a core

![LiberarOrden](https://user-images.githubusercontent.com/29107230/206264170-531f036a-6850-4f6b-8110-86e9d58e21a5.gif)

### Steps to reproduce

ir a una compañia con preset de ordenes de compra
crear una orden de compra
ponerla como finalizada 

### Expected result

que se cambie de estado sin hacer llamadas infinitas a core

**Comment by AcencioMauricioIcinf** [comment]
Fix ya subido a development, falta que llegue a prod / staging
