### ISSUE TITLE
Bug report: Falla Enlace iOS 

### ISSUE THREAD

**Issue by soporte-cotalker** [Cotalker/documentation#1228]
### Affected system

Cotalker iOS Application

### Affected environment

Production

### App version

1.0 iOS

### Details

Al hacer login en app, no carga interfaz.
Aplicación de iOS “no funciona”. No muestra algunos elementos en la interfaz haciéndola imposible de usar.

### Steps to reproduce

Entrar a Enlace 2.0 iOS
Iniciar sesión con cuenta interna de Enlace.
Al entrar a la pantalla principal no hay ningún dato.

### Expected result

Que la aplicación muestre la interfaz y usuarios puedan trabajar sin problemas.

**Comment by acedward** [comment]
Fixed.
