### ISSUE TITLE
Bug report: Webhook track in notes

### ISSUE THREAD

**Issue by etejedaw** [Cotalker/documentation#1230]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected environment

Production, Staging

### App version

18.1.3 (320)

### Details

Al crear un webhook para que haga seguimiento en las ediciones de notas, este no realiza el track pese a que hayan pasado 10 minutos.

Se probó haciendo seguimiento a la creación de tareas y en este caso sí funcionó. Por lo que al parecer el bug se encuentra solo en el seguimiento de la edición de notas.

### Steps to reproduce

1. Solicitar un URL en https://webhook.site/
2. Insertar esa URL dentro de los Webhook de Cotalker con trigger "Editar Nota"
3. Realizar una edición en cualquier nota realizada

### Expected result

El webhook debería retornar un registro de las notas editadas.

**Comment by MiikeVi** [comment]
Hotfix disponible en production, en unos minutos se actualizará staging
