### ISSUE TITLE
Bug report: No se pueden ver los archivos cargados en la task (directo sin form)

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1245]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

18.2.1

### Details

No se visualizan correctamente los archivos, imágenes , videos cargados directamente en el chat de la task (no a través de formulario) en la pestaña de "DETAILS"

<img width="726" alt="image" src="https://user-images.githubusercontent.com/50208672/208761526-dee89768-1308-442f-8789-4db5e7c5e177.png">

![image](https://user-images.githubusercontent.com/50208672/208761653-f59e4156-bfaa-45df-aae6-0cf5d163afc3.png)

Al presionar view more no se visualiza nada. En canales solos sin task esto funciona.

Además para los usuarios es confuso que la task tenga una pestaña que se llame "FILES" y que solo se vean las notas (no es consistente). 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/50208672/208762422-b915ccee-a3d4-4944-a2d6-6989f5e0baed.png">

También los archivos cargados mediante un formulario deberían verse en la misma parte de forma centralizada , ya sea en "FILES"o en la vista de "DETAILS"

### Steps to reproduce

1. cargar foto a una task (vía chat)
2. ver vista detalles sección imágenes, videos, archivos.

### Expected result

Que se vean los archivos cargados de forma centralizada

**Comment by guillevalin** [comment]
Se confirma bug, funciona en los channels sin tareas, pero no en las tareas.
