### ISSUE TITLE
What's new: Whatsapp Integration

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#135]
Cotalker can now send messages through Whatsapp.

This can be done through the new step "Whatsapp Integration" 
Requirements: Full intl. phone e.g., +56123456789, link and workflow name.

*NOTE* This service has an additional cost per message. 
Contact your Cotalker Representative to get started.

**Comment by acedward** [comment]
Added documentation to PR
https://github.com/Cotalker/documentation/pull/131

**Comment by Mauriceac** [comment]
# Questions:
In the comment above: 
- Is "**link**" the same as the "**contract code**" mentioned in the bot documentation?
- Is "**workflow name**" the same as "**template name**" mentioned in the bot documentation?

------

# "New Features" Preview

![Screen Shot 2021-05-17 at 11 38 31](https://user-images.githubusercontent.com/47286214/118516622-db336080-b70c-11eb-8be1-4297bfd3c56f.png)
