### ISSUE TITLE
What's new: Updated SQL Table names

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#137]
Default tables have been updated to make the model easier to understand
All tables are names have the structure:

```
a) [model]
b) [model]_subtype
c) [model]_[model]
d) [model]_[model]_subtype
 ```
Where **model** is the datatype. 
Singular names are used, when a plural name shows up - it means that it holds relations to many tables.

**Comment by Mauriceac** [comment]
Does this require updating https://doc.cotalker.com/docs/documentation/sql_bi/model ?
