### ISSUE TITLE
Bug report: Botón actualizar en flujo de tareas en mobile es difícil de encontrar 

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#1378]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

18.6.6

### Details

En mobile es dificil para los usuarios encontrar el botón para refrescar el flujo de trabajo en el que se encuentran. Por ejemplo para ver si han sido asignados a alguna nueva tarea.

Web

<img width="936" alt="image" src="https://user-images.githubusercontent.com/50208672/230494450-14e002be-21e3-4a5a-9274-5a61e549700b.png">

Mobile

![image](https://user-images.githubusercontent.com/50208672/230494557-92d1b663-4cab-49fa-8fa2-ff578a135d81.png)

Además el nombre de la acción que aparece al hacer hover sobre el ícono dice "Restaurar" lo que confunde.

### Steps to reproduce

entrar a un flujo de trabajo en mobile e intentar refrescar las tareas/traer los últimos cambios.

### Expected result

Que el botón de Refrescar se vea directamente sin tener que ingresar al botón de opciones adicionales

### Additional data

.

**Comment by ccarrascor** [comment]
closed in (PR#3614)[https://github.com/Cotalker/cotalker-webclient/pull/3614]
