### ISSUE TITLE
What's New: Api tokens

### ISSUE THREAD

**Issue by agallardol** [Cotalker/documentation#138]
# What's an Api Token

Is a feature that using a key (or technically bearer token) bring access to users to use Cotalker Api with diferents permissions levels.

## When this feature could be useful?

Api Tokens could be useful in many cases:
- Partners can give access to part of the company data to external users just sharing a secure key.
- Bots or systems can impersonate other users with just part of their permissions.
- Admins can deactivate or modify permissions to the data at any time.
- Create a secure key to let users and partners send messages in Coralker

## How users could use this feature?

Users can create Api Tokens using Admin and Cotalker Api.

## What we need to create an Api Token?

Using Cotalker admin is the most simple case, users will need:

- A name and a code to identify the Api Token
- A name and an avatar to personificate the user that represents the token (yes, with api token you could send messages to an specific channel)
- A set of access roles to assign to the personificated user.

### Creating a new Api Token

![image](https://user-images.githubusercontent.com/4631063/117048764-58a8ab00-ace1-11eb-8ffb-21a51eca4465.png)

### After creating an Api Token

This popup shows the Authorization token linked to the Api Token. This token will be displayed just once time.

![image](https://user-images.githubusercontent.com/4631063/117048951-8f7ec100-ace1-11eb-82bf-7bcfaba1e430.png)

### Editing an existing Api Token

![image](https://user-images.githubusercontent.com/4631063/117048986-9c9bb000-ace1-11eb-9f84-109c3f8de5a3.png)

### List Api Tokens

![image](https://user-images.githubusercontent.com/4631063/117049093-bdfc9c00-ace1-11eb-8eb1-893a65479f0e.png)

**Comment by agallardol** [comment]
Update: Added feature screenshots. It could be change but theses screenshots represents the main idea and the way Api Token will works.

@Mauriceac @acedward

**Comment by acedward** [comment]
There are two important implicit points here:
*  API Token last forever and ever.
*  But, API Tokens can be revoked at any moment.
