### ISSUE TITLE
Bug report: Imagenes no se guardan correctamente al enviarlas con formularios

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1477]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### Details

Al enviar formularios con imágenes estas no se están enviando. Aparentemente generan una url corrupta.

Esto ocurre desde el día sabado.

https://github.com/Cotalker/documentation/assets/98488087/be7eeb8d-f12b-456c-87c1-f7f2e64e8d48

### Steps to reproduce

Enviar Formulario con imagen

### Expected result

Poder ver imagen

**Comment by CVargasGando** [comment]
duplicado en issue #1475
