### ISSUE TITLE
What's New: Survey Timezones

### ISSUE THREAD

**Issue by rafaelwalter** [Cotalker/documentation#149]
# Summary
This feature defines the timezone on which dates on surveys must be processed.

# Who and how does it help
Admin users must take into account which should be the timezone of a question of type datetime. Without timezones, all dates written by users on surveys were considered to be UTC +0 and it cause confusion on how dates should be processed or used somewhere else. Now when configuring a question of type datetime the administrador will be requested to set the timezone, and all dates inserted by users on this question will be processed with that same timezone. For example, if a question is configured with timezone `Australia/Sydney (UTC +10)` by an administrador, the final users that input the date `2021-05-05 6:00` will be considered to `2021-05-04 20:00` on `Europe/London (UTC +0)`.

# Changes for Users
Users will not see any difference for now, but the dates input will finally behave as expected.

# Changes for Admins & Developers
In the administrador survey builder was added a new timezone input for all question of type datetime.
![Screen Shot 2021-05-04 at 11 36 20 AM](https://user-images.githubusercontent.com/26169103/117073108-7258eb00-acff-11eb-813c-81d442314252.png)
![Screen Shot 2021-05-04 at 11 36 31 AM](https://user-images.githubusercontent.com/26169103/117073096-6ff69100-acff-11eb-9092-8698c8001528.png)

# Expected release date
First week of June.

# Modification / Creation of new sections.
N/A

# (Supplementry information)
N/A

**Comment by acedward** [comment]
Update:
Modification / Creation of new sections.

Requires modification of Admin > Surveys

https://doc.cotalker.com/docs/documentation/admin/admin_survey#date-and-time
