### ISSUE TITLE
SurveyTriggers no se gatillan

### ISSUE THREAD

**Issue by cfernandezo** [Cotalker/documentation#1523]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected environment

Production

### Details

Al realizar una asignación masiva esta acción se realiza de manera parcializada.

### Steps to reproduce

Se sube al formulario el archivo excel tipo con las tareas a asignar.
Algunas tareas no son asignadas y tampoco se puede encontrar el schedule correspondiente.
Pero en el chat de la tarea si esta el formulario enviado, lo que evidentemente no genera ninguna acción.

### Expected result

Que las tareas indicadas en el archivo sean asignadas.

### Additional data

- Company: CGE - 627400d234b48d5b6667db18
- Group: 63126bbb5f672700087fa9b4
- Task: 6494d3eaa10052c1a7eea224

**Comment by guillevalin** [comment]
Se subió un fix a productivo aproximadamente a las 11:50 AM del 11 de julio que corrige este problema.
