### ISSUE TITLE
Feature Request: Pb update property no permite vaciar las subpropiedades

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#1535]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### Details

Cuando se trata de hacer un update property  en una rutina para eliminar todas las subpropiedades de una propiedad (ya sea ingresando un array vacío, undefined o null) falla la etapa. 

Undefinded: 

![image](https://github.com/Cotalker/documentation/assets/98488087/53b32d8d-f7d3-42c3-8203-d880441a4c53)

Null:

![image](https://github.com/Cotalker/documentation/assets/98488087/5842861c-4b7c-4f76-99da-71c376422c9d)

### Steps to reproduce

.

### Expected result

Que permita, al igual que cuando se hace desde el admin, dejar las subpropiedades vacías.

**Comment by jdurandpaz** [comment]
probaron con json patch?
