### ISSUE TITLE
Cuando uno presiona en cualquiert parte de un formulario o mensaje del sistema este lo selecciona todo y dificulta tareas

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1659]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### App version

todas las vigentes

### Details

Es incómodo que quede marcado como seleccionado el texto del sistema, ya que para realizar algunda edición del formulario es imposible. Esto afecta en toda version, ya sea dedicada como compartida. Se adjunta video
![tester 234](https://github.com/Cotalker/documentation/assets/61419471/2ceac0c9-36b6-4a9a-9999-8bbec0421527)

### Steps to reproduce

verlo directamnete

### Expected result

Sacar eso

**Comment by SeIturra** [comment]
Esto nos afecta en varios clientes
