### ISSUE TITLE
Update Certification Diagram

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#17]
This was just a internal image when we where brainstorming about the process.
Can you please update this image 

![image](https://user-images.githubusercontent.com/3951895/113300775-a726ec00-92d4-11eb-841f-5445b18267b3.png)

**Comment by Mauriceac** [comment]
What do you have in mind when you say "update" the image? Make it prettier? Change arrangement? Are there any conceptual changes that also have to be made to this section of the documentation?

**Comment by acedward** [comment]
Yes just nicer. This image was made to show how the steps will be connected and the entry points.
Everybody should start at sales or basic-admin and then move downwards, the lines are requirements.

**Comment by Mauriceac** [comment]
## Here's a draft of the diagram. 
*It's a bit too much, but I wanted to show the process. I also gave names to the steps for clarity and making each level sound special. Once approved, maybe I could ask the designer for help.*

![Certification Levels (1)](https://user-images.githubusercontent.com/47286214/113465955-34219080-940e-11eb-8b65-e4ef4f2be627.png)

**Comment by Mauriceac** [comment]
Here's a draft:

![Certification Levels (3)](https://user-images.githubusercontent.com/47286214/113580279-e10d3080-95fb-11eb-88ea-d0a225921750.png)

**Comment by acedward** [comment]
Looks great! :t-rex:

**Comment by acedward** [comment]
The "Admin" at level 2 doesn't require Sales Training.

**Comment by Mauriceac** [comment]
# How about this? 
I didn't add more levels because it could be confusing.
It keeps things smooth for those following only a technical career.
I kinda like it better because both "consultants" are paired up:

![Certification Levels (4)](https://user-images.githubusercontent.com/47286214/113586160-8c6db380-9603-11eb-95da-54b5721eb40b.png)

**Comment by acedward** [comment]
Looks great! Let's go with this
