### ISSUE TITLE
Bug report: no autoredirecciona la cuenta a l ainfra correspondiente con la nueva versión

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#1776]
### Affected system

Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### App version

21.4.8

### Details

Cliente reporta que no puede acceder su cuenta dado que utiliza la app cotlaker pero redireccionado a la infra dedicada

Se adjunta video con la versión 20.2.2 y si puede acceder

https://github.com/user-attachments/assets/cd518c0c-47c8-4d31-a199-6f9b66b3c4f3

Se adjunta video con la versión 21.4.8 y no puede acceder

https://github.com/user-attachments/assets/99806fb9-aa63-48a7-9219-07a3bf77ebc8

### Steps to reproduce

1.- usar dispositivo conla ultima version de la app
2.- ingresar cuenta
3.- probar

### Expected result

deberia redireccionarse de manera correcta a la infrarespectiva

**Comment by guillevalin** [comment]
Se subió hotfix versión 21.5.0 a las tiendas de Android e iOS.
