### ISSUE TITLE
What's New: Unified Search

### ISSUE THREAD

**Issue by rafaelwalter** [Cotalker/documentation#250]
# Summary
This new feature allows us to search all information in Cotalker in a precise and concise way.

# Who and how does it help
Allows user to find and navigate with ease. It will show information of contacts, tasks, channels and elements.

# Changes for Users
It will replace current global search by a new search interface.
Before:
![Screen Shot 2021-06-08 at 1 29 45 PM](https://user-images.githubusercontent.com/26169103/121230732-9dce7880-c85d-11eb-946c-fd02f3ae8a83.png)

After:
![Screen Shot 2021-06-08 at 1 30 14 PM](https://user-images.githubusercontent.com/26169103/121230779-ab83fe00-c85d-11eb-9fa8-13ffc72c6122.png)

# Changes for Admins & Developers
This does not affect admin or developer users.

# Expected release date
End of June.

# Modification / Creation of new sections.
Does not affect other sections.

**Comment by Mauriceac** [comment]
## PREGUNTA: ¿Cómo se accede al buscador?
![Screen Shot 2021-06-10 at 4 27 19 PM](https://user-images.githubusercontent.com/47286214/121592784-25a4b600-ca09-11eb-8c3f-cc1c29244ff6.png)
- ¿Sólo a través del menu prinicipal?
- ¿Habrá algún tipo de "shortcut" u otro lugar donde se puede invocar?

**Comment by rafaelwalter** [comment]
@Mauriceac se podrá acceder al buscador por 2 botones distintos.

1. Botón de search en menu.
2. Botón de search en la barra sobre la lista de canales.
