### ISSUE TITLE
What's New: PBCalendar

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#365]
# Summary
Send ICS invitations via email 

# Who and how does it help
Now bots can send invitations to any email.
Most email clients will show an event.

# Changes for Users
None

# Changes for Admins & Developers
New Bot Called PBCalendar (2.0.0) 
(version 1 was never published)

# Expected release date
Aug 2021

# Modification / Creation of new sections.
New Bot

# (Supplementry information)

Setup example
```
            {
                "_id" : "5f59923c42d99d000982d0aa", 
                "key" : "calendar", 
                "name" : "PBCalendar", 
                "version" : "2.0.0", 
                "data" : {
                    "title" : "PBCalendar Event", 
                    "description" : "Description of event", 
                    "initialDate" : ISODate("2021-08-05T20:51:30.551+0000"), 
                    "durationMinutes" : 30.0, 
                    "invitedById" : [
                        "5f6cfcaf7e081c0008502f3a", 
                        "5bc9ffc7f25ac42f0410179d"
                    ], 
                    "invitedByEmail" : [
                        "sample@gmail.com"
                    ], 
                    "owner" : "5f57dc679d700e0008cc131e"
                }, 
                "customNetworkRequest" : [

                ], 
                "next" : {
                    "DEFAULT" : null
                }
            }
``` 

![Frame 1](https://user-images.githubusercontent.com/3951895/128424870-d1ef004b-1198-4450-b83c-8ca1bbcc82e9.png)

**Comment by acedward** [comment]
Minor update:

### initialDate

now allows multiple input types
 
1) ISODate e.g.  "2021-09-01T21:31:45.093Z"
2) Survey Date Answer     $VALUE#answer|data[find=>identifier=myidentifier]|process|0   
3) Date Object    $VALUE#createdAt

**Comment by Mauriceac** [comment]
@acedward 
Only for `initialDate`? Not `endDate`?

**Comment by acedward** [comment]
oh s**t, i forgot.
