### ISSUE TITLE
Survey Components Hierarchy

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#37]
Our survey have many components, 
most components have sub-types:
e.g.,  multiple-choice has "tree", "list", "property" and "user",
as plain-inputs have "text" and "numbers" 

![image](https://user-images.githubusercontent.com/3951895/113740706-f3a46a00-96ce-11eb-911b-d73cbb0b4ae1.png)

We should some how try to list them in a orderly fashion and/or hierarchy

**Comment by Mauriceac** [comment]
Yeah... I noticed this as well. It's very messy.

My first reaction would be to have a table describing the components and adding links to separate pages for component details. 
Next, we would also have to arrange the documentation navigation bar and make "Survey" a subdirectory with all the components under it.

Should I start on that now? (The Survey page also needs to be grammatically reviewed.)
Any other ideas?

**Comment by acedward** [comment]
I like the sub-page option, with links from the parent

**Comment by Mauriceac** [comment]
The survey section has been re-done according to the specifications. "Survey" now has two sub-directories: "Overview" and "Components". Each component has its own sub-page under "components".
