### ISSUE TITLE
Bug report: No es posible reactivar un elemento que fue desactivado

### ISSUE THREAD

**Issue by agallardol** [Cotalker/documentation#405]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Affected environment (other)

-

### App version

16.4.5 (143)

### Discussed in https://github.com/Cotalker/documentation/discussions/402

Al desactivar una property, esta ya no aparece en la lista de properties. Si se quiere reactivarla, no hay forma de verla en la lista para poder acceder a editarla

### Steps to reproduce

1. Ir a admin de properties
2. Seleccionar una de la lista
3. Desactivarla
4. Ir a admin de properties
5. Intentar reactivar la property desactivada

### Expected result

Al desactivar una property debe exisir una forma de acceder a ella para poder reactivarla

### Additional data

-

**Comment by z0rro2k** [comment]
Hola. Si en un futuro de puede volver a activar un objeto desactivado,. Pueden avisarme? Gracias

**Comment by agallardol** [comment]
@z0rro2k Estamos trabajando por resolver esto. Cerraremos este mismo issue cuando esté disponible. Como workaround es posible usar la API

**Comment by z0rro2k** [comment]
Gracias

**Comment by z0rro2k** [comment]
hola,
  no vi vien la respuesta ... cual api permite reacticar un item de pantalla ya desactivado?

gracias

**Comment by agallardol** [comment]
> Hola. Si en un futuro de puede volver a activar un objeto desactivado,. Pueden avisarme? Gracias

Hola, esta funcionalidad ya se encuentra disponible en la versión 17.0.2, si tienes cualquier otro inconveniente no dudes en abrir un discussion, nosotros feliz te ayudamos.

Muchas gracias por reportar!
