### ISSUE TITLE
Documentation > Remove import collection feature

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#406]
# Sección to be revised
https://doc.cotalker.com/docs/documentation/admin/admin_properties#import-collection

# Objective
Import collection is deprecated on latest releases.

# Details
We offered this feature in the past but now is deprecated and removed from the admin panel, and could cause confusion between partners.

# Other
We could offer a tutorial to how to do this using Postman and Collections API.

# Priority
Medium

**Comment by guillevalin** [comment]
@Mauriceac Ya existe una guía de esto, sería genial tenerlo en la documentación como ejemplo:

[Manual_Postman_2021.pdf](https://github.com/Cotalker/documentation/files/7170886/Manual_Postman_2021.pdf)

**Comment by acedward** [comment]
We do have a new software for importing, but is a standalone solution.

**Comment by acedward** [comment]
Alternatives to importing 

* Scripts using the API
* Postman (o similar softwares)
* Our standalone solution

**Comment by guillevalin** [comment]
> Alternatives to importing
> 
> * Scripts using the API
> * Postman (o similar software)
> * Our standalone solution
> * Manually through the admin

Probably is a better solution for most (simpler) use cases using postman instead of installing a docker container from the importer project on our infrastructure?
