### ISSUE TITLE
What's New: Task*Permissions

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#440]
# Summary
Tasks Editors and Followers Permissions. 

# Who and how does it help
Now users can be editors or followers of all tasks within a task-group.
Permissions can be set globally by task group, or by a certain state o status{1,5}

# Changes for Users
Users can now participate in tasks, as editor or follower, without being in the exact user-list

# Changes for Admins & Developers
This allows easy access control by permission, instead of setting it up user-by-user
(But user-by-user is still available and completely supported)

SIDE EFFECTS:
Users WILL NOT receive push-notifications when messages are sent to channels that they participate by permissions.
To receive notifications, they must OPT-IN into the user list.

E.g., Setup:
```
taskGroup.taskFollowerPermissions = [permission1, permission2];
taskGroup.taskEditorPermissions =  [permission3]
taskPropertyPermissions = [{
 property: '1234567890' , //  e.g., 'high-priority'
 editor: [permission4]
 follower: []
},{
 property: 'abcdef012354', // e.g.,  'backlog' 
 editor: [],
 follower: [permission5]
}]
```
Users with
```
*  permission1 or permission2 will be EDITORS of ALL tasks
*  permission3 will be FOLLOWERS of ALL tasks
*  permission4 will be EDITOR that have the state or status{1,5} = 'high-priority'
*  permission5 will be FOLLOWERS of tasks with state or status{1,5} = 'backlog' 
```

# Expected release date
NOW

# Modification / Creation of new sections.
No changes in admin.
This can be setup by API at the time.

# (Supplementary information)
This feature is in a BETA stage, but is available for usage and will continue being updated 

TaskGroup model update new fields:
```
  taskPropertyPermissions: {
    property: ObjectId,    //  COTProperty
    editor: string[], // permissions
    follower: string[], // permissions
  }[];

  taskFollowerPermissions: string[]; // permissions

  taskEditorPermissions: string[]; // permissions
```
 
API EXAMPLE:
```
curl -XPATCH https:// www.cotalker.com/api/tasks/group/61545d987c442500079ad37a -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OTAxMTg3ZjFkYWJlY2M5MjYxNmJiNGUiLCJlbWFpbCI6ImVkd2FyZEBjb3RhbGtlci5jb20iLCJyb2xlIjoidXNlciIsImNvbXBhbnkiOiI1OGZlODNlZGE4YjcyNTk2MjViOWIxNWQiLCJkYXRlIjoxNjMyNzgwODQ1MTg1LCJpYXQiOjE2MzI3ODA4NDV9.hBLDyzfFKipDX70z2pD9MPeaieKscRfw-gqRc1XctGI" -H "Content-Type: application/json"  -d ' { "taskEditorPermissions": ["default", "app-access"],  "_id": "61545d987c442500079ad37a" } '
```

**Comment by Mauriceac** [comment]
> ```
> -H "Authorization: Bearer {ACCESS-TOKEN}" 
> -H "Content-Type: application/json"  -d ' { "taskEditorPermissions": ["default", "app-access"]} '  
> ```
> 
> Did this work? It shouldn't ! (this should be available at /v1/ or /v3/)

I tried it in v3 (staging) but changed it in the example because the original example you sent was in V2.
And I think Guillermo said only V2 was available for "prod".
How should I write it? v1? or v3?
