### ISSUE TITLE
Bug report: No se puede Levantar un formulario que permite crear tareas a la SM Operaciones

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#447]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.1.1 (148)

### Details

En la SM de operaciones tenemos un survey (GP) Crear tarea al proyecto, que permite crear tareas a una tarea padre. El tema es que actualmente no se puede cargar por lo que no podemos crear tareas al padre (o proyecto en este caso).

### Steps to reproduce

1.- Ir al grupo Operaciones
2.- Ir a un canal de proyectos (cualquiera que se encuentre en la maquina), o en su defecto a COTALKER - 2021-2
3.- Levantar el formulario (GP) Crear tarea al proyecto
4.- Esperar que se cargue el formulario

### Expected result

Que se pueda cargar de manera correcta

### Additional data

TaskChannel: 60ddf2fe1ed9a7000968e8eb
Survey: 5e18baf3229bf30c57922004
Company: 58fe83eda8b7259625b9b15d

**Comment by agallardol** [comment]
Corregido, estará disponible en el release 17.1.2. Gracias por reportar!  #mil
