### ISSUE TITLE
Bug report: No se muestran los archivos subidos en questions tipo file

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#450]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

15.0.0 (362)

### Details

Al visualizar un formulario enviado que tiene un archivo subido, se ve como si no hubiese ningún archivo, luego, si se cambia el formulario al modo de edición, el archivo aparece. Si cambio de canal y vuelvo al anterior, el comportamiento se repite

### Steps to reproduce

1. Enviar un formulario con un archivo cargado en una question de tipo file (en el formulario no se verá el archivo enviado).
2. Cambiar la vista a otro canal y volver al canal original o refrescar la página.
3. Cambiar el formulario a modo de edición. Se visualizará el archivo.

### Expected result

Se debería ver el archivo cargado en la question tipo file siempre

**Comment by agallardol** [comment]
@guillevalin trabajo en este issue. Debería estar disponible en 17.5.10
