### ISSUE TITLE
Section Name and i18n

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#47]
![image](https://user-images.githubusercontent.com/3951895/114056794-04d0b080-9860-11eb-88dd-3a70aa0c045b.png)

It looks like a ` { text } ` slipped through.
We should also change the name from `Required Surveys`  (required surveys is the internal name to describe that they are required when a creation or state change is triggered, and the surveys blocks the transition)

Perhaps something in the lines of `Starting Surveys` and `State-Change Surveys`

**Comment by Mauriceac** [comment]
I've been working on **Workflows**.
This will be fixed in the next commit.
I'm going through all of it again, rearranging the menu, and inserting new images.
