### ISSUE TITLE
Search muestra acciones en flujos desactivados en cliente con infra dedicada 

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#487]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

17.1.2

### Details

En barra global del search muestra como acciones, inicio de flujos desactivados. En este caso "Gestión avisos" 

![image](https://user-images.githubusercontent.com/50208672/137786591-9a366879-2858-4fde-8158-58cabbd5e16e.png)

### Steps to reproduce

Ingresar a ambiente qa cliente infra dedicada y utilizar el buscador.

### Expected result

Que no se muestren las acciones de flujos desactivados

**Comment by agallardol** [comment]
Estará disponible en el siguiente release
