### ISSUE TITLE
Error en Reloj Cotalker - Versión tiendas (android e iOS) y Web no concuerdan

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#493]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### App version

17.2.4

### Details

En plataforma móviles nuevamente no permite ingresar los tiempos con detalle al minuto

Interfaz sólo permite incrementos de 5 min.

Versión de app en tienda y web no coinciden.

![image](https://user-images.githubusercontent.com/51834544/137756448-84129b09-e592-40dc-acb1-c0e8f1a3141b.png)

![image](https://user-images.githubusercontent.com/51834544/137756489-bfeed40c-0c0f-4857-89dc-7aec7c21b471.png)

Referencia discussion: https://github.com/Cotalker/documentation/discussions/483

### Steps to reproduce

Completar mismo formulario con date/time en web y app mobile.

### Expected result

Que se pueda seleccionar tanto en web como en mobile con rango mínimo de 1 minuto.

**Comment by agallardol** [comment]
Estamos trabajando en este issue, está un poco más complejo de lo que esperábamos
