### ISSUE TITLE
Habilitar flag para no permitir edición en formularios

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#515]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

17.2.7

### Details

En ciertos flujos de clientes se requiere limitar que los forms se puedan editar y enviar nuevamente. Por ejemplo para evitar hacer doble envío de información hacia otros sistemas.

### Steps to reproduce

Enviar formulario, editarlo, modificar un valor y enviarlo nuevamente.

### Expected result

Que sea posible configurar a nivel de formulario si un formulario es editable en el flujo.

**Comment by acedward** [comment]
Movido al roadmap.
