### ISSUE TITLE
Bug report: User (visibility) removed from task but not from channel

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#516]
### Affected system

Cotalker Api

### Affected environment

Development

### App version

17.2.7

### Details

Removí a través de la api patch tasks/:taskgroup/task/:id un usuario del campo visbility. Por tanto, esperaría que también sea removido automáticamente del canal, pero no fue así. 
Revisando por segunda vez, el usuario no estaba asociada a la task, pero sí al canal.

### Steps to reproduce

1. Usar el endpoint patch tasks/:taskgroup/task/:id  para remover un usuario del campo "visbility"
2. Revisar con el endpoint de get channel/:id los usuarios del canal para observar si el usuarios ha sido removido también.

### Expected result

Que el usuario sea removido del canal asociado a la task, cuando es removido de la task

**Comment by acedward** [comment]
Abrimos un proyecto para corregir esto.
Vamos a hacer cambios significativos para poder mejorar la experiencia.

PD: https://web.cotalker.com/document/note/617c251ac169e24f1fb70da0/editor (se requiere cuenta @cotalker.com) para ver la nueva especificación

**Comment by acedward** [comment]
@ValeMP @guillevalin El feature de Tareas Jerarquicas los estamos deprecando. ¿Cómo podemos hacer esto sin jerarquia?
