### ISSUE TITLE
No se actualizan los formularios del botón de acciones en los cambios de estado

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#521]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### Affected environment (other)

Cliente infra dedicada 

### App version

17.2.7

### Details

Al realizar un cambio de estado y actualizar las propiedades del canal para mostrar distintos formularios, no se muestran los formularios del botón de acciones correctamente. Para que funcione hay que actualizar o entrar a otro canal y volver al original.

**Luego del cambio de estado (formularios incorrectos)**

![image](https://user-images.githubusercontent.com/50208672/139336603-21584d59-b383-443d-a7ca-363227fbf489.png)

**Luego de actualizar la página (F5) o cambiar de canal** (formularios correctos)

![image](https://user-images.githubusercontent.com/50208672/139336770-c3845661-d994-40ca-b7bd-417650d2f1a4.png)

### Steps to reproduce

Ingresar a flujo de trabajo y pasar aviso de asignado a en tratamiento.
Ingresar a flujo de trabajo y pasar de pospuesto a en tratamiento.

### Expected result

Que los formularios mostrados sean los correctos.

**Comment by acedward** [comment]
Fixed with workaround.
