### ISSUE TITLE
What's New: Azure AD Configuration

### ISSUE THREAD

**Issue by eduborgono** [Cotalker/documentation#530]
# Summary
This configuration allows Cotalker to use Azure AD to sign in users.

# Who and how does it help
This helps companies to use Cotalker with their registered users in Azure AD.

# Changes for Users
Users will be able to sign in to Cotalker using their Microsoft Work Account.

![Captura de pantalla de 2021-11-08 11-02-27](https://user-images.githubusercontent.com/22122681/140755450-619c5a53-4ca2-48cd-b299-451cf5d2345c.png)

# Changes for Admins & Developers
-

# Expected release date
TBD.

# Modification / Creation of new sections.
New Microsoft sign in button in login view.

# (Supplementary information)

Cotalker needs some sort of configuration in Azure to be able of sign in with Microsoft work accounts.
Steps to reproduce:

1. Sign in to the Azure portal.
2. If you have access to multiple tenants, use the Directory + subscription filter  in the top menu to select the tenant in which you want to register an application.
3. Search for and select Azure Active Directory.
4. Under Manage (left side section), select App registrations > New registration.
![Captura de pantalla de 2021-11-08 11-45-55](https://user-images.githubusercontent.com/22122681/140763977-8c886795-d561-43fe-955f-e19cfb3a7cce.png)

5. Enter a Name for the application. Users of Cotalker might see this name, and you can change it later. In this case "Cotalker" is a suitable name.
6. Choose "Accounts in this organizational directory only" as the Supported account type for the application. Do NOT enter a Redirect URI.
7. Select Register to create the app registration.
8. Under Manage, select Authentication > Add a platform.
9. Under Web applications, select the Single-page application tile.
10. Under Redirect URIs, enter a redirect URI. This value is supplied by Cotalker. Do NOT enter a redirect URI that was not supplied by Cotalker. Do NOT select either checkbox under Implicit grant and hybrid flows.
11. Select Configure to finish adding the redirect URI.
12. Under Manage, select Token configuration > Add optional claim.
13. Under Token type select ID. Then select "email", "family_name" and "given_name".
14. Select Add to continue adding the optional claim.
15. A popup should appear with the text "Some of these claims (email, familiy_name, given_name) require OpenId Connect scopes to be configured through the API permissions page or by checking the box below". The checkbox "Turn on the Microsoft Graph email, profile permission (required for claims to appear in token) must be selected.
16. Select Add to finish adding the optional claim.

Also Cotalker needs two values from the previously created app. These values are "Application (client) ID" and "Directory (tenant) ID" are under the Overview option in the previously created app view.

**Comment by Mauriceac** [comment]
@eduborgono Estamos casi listos. Sólo tengo una pregunta. En la última indicación, ¿qué se debe hacer con "Application (client) ID" y "Directory (tenant) ID"? ¿Dónde se van a requerir o quién se los entrego?

**Comment by Mauriceac** [comment]
Aquí está un "preview" del What's New y una nueva sección que agregué las instrucciones para configurar Azure.

## What's New
![Screen Shot 2021-11-10 at 1 07 49 PM](https://user-images.githubusercontent.com/47286214/141149272-cf11a724-9caf-4862-a978-78604e96ac8e.png)

## PDF Preview
[Microsoft Azure AD Sign-in Configuration _ Partner & Technical Consultants Documentation.pdf](https://github.com/Cotalker/documentation/files/7514204/Microsoft.Azure.AD.Sign-in.Configuration._.Partner.Technical.Consultants.Documentation.pdf)
w
