### ISSUE TITLE
Bug report: No funciona el link del correo para cambiar contraseña

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#540]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.5.3 (172)

### Details

En el momento que presiono en el botón "olvidaste una contraseña", envía un correo y el link del correo manda a un error

![image](https://user-images.githubusercontent.com/61419471/142418971-45ac7bd0-db46-40f5-b4d9-c2de98d5a40f.png)

![image](https://user-images.githubusercontent.com/61419471/142418976-b29de1f7-1914-4123-8319-2414c44723d8.png)

### Steps to reproduce

1.- Colocar en web.cotalker.com/login o bci.cotalker.com
2.- Colocar el correo
3.- Presionar olvidaste la contraseña
4.- ver la bandeja de correo y abri el not reply
5.- presionar el link

### Expected result

deberia poder colocar la contraseña nueva

**Comment by agallardol** [comment]
Solved, disponible en 17.5.3
