### ISSUE TITLE
Bug report: Componente cargar documento muestra cod en la vista de carga

### ISSUE THREAD

**Issue by Revolverabd** [Cotalker/documentation#546]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Al levantar un formularo, el compononte de files no falla pero muestra código de estructura de carga.

{"name":"carga-prueba-test.xlsx","fid":"619b9cdb9b5de1c7b65f48cd","url":"https://cotalker-us-files.s3.amazonaws.com/coopeuch/document/v4_619b9cdb9b5de1c7b65f48cd/default/carga-prueba-test.xlsx","codeType":"ms/excel","contentType":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","screenshots":[]}

### Steps to reproduce

1.- presionar Agregar
2.- esperar los segundos de carga

### Expected result

Vista del documento cargado para continuar con el formulario.

### Additional data

-Group id -> 616d86f3b707e90007cddb0a
-Form id -> 616dddbdb707e90007ce7c2f

**Comment by agallardol** [comment]
@gmoplaza

**Comment by agallardol** [comment]
@Revolverabd Edité el issue para eliminar datos relativos a usuarios

**Comment by gmoplaza** [comment]
Solucionado en el milestone 17.5.8
