### ISSUE TITLE
Bug report: Vista de task se pega al cargar

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#551]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.5.8

### Details

Al cargar la vista de task, se queda la pestaña de chrome pegada

![bug_task_251121](https://user-images.githubusercontent.com/50208672/143498962-d47c3512-db50-408c-ae5e-fd741edf06cc.png)

** No permite desplegar sección ** 
![image](https://user-images.githubusercontent.com/50208672/143500301-60ee68db-15b7-45cc-a350-cbbbd6dc15e4.png)

### Steps to reproduce

Abrir vista de task en un flujo de trabajo que tenga múltiple task

### Expected result

Que no se pegue la página y se carguen de forma correcta las tasks.

### Additional data

- Company: Cotalker
- Group : Operaciones (sub flujo optask)

**Comment by agallardol** [comment]
Tenemos planificado un rework de la vista de lista, por lo que no abordaremos directamente este bug (ocurre bajo condiciones específicas)
