### ISSUE TITLE
Bug report: Canales creados por creación de tasks no se pasan a PostgreSQL

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#558]
### Affected system

Cotalker Api

### Affected system (other)

SQL

### Affected environment

Production

### Affected environment (other)

Ambiente propio de compañía cliente

### App version

17.5.3 (172)

### Details

Cuando se crean tareas, no todos los canales creados se pasan a la BD SQL

### Steps to reproduce

Crear varias tareas usando una rutina.
Ver los canales que pasaron al SQL.
Sólo algunos canales se pasan al SQL.

### Expected result

Todos los canales deberían haber pasado al SQL.

**Comment by MiikeVi** [comment]
Esto pasa siempre? es decir, cada vez que se crean X cantidad de tareas, algunos canales no se ven reflejados en SQL? Cuántas tareas se crean para que llegue a pasar aprox? Este comportamiento se ve super random y no logro reproducir :(

**Comment by agallardol** [comment]
@SeIturra Congelaremos este bug hasta que ocurra de nuevo e intentaremos reproducir otra vez
