### ISSUE TITLE
Update Documentation with filter information 

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#56]
https://doc.cotalker.com/docs/documentation/admin/admin_survey#multiple-choice

Should explain how the filter works. 
Any questions, in the discussions thread
https://github.com/Cotalker/documentation/discussions/50

------------------------
Hola!

Quería saber si me podrían explicar un poco sobre el filtro de un multiple choice en un survey. Me gustaría saber si en la casilla de al lado, se configura la operación o si siempre sería "equal".

Les adjunto una imagen! 
![Screen Shot 2021-04-08 at 13 57 54](https://user-images.githubusercontent.com/42095617/114075032-11123900-9873-11eb-8a35-a93b8737aab4.png)

_Originally posted by @ValeMP in https://github.com/Cotalker/documentation/discussions/50_

**Comment by Mauriceac** [comment]
duplicate #156
