### ISSUE TITLE
Bug report: Selector de fecha permite modificar valor en formularios ya enviados

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#573]
### Affected system

Cotalker iOS Application

### Affected system (other)

Cliente con infra dedicada

### Affected environment

Production

### App version

17.5.4

### Details

El selector de fecha aparece con un UX distinto al resto de los campos y además permite su edición aún cuando el formulario esta enviado.

![IMG_0654](https://user-images.githubusercontent.com/50208672/144911092-767e938d-4412-4e4d-adbc-9d7ded83cfa3.PNG)

### Steps to reproduce

1. Ingresar a una orden
2. Completar formulario de aceptación (ingresando fecha)
3. Cambiar fecha de formulario ya enviado.

### Expected result

Que el diseño de la question de fecha sea igual al resto y que no se pueda modificar si el form ya se envio.

### Additional data

- Company: Cliente infra dedicada
- Group: Correctivas industriales
- Channel: Cualquier orden

**Comment by martinmiranda14** [comment]
Se Prueba Bug en ios y no se logra replicar
