### ISSUE TITLE
No se visualizaba el calculo de una question con exec validate (esto es regularización)

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#579]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.5.10 (187)

### Details

En un survey existen 3 campos numéricos  (A,B,C) y en la cual el campo "C" contiene un exec de validación con una operación entre los campos "A" con "B" y cuyo resultado no se visualizaba en el campo "C", pero si hacia el cálculo.

El exec es este:

```
   "exec" : {
        "validate" : {
            "src" : "async function run() {const commands = [];const peso = Number(context['responses#peso_hepatopancreaticobiliar']);console.log('peso:', peso);const altura = Number(context['responses#talla_hepatopancreaticobiliar']);console.log('altura:', altura);if (!altura || !peso) {commands.push({cmd: 'SET_RESPONSES',value: ''});commands.push({cmd: 'SET_READONLY',value: 'true'});return commands;}var imc = peso / (altura ** 2);console.log('imc:', imc);commands.push({cmd: 'SET_RESPONSES',value: imc,target:'imc_hepatopancreaticobiliar'}); commands.push(  {  cmd: 'RESULT',    value: 'true' });console.log(commands);return commands;}", 
            "context" : "responses#peso_hepatopancreaticobiliar,responses#talla_hepatopancreaticobiliar"
        }
    }
```

### Steps to reproduce

Esto ya está resuelto por lo que no colocaré los pasos

### Expected result

Esto ya está resuelto por lo que no colocaré los pasos

**Comment by agallardol** [comment]
Corregido
