### ISSUE TITLE
Improve "Where Surveys Show Up"

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#580]
# Sección to be revised
Documentation > Admin Docs > Data > Surveys > Overview

# Objective
Users should be able to show/hide surveys in specific channels.

# Details

Currently we have this description:

![image](https://user-images.githubusercontent.com/3951895/145819012-9c1d03e8-267c-4661-b2de-45ebc0f25eaa.png)

Which is technically correct, but might be difficult to understand how to set this up correctly.

I think we should show a diagram how these two dimensions work together (permissions and properties) 
and son examples for channels and tasks.

# Other

# Priority
Low

**Comment by Mauriceac** [comment]
![Screenshot_2022-02-03-17-31-10-221_com.android.chrome.jpg](https://user-images.githubusercontent.com/47286214/152424150-b96279d3-8082-4970-88fc-3065c23e29c9.jpg)

https://doc.cotalker.com/docs/documentation/admin/survey/survey_overview#access


- Diagram and explanation added.
- Entire section revised.
