### ISSUE TITLE
Bug report: Al hacer click en el botón para ver nota, nada pasa 

### ISSUE THREAD

**Issue by constanzamorales** [Cotalker/documentation#582]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.5.11 (190)

### Details

Al hacer click en una tarea, y ver las notas, el botón con el ícono de ojo no realiza ninguna acción visible.
![Screenshot 2021-12-13 at 13 39 15](https://user-images.githubusercontent.com/64158242/145852422-7f70d782-260b-44a5-9534-401e66e0cefa.png)

### Steps to reproduce

1. Click en Product Team
2. Click en Design Tasks
3. Click en Roadmap 2022
4. Click en header y se deplegará el panel con información de la tarea
5. Click en Notes
6. Click en el botón con ícono de ojo
![Uploading Screenshot 2021-12-13 at 13.42.51.png…]()

### Expected result

Al hacer click en el ícono de ojo, debería llevar al usuario a ver la nota

**Comment by agallardol** [comment]
Corregido, estará en 17.6.0
