### ISSUE TITLE
el buscador principal no está trayendo el titulo actualizado de una nota (Bci scripting)

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#589]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.5.12 (192)

### Details

Cuando se realiza la búsqueda de una nota, no muestra el titulo actualizado de ésta y al abrir dicho documento, aparece el titulo actualizado, como también abrirlo en una tasks de forma directa.

### Steps to reproduce

1.- ir a bci.cotalker.com
2.- ingresar con usuario admin
3.- realizar la búsqueda por "Bloqueo de tarjeta en app Bci" debe salir el nombre no actualizado
4.- entrar a la sm "inbound", y filtrar por app bci y se verán todos los nombres actualizados

Teoria:  puede que la creación masiva de tasks y notas haya generado esa inconsistencia

### Expected result

Debiese poder verse el último cambio

### Additional data

company:  ObjectId("6147c23a9c5e6f8dbc0b982e")
"web" : "https://bci.cotalker.com"
 "subdomain" : "bciscripting",

**Comment by agallardol** [comment]
Resuelto
