### ISSUE TITLE
Remove Unbound from admin options.

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#598]
A pesar de la determinación de hacer que los tasks asuman el tipo "bound", los _state machines_ con la opción "unbound" siguen creando _tasks_ con canales que no funcionan correctamente.

https://user-images.githubusercontent.com/47286214/146158961-78a3e5f0-53f9-4cfb-8975-9fae36e73ae6.mp4

_Originally posted by @Mauriceac in https://github.com/Cotalker/documentation/discussions/568_

**Comment by agallardol** [comment]
Corregido. Quitamos esta configuración desde admin
