### ISSUE TITLE
Bug report: question exec validate SET_RESPONSES con target survey+text no funciona

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#603]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.5.8

### Details

Buenas navidades a todus.

No sucede nada al intentar cambiar el valor que muestra una question de tipo survey+text utilizando question exec validate con la siguiente configuración:
[{"cmd":"SET_RESPONSES","target":"<identifier_de_otra_question_del_formulario>","value":"test"}]

### Steps to reproduce

1. En un formulario con al menos una question de tipo survey+text, crear un question exec validate (en otra question) que cambie el valor de lo que muestra la question de texto utilizando el siguiente valor de retorno de la función run() del exec: [{"cmd":"SET_RESPONSES","target":"<identifier_de_question_survey+text>","value":"test"}]
2. Ejecutar el question exec.

### Expected result

El texto que muestra la question survey+text debería cambiar.

**Comment by agallardol** [comment]
Cerramos este bug, entiendo que es un problema con la versión de la app
