### ISSUE TITLE
Bug report: changing passwords in android doesn't show any warning

### ISSUE THREAD

**Issue by Sadaka1234** [Cotalker/documentation#604]
### Affected system

Cotalker Android Application

### Affected environment

Production

### App version

17.5.12

### Details

When you try to change your password in the android app, there is no save button.

Once both of the new passwords match, the button shows up, but there is nothing telling you what are you doing wrong in case both of the new passwords are different.

![androidcoso](https://user-images.githubusercontent.com/29810844/147473797-5cc3bdfd-5f12-430b-91d4-4d0745fde0be.jpg)

### Steps to reproduce

1. Log in the android app
2. Go to change password
3. You will see there is no "change password" button, and if both of "new passwords" are different, nothing will tell you that they are different, and the button won't show up.

### Expected result

Some kind of warning that tells you that both of the passwords doesn't match. Basically what's the problem that causes the button to not show up.

**Comment by MiikeVi** [comment]
Solved
