### ISSUE TITLE
Tutorial > Basic

### ISSUE THREAD

**Issue by rionio** [Cotalker/documentation#610]
# Sección to be revised
Documentation > Basic >Creation Groups & Channels

# Objective
there are no option "Secondary actions"

# Details
In the documentation, it doesn't explain what is "Secondary Actions" and it doesn't appear 

# Other

# Priority
Low

**Comment by Mauriceac** [comment]
So sorry! 😥

Do you mean this: https://doc.cotalker.com/docs/documentation/admin/admin_group#secondary-actions

Thanks for the feedback!

**Comment by rionio** [comment]
yeah, I think that in the tutorial has to be a little explanation of what is the secondary action, but thanks.

**Comment by Mauriceac** [comment]
Ah! Ok, I understand now. THANKS!
