### ISSUE TITLE
En el send survey genera un error de user not found

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#611]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

 Versión 17.6.0 (203)

### Details

En el momentos de hacer pruebas y algunos cambios de contenid0, detectamos que el PBsendsurvey nos está generando error "user not found"

Adjunto 2 SS.

**SS de la rutina**
![image](https://user-images.githubusercontent.com/61419471/148079535-f362dfe8-f0e3-4e16-b920-7e1f34c6a80a.png)

**SS del resultado**
![image](https://user-images.githubusercontent.com/61419471/148078468-7a3c21e3-61fa-42a0-a82f-1daae26cd5a4.png)

### Steps to reproduce

1.- crear un send_survey
2.- colocar un usuario con id directo
3.- Probar

### Expected result

Deberia enviar el formulario

### Additional data

No aplica porque lo probé en tratton y sale el mismo error: 
_id bot prueba en tratton: 61d46419419eea00070f92ea

**Comment by agallardol** [comment]
@NicolasPLG Podrías revisar si esto sigue ocurriendo?
Ayer detectamos un bug en nuestra api de users que ya fue corregido.

Muchas gracias!

**Comment by NicolasPLG** [comment]
@agallardol si ahora no sale el error de user, solo que ahora arroja otro error: 0: "Cannot read property 'fecha_solicitud_prm_1634791712390' of undefined".

@SeIturra está creando el issue sobre el tema

**Comment by agallardol** [comment]
Gracias, cerraré este issue
