### ISSUE TITLE
No se puede acceder notes desde el channel de la sm

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#618]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.6.1 (204)

### Details

En el momento de abrir una note de una sm arroja este mensaje

{"statusCode":403,"message":"Forbidden resource","error":"Forbidden"}

### Steps to reproduce

ingresar a una nota que se encuentre en una sm

### Expected result

Se pueda ver las notas

### Additional data

no aplica porque afecta a todo

**Comment by MiikeVi** [comment]
Hola @NicolasPLG se está trabajando en un fix para esto, por mientras la única solución es hacer re-login
