### ISSUE TITLE
No existe un validador de code duplicados en los schemasInstance de una company

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#629]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.6.1 (204)

### Details

Hola

Me percaté que puedo agregar schemas instance con el mismo code en cualquier propertyType. El sistema no está arrojando que el code está duplicado.

Ejemplo:

Tengo las propertyTypes A,B,C y D y quiero agregar un schema numérico "Valor" con Code valor, para las 4 propertyTypes. El resultado es que el sistema si me deja agregarlas para cada propertyType.

El problema es cuando quiero usar un NWR para buscar el schemas de "C" "Valor", y el resultado será que arrojará un error para obtener "Valor" en "C", siendo que ese "code", está en "A". 

### Steps to reproduce

1.- dos propertyTypes "A" y "B" crear schemas con el mismo code.

2.- Hacer una llamada de red "B"

3.- Enviar el schema de "B" en un mensaje.

El resultado deberia ser un error 400

### Expected result

Exista tambien un aviso de code duplicado

### Additional data

no aplica porque puede ser cualquier compañia

**Comment by MiikeVi** [comment]
Hola, no es un error de code duplicados. Es posible tener un schema con el mismo code para propertyType "A" y "B" sin ningún problema, por eso es que no existe ninguna advertencia. Por favor cuando ocurra nuevamente, abrir un issue adjuntando Automation log de la rutina y resultado, gracias!
