### ISSUE TITLE
Bug report: PBTaskAddeditor 2.1.0

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#640]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.6.3 (207)

### Details

Hola a todos

Creo que hay un problema con el PBTaskAddeditor 2.1.0 en el momento que escoges el tipo: user

Dejo esta parte de la rutina
```
{
                "_id" : ObjectId("61e034013e2edb0007731c93"), 
                "key" : "get_user", 
                "name" : "NWRequest", 
                "version" : "2.0.0", 
                "data" : {
                    "url" : "$JOIN#/#($ENV#BASEURL)#api#users#find", 
                    "method" : "GET", 
                    "headers" : {
                        "admin" : true
                    }, 
                    "defaultAuth" : true, 
                    "body" : {
                        "_id" : "$VALUE#data|[find=>identifier=seleccione_usuario_cotalker]|process|0"
                    }
                }, 
                "next" : {
                    "SUCCESS" : "invite_user", 
                    "ERROR" : ""
                }, 
                "customNetworkRequest" : [

                ]
            }, 
            {
                "_id" : ObjectId("61e032dc3fb33800077a6c32"), 
                "key" : "invite_user", 
                "name" : "PBTaskAddEditor", 
                "version" : "2.1.0", 
                "data" : {
                    "type" : "user", 
                    "user" : "$OUTPUT#get_user#data|_id", 
                    "task" : "$OUTPUT#get_task#data|_id", 
                    "taskGroup" : "5e0f9ce5bd891701378ba6d4", 
                    "operation" : "eq"
                }, 
                "next" : {
                    "SUCCESS" : "wait", 
                    "ERROR" : ""
                }, 
                "customNetworkRequest" : [

                ]
            }
```

El resultado en los logs es:

```
key: "get_user"
name: "NWRequest"
status: "SUCCESS"
result:
statusCode: 200
data:
0:
name: Object {"displayName":"","names":"tester","lastName":"testser","secondLastName":""}
avatar: Object {"small":"","square":"","original":""}
role: "user"
_id: "60c7bd6522ee4b00081f1c3b"
email: "tesre@tester.cl"
phone: "561"
jobTitle: "CTO"
job: "60f5ab572a50200007f3a3ed"
modifiedAt: "2022-01-13T14:07:04.963Z"
isActive: true
extra: Object {"prreview":{"lastrequest":"","rerolls":""},"badges":{"awards":"","currentbadge":""}}
profileInfo: Array[0] []
nextBot: "invite_user"
iteration: 5
3:
key: "invite_user"
name: "PBTaskAddEditor"
status: "ERROR"
result:
errors:
0: ""user" is required"
nextBot: ""
```

### Steps to reproduce

1.- Revisar rutina bot: {_id:ObjectId("61e02d263e2edb000772ff4c")}
2.- Ver el automatic logs
3.- Ver las etapas indicadas

### Expected result

Cómo se deberia usar ese tipo

### Additional data

Company: 
bot: {_id:ObjectId("61e02d263e2edb000772ff4c")}
  "company" : ObjectId("58fe83eda8b7259625b9b15d"),

**Comment by acedward** [comment]
Pienso que deberíamos unificar:

EDIT TASK
https://doc.cotalker.com/docs/documentation/automation/bots/pbchangestate-2.0.0/
https://doc.cotalker.com/docs/documentation/automation/bots/pbupdatetask-2.0.1/
https://doc.cotalker.com/docs/documentation/automation/bots/pbtaskaddeditor-2.0.0/

CREATE TASK
https://doc.cotalker.com/docs/documentation/automation/bots/pbduplicatetask-2.0.0/
https://doc.cotalker.com/docs/documentation/automation/bots/pbcreatetask-2.0.1/

**Comment by eduborgono** [comment]
El error que describes nicho se debe a la expresión de cotlang que usaste `$OUTPUT#get_user#data|_id` al probarla contra el playground de cotlang arroja vacío, que es efectivamente el error que te muestra el log:
![Captura de Pantalla 2022-03-17 a la(s) 22 53 06](https://user-images.githubusercontent.com/22122681/158922424-fcf3b348-3b59-476d-a70a-f1fe0cceb217.png)

Si cambiamos la expresión a la siguiente `$OUTPUT#get_user#data` el resultado queda como
![Captura de Pantalla 2022-03-17 a la(s) 22 54 54](https://user-images.githubusercontent.com/22122681/158922586-ba7da7eb-12d3-490e-ae4b-fe90c9cca316.png)

Que vendría a ser un arreglo, si quieres acceder a la id la expresión debería quedar así `$OUTPUT#get_user#data|0|_id`
![Captura de Pantalla 2022-03-17 a la(s) 22 56 28](https://user-images.githubusercontent.com/22122681/158922762-73b50231-44d5-4aa8-8089-1b6fe7a36cb1.png)

Sin embargo esto no es suficiente, dado que el input de usuarios del bot espera que se le pase un arreglo de ids, no una id suelta así que hay que preocuparse de manejar eso, por ejemplo con `["$OUTPUT#get_user#data|0|_id"]`.

De todas formas, se añadió una nueva versión que da la opción para incluir solo un usuario en la versión 2.2.0 del bot.

**Comment by NicolasPLG** [comment]
Perfecto muchas gracias @eduborgono , faltó colocar el 0
SAlu2
