### ISSUE TITLE
Bug report: Problemas para agregar usuarios en canal usando el teclado

### ISSUE THREAD

**Issue by Mauriceac** [Cotalker/documentation#645]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

Version 17.6.3 (205)

### Details

When I try to add users to a channel, if I use the keyboard instead of mouse to select the user from the drop-down menu, the drop-down menu gets stuck and no more users can be added.

### Steps to reproduce

1. Create new channel
2. Go the "participants" section of channel settings panel
3. type the first letters of a user's name to have the drop-down menu appear with suggestions
4. chose a suggestion with the keyboard (arrows and enter buttons)
5. the drop-down menu will only show the names of the last suggestion, making it impossible to continue to add more users.

### Expected result

It should be possible to choose a new user from the suggestions given in the drop-down menu either with the mouse or keyboard.

### Additional data

https://user-images.githubusercontent.com/47286214/149810655-35c65cb1-dd6e-4997-b209-35f87d2079e8.mp4

**Comment by agallardol** [comment]
@Mauriceac Vamos a cerrar este issue, implementamos un rework de este tipo de inputs que estará disponible en el próximo release de Febrero
