### ISSUE TITLE
Bug report: Problems with survey permissions

### ISSUE THREAD

**Issue by Mauriceac** [Cotalker/documentation#648]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

Version 17.6.3 (207)

### Details

A user with an access role containing the following permissions cannot create a survey:
`admin-access` + `admin-surveys-write` + `admin-accesscontrol-write` + `admin-groups-write` + `admin-taskgroups-write` + `admin-channels-write` + `admin-surveys-write` + `admin-properties-write` + `admin-tasks-write`.
There are supposedly the permissions to the endpoints related to surveys. 
Maybe more permissions are required?

### Steps to reproduce

1. User with the following permissions: `admin-access` + `admin-surveys-write` + `admin-accesscontrol-write` + `admin-groups-write` + `admin-taskgroups-write` + `admin-channels-write` + `admin-surveys-write` + `admin-properties-write` + `admin-tasks-write`
2. Go to the Administrative Panel
3. Go to the Surveys section
4. Try creating a survey.
5. Access Roles and Group permissions cannot be selected.
6. Save (no response returned)

### Expected result

Users with the following permissions should be able to create surveys:
`admin-access` + `admin-surveys-write` + `admin-accesscontrol-write` + `admin-groups-write` + `admin-taskgroups-write` + `admin-channels-write` + `admin-surveys-write` + `admin-properties-write` + `admin-tasks-write`

**Comment by MiikeVi** [comment]
solved
