### ISSUE TITLE
Bug report: Survey survey + isCommanded 🤯 desaparece pero aparece al enviar

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#655]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.5.14 (202) 

### Details

Cuando se tiene un survey survey comandado por otra question (visualización condicional) si se agregan subformularios y luego se cambia dos veces su estado de visualización condicional (mostrar=>no mostrar=>mostrar), todos los subformularios desaparecen pero cuando se envía el formulario padre al canal, reaparecen todos los que desaparecieron.

Tampoco funciona el resetIdentifiers sobre survey survey, que podría solucionar este problema en parte al menos ya que no estaríamos enviando la data. El contra es que se perdería información.

### Steps to reproduce

1. Tener una question survey survey como comandada
2. Agregar sub formularios
3. Esconder question survey survey (hasta aquí todo bien)
4. Al volver a hacerla aparecer, no aparecen los sub formularios agregados anteriormente
5. Al enviar el formulario aparecen todos los sub formularios que habían desaparecido anteriormente

### Expected result

En el paso 4 deberían aparecer los sub formularios agregados anteriormente

**Comment by agallardol** [comment]
@SeIturra Esto ya está corregido y disponible en production
