### ISSUE TITLE
Search de task no funciona en cliente con infa dedicada

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#657]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.5.4

### Details

Al hacer una búsqueda de task no se encuentran resultados,  tanto en el buscador global como en el contextual del grupo.

![image](https://user-images.githubusercontent.com/50208672/150424545-7e8f704f-53f3-49d3-af85-e38dc63d0049.png)

![image](https://user-images.githubusercontent.com/50208672/150424612-ea3a1fb8-6eec-4674-9a55-307b501a0615.png)

Sin embargo la búsqueda si funciona con canales.

En BD la config esta de esta forma: 

`"searchEngines" : [
        {
            "name" : "tasksElastic"
        }, 
        {
            "name" : "channels"
        }
    ]`

### Steps to reproduce

Ingresar a una cuenta (solicitar credenciales) y realizar una búsqueda de una task dek  grupo Telecanal

### Expected result

Que se puedan buscar task y se muestren resultados

**Comment by jdurandpaz** [comment]
@ccarrascor 

![image](https://user-images.githubusercontent.com/50208672/150425318-224f5612-6446-44ca-9c10-1c0de2752ffe.png)

**Comment by jdurandpaz** [comment]
se agregaron indexes y funciona el buscador global, pero no el de contextualizado de cada grupo @acedward

**Comment by eduborgono** [comment]
- Se añadieron validadores para que el servicio no pueda arrancar sin las variables globales necesarias.
- Se corrigió el bug que no permitía buscar tareas por contextos
