### ISSUE TITLE
Bug report: Notas se abren en modo "editor" en vez de modo "viewer" para cliente

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#661]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.6.4

### Details

Cliente con solución de gestión de conocimiento que típicamente consulta procedimientos (notas) incluidas en cada tarea creada, ha tenido siempre la funcionalidad de abrir notas en modo viewer. Sin emabrgo, desde el 24-ene-2021 se están abriendo todas las notas en modo "editor" por default.

### Steps to reproduce

1. Entrar a cualquier tarea desde url dedicada de producción de este cliente 
2. Buscar palabra y seleccionar una nota o ingresar a cualquier tarea y expandir nota asociada dentro de la tarea
3. Debería abrir nota en pestaña nueva y se verá en modo editor en vez de modo "viewer"

### Expected result

Que las notas se abran por default para todos los usuarios, independiente de su rol con modo viewer por default

**Comment by gmoplaza** [comment]
El problema no se pudo replicar, seguramente fue arreglado en una actualización
