### ISSUE TITLE
Bug report: Campos limitados, no permite agregar más de 6 Campos a una Colección 

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#664]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

 17.7.0

### Details

En una empresa ficticia creada para la práctica con tutoriales, al crear una nueva colección, el sistema no permite agregar más de 6 campos, indicando que el usuario no cuenta con los permisos para ello. 

### Steps to reproduce

1. Ingresar a base de datos como administrador 
2. Crear colección 
3. Agregar campos hasta que ya no lo permita el sistema (6 en mi caso
![Uploading BUG.jpg…]()
)

### Expected result

Agregar Campo

**Comment by MiikeVi** [comment]
No logré replicar bug, tengo entendido que hace unas semanas se realizó una tarea grande de corrección de permisos.
