### ISSUE TITLE
Bug report: No está funcionando el external survey/link publico

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#666]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.1 (210)

### Details

En el momento en que se configura un survey link externo éste no aparece.

Se adjunta link explicativo:

Link: https://drive.google.com/file/d/1KJWUSwp-cgG_vgfUpREPcpGNL_iBwlDE/view?usp=sharing

### Steps to reproduce

1.- los pasos se deben seguir como se visualiza en el video

### Expected result

Que se pueda visualizar

### Additional data

Todas las compañias le afectan el survey public

**Comment by agallardol** [comment]
Fixed
