### ISSUE TITLE
What's New: Dynamic Input

### ISSUE THREAD

**Issue by gabowo001** [Cotalker/documentation#676]
# Summary
This new input works on the child classes of base-autocomplete-input, changing the previous search layout for a dialog that let us search and choose items.

# Who and how does it help
The previous autocomplete input was sometimes uncomfortable, with no initial search and rough display when you have a lot of items selected, we solved it with a dialog that appears by clicking the input, it sorts the items as a list so we can scroll through it with a better performance.

# Changes for Users
In the dialog a list of items is displayed, so users can select and deselect this items in a more confortable way, aditionally, it has control of the limit of options that can be selected, blocking the selection when you reach the limit (DEMO below).

# Changes for Admins & Developers
There's a new module on admin-shared called dynamic-input, it manages the dialog and has some custom interfaces, it is connected to base-autocomplete-input and works in its child classes.

# Expected release date
04-02-2022

# Modification / Creation of new sections.
- New Module called dynamic-input
- Modified base-autocomplete-input and its child classes to work with dynamic-input
- Added DynamicInputModule to the admin modules who use base-autocomplete-input

# (Supplementary information)
Here's an explained DEMO for the new input:

https://user-images.githubusercontent.com/94371363/152411858-95e4e36d-56f2-43da-94eb-011495815c0b.mp4

**Comment by Mauriceac** [comment]
@gabowo001 Que buen feature! Hacía falta.
¿Esto cuándo estará en dev? Para poder empezar a sacar los screen shots.
