### ISSUE TITLE
Public Surveys

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#68]
@agallardol por favor comentarle a @Mauriceac como funciona esto para publicarlo :)

**Comment by Mauriceac** [comment]
**Por favor, revisar.**
- *Se me olivdó un poco el tema de los subtasks y de cómo obtener el ID de los parent tasks.*
- Creo que debo incluir "Public Surveys" en *Admin > Surveys*, pero también podría estar en *Admin > Workflows > Required Surveys*. Por último incluyo un link en Required Surveys que vaya a *Admin > Surveys*.
- Habría que arreglar el cuadro de diálogo (Ver imagen al final).


Preview
----------

### Public Survey

Sometimes companies might want to give people outside the Cotalker environment the opportunity to create a task. For example, customers who recur for support can fill out a form with their issue and automatically create a Cotalker task that would act as a support ticket. We call this feature a _public survey_.

:::important
Public Surveys only work with _initial workflow start forms_. Nonetheless, we offer a [workaround](#public-survey-subtask) for associating public surveys with _subtask start forms_. Some manual tweaking is required. We wish to have this integrated into our GUI sometime soon.
:::

### Basic Setup
From <span className="badge badge--primary">Administration</span>, go to <span className="badge badge--primary">Workflows</span> section, select a **workflow group**, and finally choose the corresponding **workflow**.

The [workflow settings panel](docs/documentation/admin/workflows/admin_workflow_configure#edit-a-single-workflow) will open up.

In the **Start Form** field, choose the desired survey. Once a _survey_ has been selected, the <span className="badge badge--secondary">Share</span> button appears.

![admin_survey_share_00](https://user-images.githubusercontent.com/47286214/115270390-a2569a80-a112-11eb-9fc7-aa2f62a4409b.png)

Press the <span className="badge badge--secondary">Share</span> button. A _Share survey_ dialog box will appear. The **Share** field has two options: _Restricted_ and _Any People with the Link_.

![admin_survey_share_01](https://user-images.githubusercontent.com/47286214/115280054-dc796980-a11d-11eb-8d1b-cdc563bea8bb.png)


:::note
- The public access link, _Any People with the Link_ option, only works if there is no open Cotalker session in the browser.
- The _Restricted_ access option is not fully operational. For now, users can open the link, but cannot send the survey.
:::

After selecting the option, copy the URL. Now you can share the link, add it to an email, or copy it into a webpage, or whatever suits you best to let people outside the Cotalker environment answer your survey.

:::note
- For security reasons, the following [survey components](/docs/documentation/admin/admin_survey) do not function in the public survey: _properties_, _user_, and _files_.
- Survey embedding has not yet been developed but is in our backlog for future updates.
:::

_Here is an example of what users might see when they access public surveys:_

![admin_survey_share_02](https://user-images.githubusercontent.com/47286214/115280127-f5821a80-a11d-11eb-8adf-069deb15f5d6.png)


_And this is what users are expected to see when the survey is sent successfully:_

![admin_survey_share_03](https://user-images.githubusercontent.com/47286214/115280197-09c61780-a11e-11eb-9a2d-7328ff44c08d.png)

### Public Survey for Subtasks {#public-survey-subtask}

Public surveys work ideally with initial workflows, but we offer here a workaround to associate a public survey with a subtask.

1. Encode the following body at https://www.base64encode.org/:
```json
  {
      "parentTask": "abcdefgh1234567890"
  }
```
2. Copy the generated code.
3. Get the public link.
4. Add the following parameter to the public link: `?data=[base64token]`, where _base64token_ is the generated code obtained through https://www.base64encode.org/.
5. You can now share the modified URL to allow visitors complete the subtask's public survey.

### Adding a Message {#adding-message}

Once visitors respond the survey, a screen appears indicating that the survey was sent successfully. You may add a message to this screen by following the indicated steps:

1. Encode the following body at https://www.base64encode.org/:
```json
  {
      "parentTask": "abcdefgh1234567890"
      "sentMessage": "We have received your message."
  }
```
2. Copy the generated code.
3. Get the public link.
4. Add the following parameter to the public link: `?data=[base64token]`, where _base64token_ is the generated code obtained through https://www.base64encode.org/.
5. Visitors will see your message once they send the form.

-----------------

# English Review
![Screen Shot 2021-04-19 at 13 55 16](https://user-images.githubusercontent.com/47286214/115282184-485cd180-a120-11eb-987e-c512f209ca0f.png)

**Comment by acedward** [comment]
@Mauriceac es mejor colocar estas mismas dudas en el PR:
Porque normalmente PR es la solución al issue (y todos tienden a mirar los PR que los issues)
Ahi también puedes solicitar reviewers y también existe más presión porque el código está "casi-listo"

**Comment by acedward** [comment]
@Mauriceac 

1. Se me olivdó un poco el tema de los subtasks y de cómo obtener el ID de los parent tasks.

se puede obtener de la URL o desde la API

![image](https://user-images.githubusercontent.com/3951895/115751911-9c0d2c00-a367-11eb-8362-dcb9ba05dd32.png)

2. Creo que debo incluir "Public Surveys" en Admin > Surveys, pero también podría estar en Admin > Workflows > Required Surveys. 

Admin > Surveys 
es más para temas del survey en si mismo, sus campos etc.
Creo que una referencia, a workflows seríá bueno

Admin > Workflows > Public Surveys 
creo que es un mejor lugar, porque es funcional para un workflow

3. Por último incluyo un link en Required Surveys que vaya a Admin > Surveys.
Habría que arreglar el cuadro de diálogo (Ver imagen al final).

No entendí bien este último punto
