### ISSUE TITLE
Bug report: visualización de un campo con QuestionExec

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#689]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Detalles se encuentran aquí #683 

### Steps to reproduce

1. Ejecutar el formulario y sobrescribir campo "Costo".
2. Al mandar el formulario, no se logra visualizar el campo con el valor sobrescrito.

### Expected result

Visualizar el campo Costo del formulario cuando el usuario sobrescribe el valor que aparece por defecto.

**Comment by AcencioMauricioIcinf** [comment]
@CVargasGando Hola! Podrías por favor pasarme las credenciales que necesito para testear este bug?

**Comment by AcencioMauricioIcinf** [comment]
Issue resolved by newly reworked code [here](https://github.com/Cotalker/documentation/discussions/683#discussioncomment-2569540)
