### ISSUE TITLE
Bug report: En el momento de hacer login, el fondo queda con la pagina de web.cotalker

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#699]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.5 (217)

### Details

Cuando uno hace login aparece esto:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/61419471/153926841-f4b612bf-de00-488c-aa60-2de6e03fb369.png">

### Steps to reproduce

iniciar sesión con cualquier cuenta

### Expected result

no deberia aparecer

### Additional data

no aplica

**Comment by agallardol** [comment]
Disponible en 17.7.6
