### ISSUE TITLE
What's new: Tree Selector

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#7]
The new property - tree selector is available in development environments.
Please add this to what's new and to the survey-property section.
@Mauriceac @gmoplaza @rafaelwalter

**Comment by gmoplaza** [comment]
![image](https://user-images.githubusercontent.com/9313324/113584329-c4bbc480-95f8-11eb-91c1-b91bf6c791ed.png)
![image](https://user-images.githubusercontent.com/9313324/113584350-cab1a580-95f8-11eb-8455-7317f7124a50.png)
Las preguntas de tipo **colección** pueden ser configuradas para tener un **comportamiento de jerarquia**. En caso de habilitar esta opción, es obligatorio definir cual es la **colección objetivo** que se desea guardar (las "hojas") o las propiedades del último nivel.

Opcionalmente, se pueden configurar filtros. Estos permiten definir que elementos se mostraran según las colecciones seleccionadas. OJO! en importante selecionar TODAS las colecciones que SI se quieren ver para tener un correcto funcionamiento de la pregunta.

Teniendo esto bien configurado, una pregunta de colección con selección de jerarquía permitirá "navegar" desde un nodo inicial (la colección seleccionada inicialmente, con todas las opciones que ya tiene una pregunta de tipo colección) e ir seleccionando nuevos elementos hijos hasta llegar a elementos de la colección objetivo.

**Comment by Mauriceac** [comment]
**Draft for "What's New"**

> Surveys are great, and they just got better! Users can now answer questions with the help of *tree collections*. Choose a general answer which will lead you to a more specific category. For example, a question configured to specify a location can start by asking for *country*, then *region*, and finally *city*.
