### ISSUE TITLE
Bug report: Desde el admin, no se pueden ver los canales de un workflow

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#700]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.5 (217)

### Details

AL ingresar a un workflow y ver sus canales, éste no queda con la vista de channel sino una de task, y no mostrará nada.

1.- Foto 1
<img width="457" alt="image" src="https://user-images.githubusercontent.com/61419471/153928582-81a70422-ef2b-4402-a159-9a1557dbedc8.png">

2.- Foto 2

<img width="597" alt="image" src="https://user-images.githubusercontent.com/61419471/153928485-12829b1f-8bb8-4cbb-9b78-f984550038a6.png">

### Steps to reproduce

Como se ven las imagenes son los pasos a realizar

### Expected result

Que se puedan visualizar los canales del workflow

### Additional data

no aplica

**Comment by agallardol** [comment]
Solved
