### ISSUE TITLE
Bug report: Creador de rutinas. Cuando se crean mas de dos etapas vacías no te permitirá guardar la rutina

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#704]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.8 (220)

### Details

Cuando uno quiere agregar rutinas vacías y las completas, el sistema no permitirá guardar. Sin embargo si se construyen una a una, el sistema permitirá guardar.

Adjunto un video de lo que estoy diciendo: https://drive.google.com/file/d/1LBJJpUHoyjaiTy9dYWwa3nikxcnq5FRt/view?usp=sharing

Gracias =)

### Steps to reproduce

1.- Repertir los pasos según como se muestra el video

### Expected result

Que fuese como la versión anterior, crear varias etapas de rutinas vacias, para luego completarla y anexarlas al sistema.

### Additional data

no aplica

**Comment by MiikeVi** [comment]
No logré reproducir, al parecer se corrigió hace tiempo, cerraré este issue, porfavor si el problema persiste abrir uno nuevo, gracias!
