### ISSUE TITLE
Bug report: Property-Schema-Node File Input does not work at tasks  

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#712]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

When setting up a Task with a unique property , that has a File schema node type field - it does not work in the task view.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/3951895/155155946-3476013e-8c65-482b-81b8-a52cb165318b.png">

### Steps to reproduce

task -> detail -> try to upload file

### Expected result

File is uploaded

**Comment by agallardol** [comment]
No logramos reproducir en ningún ambiente, daremos por cerrado hasta que podamos detectarlo de nuevo. Adicionalmente viene un rework de ese componente
