### ISSUE TITLE
Bug report: No se ven los channels que sin relacion a tasks y no se ve el buscador

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#713]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.8 (220)

### Details

En el momento de ingresar a un workflow se ven el listado de los channels tasks, pero no muestra los channels que pertenecen al grupo y no corresponde a una tasks. Con respecto al buscador tampoco existe o está habilitado el buscador.

Tuvimos que hacer atras de un channel tasks para luego poder ver los canales.

se deja video explicativo: https://drive.google.com/file/d/1nAeYMTlDSEpwMnApr-ufLiV0NvYAQ0F-/view

### Steps to reproduce

1.- entrar a un workflow
2.- entrar a canales del workflow
3.- entrar a una tasks
4.- retroceder
5.- aparecerán los canales y el buscador

### Expected result

Debiese verse:

1.- los canales que no son taskjs
2.- el buscador para buscar dichos canales (los canales que tengan relación a una tarea y los canales que no tengan relación a una tarea (por ejemplo canal de conversación)

### Additional data

No aplica

**Comment by acedward** [comment]
Está deprecado crear canales en workflows de tareas.

**Comment by acedward** [comment]
@NicolasPLG si necesitas más información por favor contactame!
