### ISSUE TITLE
Bug report: Estado de usuarios desaparece del front

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#724]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Affected environment (other)

Cliente infra dedicada 

### App version

17.7.5

### Details

En ciertas ocasiones no se muestra en el front, el selector para cambiar el estado del usuario (CONECTADO, OCUPADO)

- No se muestra (omitir recuadro rojo)
<img width="618" alt="image" src="https://user-images.githubusercontent.com/50208672/155807509-d603f319-4ac7-4ef8-af92-19a6bac43e12.png">

- Se muestra

<img width="372" alt="image" src="https://user-images.githubusercontent.com/50208672/155807572-578bdf7f-b394-4588-8061-0df5eafc3c8a.png">

### Steps to reproduce

Interactuar entre los grupos o canales, y verificar que en ciertos momentos el selector e indicador de estado desaparece.

### Expected result

Que sea consistente y no desaparezca ya que para este proyecto es clave que los usuarios puedan modificar su estado, debido a que se asignan avisos por estado de usuario.

**Comment by jdurandpaz** [comment]
@acedward @agallardol este issue en que quedó? , lamentablemente copec volvió a levantarlo.

**Comment by agallardol** [comment]
Voy a darlo por cerrado, ya que implementamos varias mejoras que deberían haber corregido esto. Si vuelven a verlo lo reportamos de nuevo!
