### ISSUE TITLE
Bug report: Reports no funciona en compañías creadas mediante self service

### ISSUE THREAD

**Issue by agallardol** [Cotalker/documentation#725]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Affected environment (other)

cotalker-playground

### App version

17.7.9

### Details

![Uploading image.png…]()

### Steps to reproduce

1. Crear compañía en self service
2. Acceder a módulo de reports

### Expected result

Luego de crear una compañía, poder acceder correctamente al módulo de reports y descargar la data

**Comment by acedward** [comment]
(1) Problema con traducciones destruía los logs - corregido en exporter-importer & lib-solutions [corregido]
(2) No estaba implementado en nueva instalación la creación de la bd pgsql [corregido]
(3) Falta de algunas variables de entorno en exporter-importer [corregido]
(4) Lectura de BD fallando desde svc-tables [corregido]

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/3951895/156894200-fa593bdf-2ad1-4b89-89da-ed1a661cdb04.png">

**Comment by acedward** [comment]
Fixed.
