### ISSUE TITLE
Bug report: No se guarda la rutina si mueves de una rutina incompleta a otra

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#727]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.9 (222)

### Details

El error presenta cuando tienes rutinas incompletas que cambias a otra rutina para volver la incompleta y creo que queda "pegado" el validador o mensaje de error de manera interna

Ejemplo

Tengo 2 rutinas (A y B), de enviar mensaje donde "A" es mi rutina completa y "B" es la nueva que la estoy completando. En el caso que B quiero que quien lo envie es el mismo que en al rutina "A", voy a la rutina "A", copio el userId, voy a "B", pego el userId y no me dejará de guardar. Sin embargo creo nuevamente otra rutina "C", eliminando "B", completando todos los datos si me dejará guardar.

Ahora en el caso de "C", donde me deja guardar la rutina, elimino el campo de texto, me aparece el error, voy a la rutina "A", regreso a "C" y escribo el mensaje de texto, el sistema no me permitirá guardar.

No vi en redes el error que genera pero si lo pude replicar, en el video adjunto se puede ver.

Link: https://drive.google.com/file/d/16vPZjaoJ0Y-uys_Cs2uFgcH6edW11Yuk/view?usp=sharing

gracias =)

### Steps to reproduce

1.- Seguir el ejemplo del video
2.- Hacer los pasos

### Expected result

No debería generar ese error, ya que habitualmente un implementador requiere una información de una rutina anterior para completarla

### Additional data

No Aplica

**Comment by acedward** [comment]
¿Creo que es Alto no crítico, porque hay workaround?

**Comment by eduborgono** [comment]
Se encuentra corregido en dev
