### ISSUE TITLE
Bug report: Can't create a new property

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#728]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

When I try to create a new property which has a name that includes invalid characters, even though they aren't used on the code, it gives an error anyways:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/34345309/156387195-2b0129c8-0c40-496e-9a0e-e8eafdb4c70d.png">

Removing the invalid characters from the display it allows to create the property, this is a bug, but also is not clear the real cause of the error.

### Steps to reproduce

1. Database
2. Collections
3. Add new element
4. Use the name "1. New Item" for display
5. Automatically it will populate the code as "new_item"
6. Press "Save"
7. An error will appear.

### Expected result

It should allow to create the item since "new_item" is a valid code. Also, "Unknown error" is a very vague error description and the user doesn't know what's going on.

**Comment by MiikeVi** [comment]
Al parecer ya no pasa, se ve resuelto, cerrare el issue
