### ISSUE TITLE
Rol de acceso en addUsers funciona con ‘name’ y no con ‘id’.

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#745]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

En la etapa  de una rutina de "Editar usuarios de una tarea", si el campo "Criterio" es "accessRole", en el campo "Rol de acceso" se pide: "ID DEL ROL DE ACCESO QUE DEBEN TENER LOS USUARIOS EN CASO DE QUE EL CRITERIO SEA 'ACCESSROLE", sin embargo, no funciona con el 'id', sino que funciona con el 'name' del access role. 

### Steps to reproduce

1. Crear etapa "Editar usuarios de una tarea" en una rutina
<img width="922" alt="Captura de Pantalla 2022-03-10 a la(s) 11 30 59" src="https://user-images.githubusercontent.com/73865460/157683308-6f753204-c034-44a0-8560-ef565e7df8ab.png">
<img width="928" alt="Captura de Pantalla 2022-03-10 a la(s) 11 31 50" src="https://user-images.githubusercontent.com/73865460/157683455-d00d32ad-6588-456c-b591-860fbf44e009.png">

2. Al probar con el 'id' no funciona:
<img width="327" alt="Captura de Pantalla 2022-03-10 a la(s) 11 35 55" src="https://user-images.githubusercontent.com/73865460/157684178-b137f1f3-0bbf-44e6-b23d-fd7497d52911.png">

Pero con 'name' sí funciona. 

### Expected result

Se espera que funcione con el 'id' como se indica en el campo. O sería mejor que lo que salga escrito sea: 'NAME del rol de acceso que deben tener los usuarios en caso de que el criterio sea accessrole'.

**Comment by eduborgono** [comment]
En producción
