### ISSUE TITLE
Bug report: COTLang no se resuelve

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#752]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging, Development

### App version

17.7.10

### Details

Estoy construyendo un JSON para poder poblar las extensions de una task, como tiene elementos complejos que no son strings que vienen dentro de otros COTLang, utilicé $JOIN para unir los elementos del objeto, el cual funciona correctamente en "COTLang Playgound":
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/34345309/157947265-070caf68-bd3c-440e-b6f5-c56ee13adc0b.png">

Sin embargo, no se resuelve al ejecutar la rutina y "extensions" queda como undefined:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/34345309/157947373-18beb198-0c2d-4170-93a4-6e83fdca67cd.png">

### Steps to reproduce

Consultar los datos a @guillevalin para reproducir el problema.

Sin embargo, incluyo el contexto y el COTLang dado que no tienen información privada:

Expression:
`($JOIN##```{"service_order":{"order_type":"```#($VALUE#answer|data|[find=>identifier=so_order_type]|process|0)#```","client":"```#($VALUE#answer|data|[find=>identifier=so_client]|process|0)#``` ","name":"```#($VALUE#answer|data|[find=>identifier=so_order_name]|process|0)#```","description":"```#($VALUE#answer|data|[find=>identifier=so_order_description]|process|0)#```","products":[```#($VALUE#answer|data|[find=>identifier=so_add_product]|process)#```],"performers":[```#($VALUE#answer|data|[find=>identifier=so_add_performers]|process)#```]}}```)|[json=>parse]`

Context:
`
{
  "answer": {
    "score": {
      "scores": []
    },
    "isAuto": true,
    "properties": [
      "621f97868d6c9d0008794255",
      "621fb5d18d6c9d0008797420"
    ],
    "propertyTypes": [
      "order_type",
      "client"
    ],
    "extendsAnswer": [],
    "rExtendsAnswer": [],
    "_id": "622b6d54c91d480007df889c",
    "data": [
      {
        "code": [],
        "display": [
          "### Datos generales de la orden"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df889d",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fced38d6c9d0008798ad3",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_general_label",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Tipo de Orden"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df889e",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794eb7",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_order_type_1646238663861",
        "diff": []
      },
      {
        "code": [
          "{\"allow\":\"propertyType\",\"value\":\"order_type\",\"filter\":\"*\"}"
        ],
        "display": [],
        "responses": [
          "{\"_id\":\"621f97868d6c9d0008794255\",\"subproperty\":[],\"isActive\":true,\"name\":{\"code\":\"computer_repair\",\"display\":\"Reparacion de Computadores\"},\"propertyType\":\"order_type\",\"company\":\"621f83de7b5a1a748394becc\",\"createdAt\":\"2022-03-02T16:12:54.303Z\",\"modifiedAt\":\"2022-03-02T16:12:54.310Z\"}"
        ],
        "process": [
          "621f97868d6c9d0008794255"
        ],
        "_id": "622b6d54c91d480007df889f",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794eb8",
        "contentType": "application/vnd.cotalker.survey+property",
        "identifier": "so_order_type",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Cliente"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88a0",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794eba",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_client_1646238663861",
        "diff": []
      },
      {
        "code": [
          "{\"allow\":\"propertyType\",\"value\":\"client\",\"filter\":\"*\"}"
        ],
        "display": [],
        "responses": [
          "{\"_id\":\"621fb5d18d6c9d0008797420\",\"subproperty\":[],\"isActive\":true,\"name\":{\"code\":\"client_2\",\"display\":\"Cliente 2\"},\"propertyType\":\"client\",\"company\":\"621f83de7b5a1a748394becc\",\"createdAt\":\"2022-03-02T18:22:09.765Z\",\"modifiedAt\":\"2022-03-10T21:26:46.497Z\",\"extra\":{},\"schemaInstance\":{\"address_1\":\"4166 N World Drive\",\"address_2\":\"Guest staying at Bay Lake Tower\",\"tax_id\":\"22222222-2\",\"phone\":\"4151010000\",\"email\":\"contact@baylake.com\",\"contact_name\":\"Test Username\",\"city\":\"Lake Buena Vista\",\"state\":\"Florida\",\"zip\":\"32830\"}}"
        ],
        "process": [
          "621fb5d18d6c9d0008797420"
        ],
        "_id": "622b6d54c91d480007df88a1",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794ebb",
        "contentType": "application/vnd.cotalker.survey+property",
        "identifier": "so_client",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Nombre de la Orden"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88a2",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794ebd",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_order_name_1646238663861",
        "diff": []
      },
      {
        "code": [],
        "display": [],
        "responses": [
          "test"
        ],
        "process": [
          "test"
        ],
        "_id": "622b6d54c91d480007df88a3",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794ebe",
        "contentType": "application/vnd.cotalker.survey+textinput",
        "identifier": "so_order_name",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Descripción de la orden"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88a4",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794ec0",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_order_description_1646238663861",
        "diff": []
      },
      {
        "code": [],
        "display": [],
        "responses": [
          "test"
        ],
        "process": [
          "test"
        ],
        "_id": "622b6d54c91d480007df88a5",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621f9bc88d6c9d0008794ec1",
        "contentType": "application/vnd.cotalker.survey+textinput",
        "identifier": "so_order_description",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Fecha de inicio de los trabajos"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88a6",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fced38d6c9d0008798ad5",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_arrival_date_1646251730291",
        "diff": []
      },
      {
        "code": [
          "date",
          "time",
          "timezone=America/Santiago"
        ],
        "display": [
          "Date",
          "Hour"
        ],
        "responses": [
          "2022/3/11",
          "11:11"
        ],
        "process": [
          "1647007860000"
        ],
        "_id": "622b6d54c91d480007df88a7",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fced38d6c9d0008798ad6",
        "contentType": "application/vnd.cotalker.survey+datetime",
        "identifier": "so_arrival_date",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Fecha de término de los trabajos"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88a8",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "622a2d5cc91d480007ddabec",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_end_date_1646931291209",
        "diff": []
      },
      {
        "code": [
          "date",
          "time"
        ],
        "display": [
          "Date",
          "Hour"
        ],
        "responses": [
          "2022/3/11",
          "22:22"
        ],
        "process": [
          "1647037320000"
        ],
        "_id": "622b6d54c91d480007df88a9",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "622a2d5cc91d480007ddabed",
        "contentType": "application/vnd.cotalker.survey+datetime",
        "identifier": "so_end_date",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "### Productos necesarios"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88aa",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fced38d6c9d0008798ad8",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_products_label",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Agregar producto"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88ab",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fd0e48d6c9d0008799445",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_add_product_1646252259380",
        "diff": []
      },
      {
        "code": [
          "{\"sid\":[\"621fcfc48d6c9d0008798e40\"]}"
        ],
        "display": [],
        "responses": [
          "{\"surveyCount\":2,\"messageCount\":38,\"uuids\":[\"622b6d4883de94bf13a915d4\",\"622b6d4c83de94bf13031d4e\"],\"code\":\"so_add_product\",\"survey\":\"621fcfc48d6c9d0008798e40\"}"
        ],
        "process": [
          "{\"uuids\":[\"622b6d4883de94bf13a915d4\",\"622b6d4c83de94bf13031d4e\"],\"survey\":\"621fcfc48d6c9d0008798e40\",\"code\":\"so_add_product\"}"
        ],
        "_id": "622b6d54c91d480007df88ac",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fd0e48d6c9d0008799446",
        "contentType": "application/vnd.cotalker.survey+survey",
        "identifier": "so_add_product",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "### Personal necesario"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88ad",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fced38d6c9d0008798ada",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_service_workers_label",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "Agregar trabajador"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88ae",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fd0e48d6c9d0008799448",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_add_performers_1646252259380",
        "diff": []
      },
      {
        "code": [
          "{\"sid\":[\"621fd0918d6c9d0008799267\"]}"
        ],
        "display": [],
        "responses": [
          "{\"surveyCount\":2,\"messageCount\":28,\"uuids\":[\"622b6d4183de94bf13c61274\",\"622b6d4483de94bf136b29e9\"],\"code\":\"add_service_performers\",\"survey\":\"621fd0918d6c9d0008799267\"}"
        ],
        "process": [
          "{\"uuids\":[\"622b6d4183de94bf13c61274\",\"622b6d4483de94bf136b29e9\"],\"survey\":\"621fd0918d6c9d0008799267\",\"code\":\"add_service_performers\"}"
        ],
        "_id": "622b6d54c91d480007df88af",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fd0e48d6c9d0008799449",
        "contentType": "application/vnd.cotalker.survey+survey",
        "identifier": "so_add_performers",
        "diff": []
      },
      {
        "code": [],
        "display": [
          "### Información adicional"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88b0",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fd0e48d6c9d000879944b",
        "contentType": "application/vnd.cotalker.survey+text",
        "identifier": "so_additional_fields",
        "diff": []
      },
      {
        "code": [
          "*"
        ],
        "display": [
          "Adjuntos"
        ],
        "responses": [],
        "process": [],
        "_id": "622b6d54c91d480007df88b1",
        "user": "621f83de7b5a1a27c394bf13",
        "question": "621fced38d6c9d0008798adc",
        "contentType": "application/vnd.cotalker.survey+file",
        "identifier": "so_files",
        "diff": []
      }
    ],
    "uuid": "622b6d3483de94bf13a0af83",
    "survey": "621f9bc88d6c9d0008794eb6",
    "formId": "622b6d53c91d480007df87fa",
    "company": "621f83de7b5a1a748394becc",
    "user": "621f83de7b5a1a27c394bf13",
    "createdAt": "2022-03-11T15:40:04.627Z",
    "startDate": "2022-03-11T15:40:04.627Z",
    "modifiedAt": "2022-03-11T15:40:04.650Z",
    "target": null,
    "channel": "622b6d53c91d480007df87f9",
    "meta": {
      "action": "create-task",
      "payload": {
        "group": "621f851a8d6c9d0008792582"
      }
    },
    "__v": 0
  },
  "meta": {
    "taskGroup": "621f851b8d6c9d000879258a"
  },
  "__value_mapping": {
    "answer": "answers|0",
    "meta|parentTask": "ref|taskParent",
    "meta|taskGroup": "ref|taskGroups|0"
  },
  "__bot_context": "workflowStart"
}
`

### Expected result

Que se resuelva correctamente el COTLang dentro del bot "Crear tarea" (2.0.1)

**Comment by acedward** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/3951895/158671116-9b8e70ba-ed4d-4692-a556-241e116a44b4.png">

**Comment by acedward** [comment]
## Request
curl -X "POST" "https://dev.cotalker.com/api/v1/bots/run/exec" \
     -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmM5ZjY2NzY1NzE5ODUwMmVkNjAxNjciLCJyb2xlIjoidXNlciIsImNvbXBhbnkiOiI1YmM5ZjJmYmRhMTA5NDUyNTY5OTg5NGEiLCJkYXRlIjoxNjQ3MDA5MjM3MDU0LCJpcnQiOnRydWUsImlhdCI6MTY0NzAwOTIzNywiZXhwIjoxNjQ5NjAxMjM3fQ.coqI3ehIljXcC7_btGM3MMP_DBjE4jrvyVtgCLK66CY' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "tags": [],
  "owner": "WEBHOOK",
  "tagValue": "this-is-test-for-pdf-extraction-example",
  "data": {},
  "pb": {
    "start": "send_message",
    "data": {
      "meta": {
        "taskGroup": "621f851b8d6c9d000879258a"
      },
      "answer": {
        "modifiedAt": "2022-03-11T15:40:04.650Z",
        "__v": 0,
        "company": "621f83de7b5a1a748394becc",
        "target": null,
        "score": {
          "scores": []
        },
        "isAuto": true,
        "_id": "622b6d54c91d480007df889c",
        "uuid": "622b6d3483de94bf13a0af83",
        "createdAt": "2022-03-11T15:40:04.627Z",
        "channel": "622b6d53c91d480007df87f9",
        "meta": {
          "payload": {
            "group": "621f851a8d6c9d0008792582"
          },
          "action": "create-task"
        },
        "user": "621f83de7b5a1a27c394bf13",
        "properties": [
          "621f97868d6c9d0008794255",
          "621fb5d18d6c9d0008797420"
        ],
        "survey": "621f9bc88d6c9d0008794eb6",
        "extendsAnswer": [],
        "propertyTypes": [
          "order_type",
          "client"
        ],
        "formId": "622b6d53c91d480007df87fa",
        "startDate": "2022-03-11T15:40:04.627Z",
        "rExtendsAnswer": [],
        "data": [
          {
            "_id": "622b6d54c91d480007df889d",
            "diff": [],
            "display": [
              "### Datos generales de la orden"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fced38d6c9d0008798ad3",
            "responses": [],
            "identifier": "so_general_label",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df889e",
            "diff": [],
            "display": [
              "Tipo de Orden"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621f9bc88d6c9d0008794eb7",
            "responses": [],
            "identifier": "so_order_type_1646238663861",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df889f",
            "diff": [],
            "display": [],
            "code": [
              "{\\"allow\\":\\"propertyType\\",\\"value\\":\\"order_type\\",\\"filter\\":\\"*\\"}"
            ],
            "contentType": "application/vnd.cotalker.survey+property",
            "question": "621f9bc88d6c9d0008794eb8",
            "responses": [
              "{\\"_id\\":\\"621f97868d6c9d0008794255\\",\\"subproperty\\":[],\\"isActive\\":true,\\"name\\":{\\"code\\":\\"computer_repair\\",\\"display\\":\\"Reparacion de Computadores\\"},\\"propertyType\\":\\"order_type\\",\\"company\\":\\"621f83de7b5a1a748394becc\\",\\"createdAt\\":\\"2022-03-02T16:12:54.303Z\\",\\"modifiedAt\\":\\"2022-03-02T16:12:54.310Z\\"}"
            ],
            "identifier": "so_order_type",
            "process": [
              "621f97868d6c9d0008794255"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a0",
            "diff": [],
            "display": [
              "Cliente"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621f9bc88d6c9d0008794eba",
            "responses": [],
            "identifier": "so_client_1646238663861",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a1",
            "diff": [],
            "display": [],
            "code": [
              "{\\"allow\\":\\"propertyType\\",\\"value\\":\\"client\\",\\"filter\\":\\"*\\"}"
            ],
            "contentType": "application/vnd.cotalker.survey+property",
            "question": "621f9bc88d6c9d0008794ebb",
            "responses": [
              "{\\"_id\\":\\"621fb5d18d6c9d0008797420\\",\\"subproperty\\":[],\\"isActive\\":true,\\"name\\":{\\"code\\":\\"client_2\\",\\"display\\":\\"Cliente 2\\"},\\"propertyType\\":\\"client\\",\\"company\\":\\"621f83de7b5a1a748394becc\\",\\"createdAt\\":\\"2022-03-02T18:22:09.765Z\\",\\"modifiedAt\\":\\"2022-03-10T21:26:46.497Z\\",\\"extra\\":{},\\"schemaInstance\\":{\\"address_1\\":\\"4166 N World Drive\\",\\"address_2\\":\\"Guest staying at Bay Lake Tower\\",\\"tax_id\\":\\"22222222-2\\",\\"phone\\":\\"4151010000\\",\\"email\\":\\"contact@baylake.com\\",\\"contact_name\\":\\"Test Username\\",\\"city\\":\\"Lake Buena Vista\\",\\"state\\":\\"Florida\\",\\"zip\\":\\"32830\\"}}"
            ],
            "identifier": "so_client",
            "process": [
              "621fb5d18d6c9d0008797420"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a2",
            "diff": [],
            "display": [
              "Nombre de la Orden"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621f9bc88d6c9d0008794ebd",
            "responses": [],
            "identifier": "so_order_name_1646238663861",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a3",
            "diff": [],
            "display": [],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+textinput",
            "question": "621f9bc88d6c9d0008794ebe",
            "responses": [
              "test"
            ],
            "identifier": "so_order_name",
            "process": [
              "test"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a4",
            "diff": [],
            "display": [
              "Descripción de la orden"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621f9bc88d6c9d0008794ec0",
            "responses": [],
            "identifier": "so_order_description_1646238663861",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a5",
            "diff": [],
            "display": [],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+textinput",
            "question": "621f9bc88d6c9d0008794ec1",
            "responses": [
              "test"
            ],
            "identifier": "so_order_description",
            "process": [
              "test"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a6",
            "diff": [],
            "display": [
              "Fecha de inicio de los trabajos"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fced38d6c9d0008798ad5",
            "responses": [],
            "identifier": "so_arrival_date_1646251730291",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a7",
            "diff": [],
            "display": [
              "Date",
              "Hour"
            ],
            "code": [
              "date",
              "time",
              "timezone=America/Santiago"
            ],
            "contentType": "application/vnd.cotalker.survey+datetime",
            "question": "621fced38d6c9d0008798ad6",
            "responses": [
              "2022/3/11",
              "11:11"
            ],
            "identifier": "so_arrival_date",
            "process": [
              "1647007860000"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a8",
            "diff": [],
            "display": [
              "Fecha de término de los trabajos"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "622a2d5cc91d480007ddabec",
            "responses": [],
            "identifier": "so_end_date_1646931291209",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88a9",
            "diff": [],
            "display": [
              "Date",
              "Hour"
            ],
            "code": [
              "date",
              "time"
            ],
            "contentType": "application/vnd.cotalker.survey+datetime",
            "question": "622a2d5cc91d480007ddabed",
            "responses": [
              "2022/3/11",
              "22:22"
            ],
            "identifier": "so_end_date",
            "process": [
              "1647037320000"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88aa",
            "diff": [],
            "display": [
              "### Productos necesarios"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fced38d6c9d0008798ad8",
            "responses": [],
            "identifier": "so_products_label",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88ab",
            "diff": [],
            "display": [
              "Agregar producto"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fd0e48d6c9d0008799445",
            "responses": [],
            "identifier": "so_add_product_1646252259380",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88ac",
            "diff": [],
            "display": [],
            "code": [
              "{\\"sid\\":[\\"621fcfc48d6c9d0008798e40\\"]}"
            ],
            "contentType": "application/vnd.cotalker.survey+survey",
            "question": "621fd0e48d6c9d0008799446",
            "responses": [
              "{\\"surveyCount\\":2,\\"messageCount\\":38,\\"uuids\\":[\\"622b6d4883de94bf13a915d4\\",\\"622b6d4c83de94bf13031d4e\\"],\\"code\\":\\"so_add_product\\",\\"survey\\":\\"621fcfc48d6c9d0008798e40\\"}"
            ],
            "identifier": "so_add_product",
            "process": [
              "{\\"uuids\\":[\\"622b6d4883de94bf13a915d4\\",\\"622b6d4c83de94bf13031d4e\\"],\\"survey\\":\\"621fcfc48d6c9d0008798e40\\",\\"code\\":\\"so_add_product\\"}"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88ad",
            "diff": [],
            "display": [
              "### Personal necesario"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fced38d6c9d0008798ada",
            "responses": [],
            "identifier": "so_service_workers_label",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88ae",
            "diff": [],
            "display": [
              "Agregar trabajador"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fd0e48d6c9d0008799448",
            "responses": [],
            "identifier": "so_add_performers_1646252259380",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88af",
            "diff": [],
            "display": [],
            "code": [
              "{\\"sid\\":[\\"621fd0918d6c9d0008799267\\"]}"
            ],
            "contentType": "application/vnd.cotalker.survey+survey",
            "question": "621fd0e48d6c9d0008799449",
            "responses": [
              "{\\"surveyCount\\":2,\\"messageCount\\":28,\\"uuids\\":[\\"622b6d4183de94bf13c61274\\",\\"622b6d4483de94bf136b29e9\\"],\\"code\\":\\"add_service_performers\\",\\"survey\\":\\"621fd0918d6c9d0008799267\\"}"
            ],
            "identifier": "so_add_performers",
            "process": [
              "{\\"uuids\\":[\\"622b6d4183de94bf13c61274\\",\\"622b6d4483de94bf136b29e9\\"],\\"survey\\":\\"621fd0918d6c9d0008799267\\",\\"code\\":\\"add_service_performers\\"}"
            ],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88b0",
            "diff": [],
            "display": [
              "### Información adicional"
            ],
            "code": [],
            "contentType": "application/vnd.cotalker.survey+text",
            "question": "621fd0e48d6c9d000879944b",
            "responses": [],
            "identifier": "so_additional_fields",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          },
          {
            "_id": "622b6d54c91d480007df88b1",
            "diff": [],
            "display": [
              "Adjuntos"
            ],
            "code": [
              "*"
            ],
            "contentType": "application/vnd.cotalker.survey+file",
            "question": "621fced38d6c9d0008798adc",
            "responses": [],
            "identifier": "so_files",
            "process": [],
            "user": "621f83de7b5a1a27c394bf13"
          }
        ]
      },
      "__value_mapping": {
        "answer": "answers|0",
        "meta|parentTask": "ref|taskParent",
        "meta|taskGroup": "ref|taskGroups|0"
      },
      "__bot_context": "workflowStart"
    },
    "maxIterations": 1,
    "stages": [
      {
        "data": {
          "channelIds": [
            "621f69131dee9700072e951b"
          ],
          "content": "($JOIN##```{\\"service_order\\":{\\"order_type\\":\\"```#($VALUE#answer|data|[find=>identifier=so_order_type]|process|0)#```\\",\\"client\\":\\"```#($VALUE#answer|data|[find=>identifier=so_client]|process|0)#``` \\",\\"name\\":\\"```#($VALUE#answer|data|[find=>identifier=so_order_name]|process|0)#```\\",\\"description\\":\\"```#($VALUE#answer|data|[find=>identifier=so_order_description]|process|0)#```\\",\\"products\\":[```#($VALUE#answer|data|[find=>identifier=so_add_product]|process)#```],\\"performers\\":[```#($VALUE#answer|data|[find=>identifier=so_add_performers]|process)#```]}}```)",
          "sentBy": "5bc9f667657198502ed60167",
          "contentType": "text/plain"
        },
        "key": "send_message",
        "next": {},
        "name": "PBMessage",
        "version": "2.0.0"
      }
    ],
    "version": 3
  }
}'

**Comment by acedward** [comment]
CASO CERRADO
