### ISSUE TITLE
Bug report: estilo del html es distinto al pdf que se genera en el pbpdf

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#754]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

En una rutina tengo una etapa de un pbpdf de la siguiente manera:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/73865460/158204054-2b2916e3-1737-4304-86c6-c9eb16893a8e.png">

Al abrir en chrome el url indicado (https://92wp3ez0dd.execute-api.us-east-1.amazonaws.com/dev/getPurchaseOrder/622f420fd7da8d6a616c9529), se abre el archivo con el estilo que se quiere, por ejemplo el estilo de letra es el siguiente:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/73865460/158204560-f00361a0-5ccd-4d8c-8a5d-522f362725af.png">

Sin embargo, el pdf que entrega como resultado esta etapa se genera con otro estilo:
https://cotalker-development.s3.amazonaws.com/uploads/products/document/622f4220d7da8da9a66c952f.pdf
por ejemplo el estilo de letra es el siguiente:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/73865460/158204609-38be11c5-0a91-4265-98ed-ef84bab7324b.png">

### Steps to reproduce

1. Crear etapa "Crear PDF" con url = $JOIN#/#https://92wp3ez0dd.execute-api.us-east-1.amazonaws.com/dev/getPurchaseOrder#($VALUE#_id)
2. Ejecutar rutina y observar que el estilo que tiene el pdf generado es distinto al estilo que se especifica en el html.

### Expected result

Que el pdf generado se genere con el estilo indicado en el css indicado dentro del html.

**Comment by guillevalin** [comment]
Actualmente estamos teniendo problemas con el nuevo PBPdf con los estilos:

Así se ve en el HTML:
![image](https://user-images.githubusercontent.com/34345309/158630989-9a3e25a9-dfc1-484e-a0c0-ad41797c61ea.png)

Así se ve en el PDF:
![image](https://user-images.githubusercontent.com/34345309/158630928-8d090a4e-e27f-4846-842a-df71aca37234.png)

**Comment by MiikeVi** [comment]
A considerar para una próxima revisión:

Problema específico: Al parecer el bot no resuelve los links (estilos css, en específico cdn de bootstrap) que contiene determinado html generado  por una función lambda.
workaround: Se copian los estilos necesarios directamente en el html en vez de usar los cdn.

- Se probó de forma aislada la librería que usa el bot para convertir html a pdf, con las mismas configuraciones/opciones, pdf se genera correctamente.
- Se probó el bot con html que contiene cdn de bootstrap, como input. Dos flujos: Guardar pdf localmente / subir a aws. Resultado: pdf se genera con los estilos correspondientes.
