### ISSUE TITLE
Feature Request: PBPDF No soporta enviar Headers ni token de Cotalker

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#755]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

PBPdf no soporta enviar el parámetro "defaultAuth" por lo que no se puede crear extensiones que utilicen el token del usuario que realiza la llamada para crear llamadas a la API contextualizadas.

Además sería bueno poder soportar el envío de headers personalizados para permitir personalizar más los PDF que se puedan generar a partir de una página HTML.

Gracias! :D

### Steps to reproduce

Usar PBPDF con algúna página que utilice el header "Authorization: Bearer [cotalker_token]".

### Expected result

Poder usar el token como header referenciado al usuario que realiza la request.

**Comment by acedward** [comment]
Fixed PBPDF V3
