### ISSUE TITLE
Bug report: PBCalendar está generando problemas con el formato de la fecha de entrada

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#757]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.7.10 (223)

### Details

Contexto

Estoy usando el PBCalender 2.0.0 para agendar citas en el momento que seleccione una fecha y hora, como el json que dejo más abajo

`            {
                            "_id" : ObjectId("62309a910e712600079a7a16"), 
                            "key" : "calendario_terapia", 
                            "name" : "PBCalendar", 
                            "version" : "2.0.0", 
                            "data" : {
                                "title" : "$JOIN##(Reunión siguiente  sesión programa tabaquismo)#($VALUE#name)", 
                                "initialDate" : "$JOIN##($VALUE#sentAnswer|data|[find=>identifier=indique_fecha_proxima_sesion]|process|0|[date=>format=DD-MM-YYYY hh:mm:ss@America/Santiago])", 
                                "durationMinutes" : NumberInt(60), 
                                "owner" : "5e0a1a1345e9602068206fdb", 
                                "description" : "$JOIN##(La próxima reunión se realizará el día: )#($VALUE#sentAnswer|data|[find=>identifier=indique_fecha_proxima_sesion]|process|0|[date=>format=DD-MM-YYYY HH:mm:ss@America/Santiago])#</br>#(. Favor tenerlo entre sus prioridades)", 
                                "invitedByEmail" : [
                                    "tester@tester.com"
                                ]
                            }, 
                            "next" : {
                                "DEFAULT" : ""
                            }, 
                            "customNetworkRequest" : [

                            ]
                        }`

Sin embargo en el momento que lo ejecuto me arroja el siguiente error:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/61419471/158396624-263d4639-d273-4ac5-a4f1-9afdba68c0b8.png">

Al revisar en la documentación  https://doc.cotalker.com/docs/documentation/automation/bots/pbgooglecalendar#json-sample

Aparece este ejemplo:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/61419471/158396891-741618a8-3bd3-4e52-845d-95c75bc4286c.png">

Donde el campo initialDate: está en formato de ISODate y se ejecuta sin problemas.

---------
En realizar varias pruebas logré que el bot funcionara usando esta expresión
`"initialDate" : "$VALUE#sentAnswer|data|[find=>identifier=indique_fecha_proxima_sesion]|process|0|[date=>format=YYYY-MM-DDTHH:mm:ss@America/Santiago]"`
Sólo que hay problemas con las horas, que veré como hacerlo xD

Si se puede apreciar en el formato de la fecha: "DD-MM-YYYY HH:mm:ss@America/Santiago" y "YYYY-MM-DDTHH:mm:ss@America/Santiago", se ve que es lo mismo, cambiando el orden del campo de la fecha, pero el segundo es formato IsoDate (como sale en el ejemplo de la documentación) y podría generar problemas para usuarios que no tengan gran conocimiento en programación.

### Steps to reproduce

1.- replicar el json en otra cia
2.- cambiar los valores del initialDate a formatos normales y formato iso
3.- probar

### Expected result

Posibles ideas:

1.- Que el usuario con sólo colocar: $VALUE#sentAnswer|data|[find=>identifier=indique_fecha_proxima_sesion]|process|0 funcione el bot, dejando como conversión interna a una fecha ISO.

2.- Que en el error muestre un ejemplo de formato correcto para el campo

3.- Que en la documentación quede el ejemplo json del calendar con su cotlang (o configuración), asociada.

Gracias =>

### Additional data

No Aplica

**Comment by acedward** [comment]
duplicated of #781
