### ISSUE TITLE
Infinit reload de llamada GET en WebClient

### ISSUE THREAD

**Issue by AlejandroLoraG** [Cotalker/documentation#760]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging, Development

### App version

15.0.0

### Hola gente hermosa! Espero sigan con un día de lujo! 😘

Al hacer una acción sobre un canal relacionada a una task, esta acción queda cargando de manera infinita hasta que haga reload (fig 1). ¡Esto afecta al webclient no solo al usuario! AYUDA.

<img width="1437" alt="fig 1" src="https://user-images.githubusercontent.com/51095635/158432422-76e830c8-af51-4624-aca9-c6aa70a160df.png">

Muchas gracias!! ☺️

### Steps to reproduce

1. Al parecer está difícil reproducirlo. No se sabe aún como reprducirlo
2. Entrar a compañía
3. web.staging.cotalker.com
4. User: builder.admin@esmaxstaging.cotalker.com
5. Pass: @acedward  la tiene

### Expected result

No cargar infinitamente.

**Comment by acedward** [comment]
Corregido con workaround.

Al fallar escribir la tarea en el backend (e.g., schemaInstance inválido) envía el mensaje vía socket con modifedAt que no fue escrito en la BD, causando un loop infinito de requests.
Al corregir el schemaInstance el error no es visualizado.
