### ISSUE TITLE
What's New: Company colors

### ISSUE THREAD

**Issue by MiikeVi** [Cotalker/documentation#765]
# Summary
Thanks to this new feature we will be able to modify and customize the colors and configurations of a company.

# Who and how does it help
Internally we can change the name, short name, app url, api url, activate/deactivate google sign in, azure ad credentials config, upload custom images and icons, custom css and custom translations.

# Changes for Admins & Developers
Will be able to configure the visual aspect of the company (colors, images, text) through the api ( PATCH /api/v1/companies/:id), in addition to activating/deactivating other functionalities such as login with google or azure. 
# Expected release date
31/05

# Modification / Creation of new sections.
-

# (Supplementary information)
New property added to the COTCompany model:

```
whitelabel?: {
    isActive?: boolean;
    names?: {
      name?: string;
      shortName?: string;
    };
    urls?: {
      app?: string;
      api?: string;
    };
    style?: {
      customCss?: string;
    };
    auth?: {
      azureAD?: {
        isActive?: boolean;
        clientId?: string;
        authority?: string;
        redirectUri?: string;
      };
      googleSignIn?: {
        isActive?: boolean;
      };
    };
    images?: {
      login?: string;
      email?: string;
      logotype?: string;
      isotype?: string;
      icon512?: string;
      icon384?: string;
      icon192?: string;
      icon152?: string;
      icon144?: string;
      icon128?: string;
      icon96?: string;
      icon72?: string;
    };
    translations: {
      en: { [key: string]: string };
      es: { [key: string]: string };
    }
  };
```

**Comment by acedward** [comment]
@Mauriceac this should not be called Whitelabel o even name the word (Whitelabel do not include the company's logo) e.g., I make cloth and the reseller stamps its Brand on it.

**Comment by acedward** [comment]
Perhaps something with the works
Custom, Personalization, Look & Feel, Colors, Brand, Customization

**Comment by Mauriceac** [comment]
@acedward, I was even thinking of "skins" or "color themes".
It would be cool to code in the documentation for custom "Cotalker skins" or "color themes", and include a much needed "dark mode".

**Comment by acedward** [comment]
I feel "skins" is too retro - it reminds me of the winamp age and msn messenger.
On the other side, "color themes" is too narrow, we allow deep personalization - from colors, logos, images, custom-css, custom-translations,  app name and app subdomain (so that the final app looks like a app made for the company)
