### ISSUE TITLE
Bug report: No funcionan los dashboards en modo embedded (Metabase)

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#774]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging, Development

### Details

Al agregar un link de Metabase público se queda cargando al infinito:
![image](https://user-images.githubusercontent.com/34345309/158837214-7e2c580c-8ac9-4ac2-b3c4-eeb4bd9576d1.png)

Al usarlo como link normal que se abra en una pestaña nueva, funciona sin problemas.

### Steps to reproduce

Crear un "Group Link" con un enlace a un dashboard público de Metabase.
Clickear el "Group Link", quedará "Cargando" infinitamente.

### Expected result

Poder visualizar dashboards de Metabase en modo embedded.

**Comment by acedward** [comment]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/3951895/160424710-0dbee2d6-3f5e-4b06-b938-a5244e573a63.png">

Fixed? Cannot reproduce.

**Comment by guillevalin** [comment]
Al parecer se solucionó con el último mega release, porque pasaba en prod y no en dev :) thanks!
