### ISSUE TITLE
Bug report: no se eliminan todos los datos al hacer un clean de la company

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#775]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

Hola! Espero que estén super :) 
Los vengo a molestar jeje

Al hacer un clean de la compañía con el comando:
curl -XDELETE http://localhost:12345/api/remover/${companyId}
Quedan algunos datos que no se borran:

1. Las burbujas de mensajes no leídos si es que antes de limpiar la company existía una notificación que no se leyó, como se muestra en la imagen (el número 17, que eran los mensajes no leídos de antes de limpiar la company):
<img width="626" alt="image" src="https://user-images.githubusercontent.com/73865460/158871892-d316216d-6461-4d83-8667-0f8ab716eaf7.png">

2. Los Api Token: se elimina solo lo de adentro, pero sigue apareciendo el api token. En las imágenes se observa que luego de hacer el clean aun aparecen, sin embargo, dentro no tienen nada.
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/73865460/158872299-f4bfcbc5-ecac-4cb2-8e86-51cbfc27ced9.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/73865460/158872367-db7741f6-9e5a-4921-99d8-ec34090c8e4b.png">

### Steps to reproduce

1. Tener una company con notificaciones no leídos y con api token.
2. Hacer un clean de la compañía con el comando: curl -XDELETE http://localhost:12345/api/remover/${companyId}
3. Luego de hacer el clean, se observa que la burbuja de notificaciones no leídas y el nombre de los api token siguen estando ahí (como se muestra en las imágenes anteriores).

### Expected result

Que se borre todo con el comando curl -XDELETE http://localhost:12345/api/remover/${companyId}.

**Comment by CVargasGando** [comment]
Tampoco se eliminan los automation logs antiguos (de antes de hacer el clean)

**Comment by acedward** [comment]
@martinmiranda14

**Comment by martinmiranda14** [comment]
Actualmente no esta implementado el eliminar apitokens de una compañia (base de datos: cotalker-dev-auth)

**Comment by martinmiranda14** [comment]
Se reporta que aún no se están eliminando audit logs
