### ISSUE TITLE
Bug report: no aparece el campo adicional 5 en el fronted

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#776]
### Affected system

Cotalker Web Application

### Affected environment

Development

### Details

Hola! Vengo nuevamente a molestar :) 

Tengo 5 campos adicionales, pero en el fronted solo se ven 4 :(
Los campos adicionales que tengo son:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/73865460/158873867-db6fb9c3-d2b3-4545-9746-e2d4b6cb2d3f.png">

Luego cuando creo una tarea, en el PBCreateTask agrego el status5. En Resultados del automation log se puede ver que sí se agregó:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/73865460/158874255-46155b48-28e7-4d30-a4b4-172416151288.png">
También se verificó haciendo una llamada de red para obtener la task y sí aparece el status5.

Sin embargo, en el fronted no aparece:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/73865460/158874379-30d4f434-fc96-4c1b-8752-97c8c8a03278.png">

### Steps to reproduce

1. Tener 5 campos adicionales.
2. Crear una tarea y llenar el status5.
3. En el fronted no se observa este status (pero sí está creado en la task, es solo problema de visualización)

### Expected result

Que se visualicen los 5 campos adicionales de la Task.

**Comment by acedward** [comment]
"status5" no estaba en la lista de activos, pero no se ve reflejado en el admin

**Comment by CVargasGando** [comment]
No aparecía porque en la base de datos no estaba: "isActive":["status5"].
Sin embargo, podría esto estar disponible desde el fronted, poder activar o desactivar los campos adicionales, sería bacan :)

Gracias!!

**Comment by eduborgono** [comment]
En producción
