### ISSUE TITLE
Bug report: COTLang Parseo de Literales

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#784]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Tengo esta expresión COTLang:
`($JOIN##```{"test": "hola", ```#```"test2": "```#($VALUE#testString|[toString=>JSON])#```"}```)|[json=>parse]`

Con este contexto:
`{ "testString": "string \"con\" comillas" }`

La cual no se resuelve correctamente. Si quito los caracteres conflictivos, usando este contexto:
`{ "testString": "string sin comillas" }`

Funciona correctamente.

### Steps to reproduce

Utilizar en COTLang playground los valores mencionados en la parte superior.

### Expected result

Poder soportar strings con cualquier caracter en la expresión mencionada.

**Comment by acedward** [comment]
el contexto debe ser
```
{"testString": "string \\\"con\\\" comillas" }
```

**Comment by acedward** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/3951895/162026600-6e5a6e37-02b3-4d1c-8310-9ceeedcda328.png">
