### ISSUE TITLE
Bug report (staging): En el survey builder cuando se quiere agregar la componente fecha ésta desaparece

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#797]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.8.1 (227)

### Details

En survey builder, si queremos ingresar un campo de componente fecha: éste desaparece.

Se adjunta el link del video: https://drive.google.com/file/d/1ZZUm5PqhEVESUzVxoA7cmWw9g_CVWD6G/view?usp=sharing

Pd: En producción no hay problemas

### Steps to reproduce

1.- ir ambiente staging
2.- ir a survey
3.- crear un nuevo survey
4.- Agregar la componente fecha
5.- Saldrá el error

### Expected result

Se debería mostrarse

### Additional data

No aplica

**Comment by eduborgono** [comment]
Este issue está solucionado en development.
