### ISSUE TITLE
Bug report: Pop-up de "Enriched Messages" no desaparece a veces

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#799]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.8.1 (227)

### Details

Cuando sale un cuadro pop-up de sitio al hacer hover con el cursor en un link de un mensaje, se queda permanentemente el cuadro sin desaparecer en algunos casos. No tengo claro cómo reproducirlo.

### Steps to reproduce

?

### Expected result

Cuadro debería desaparecer al quitar el cursor del link.

**Comment by acedward** [comment]
Gracias Sergio. Me pasó lo mismo, al parecer pasa al cambiar de contexto mientra el popup está abierto.
