### ISSUE TITLE
Add QuestionExec documentation

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#8]
Please add Question-Exec documentation.
The current documentation is in the internal wiki.

@Mauriceac @guillevalin @gmoplaza

**Comment by guillevalin** [comment]
@Mauriceac la documentación técnica está en esta Wiki:
https://github.com/Cotalker/cotalker-development/wiki/QuestionExec-Specs

Pero finalmente, a nivel de implementador, hay que explicar que existen diferentes etapas en el ciclo de vida del formulario:
![image](https://user-images.githubusercontent.com/34345309/113594217-634e2280-9605-11eb-88ed-e545906276c5.png)

Las que están implementadas actualmente son:
- Preload: Se ejecuta cuando se crea una nueva instancia de formulario.
- onDisplay: Se ejecuta cuando un formulario se pone en modo edición? @rafaelwalter confirmar please.
- Validate: Se ejecuta antes de las validaciones internas, permite agregar una capa adicional de validaciones (reglas de negocio, por ejemplo.)
- Postsave: Se ejecuta luego de las validaciones custom (validate) e internas (preSave).

Lo que se puede realizar a nivel de alteración de formularios es lo siguiente:
- SET_READONLY: Configura la casilla en modalidad solo lectura.
- SET_RESPONSES: Reemplaza el valor guardado en la casilla.
- SET_REQUIRED: Configura la casilla como obligatoria (no debe tener un valor en blanco).

Para ello, se puede escribir código JavaScript y se puede referenciar distintos contextos que nos ayudan a tener más datos para crear reglas de negocio, los cuales son:
- property#channel: Propiedades asociadas al canal.
- property#user: Propiedades asociadas al usuario.
- channel#self: Canal donde está el formulario.
- user#me: Usuario que está levantando el formularo.
- responses#self: Valor que se va a guardar como respuesta de la casilla del formulario.
- messages#self: Mensaje asociado a la casilla del formulario.

Dejo dos ejemplos, en el primer caso es un Preload que mostrará en la casilla el usuario y el canal, y dejará la casilla en solo lectura:

```
function run(){
  const commands = [];
  const user = context['user#me'];
  const channel = context['channel#self'];
  const channelName = channel.nameDisplay;
  const userName = user.name.names + ' ' + user.name.lastName;
  commands.push(
  { cmd: 'SET_RESPONSES', 
    value: channelName + ' / ' + userName }
  );
  commands.push(
  { cmd: 'SET_READONLY',
    value: 'true' }
  );
  return commands;
}
```

![image](https://user-images.githubusercontent.com/34345309/113594182-56313380-9605-11eb-9f1e-126c5d041ac2.png)
![image](https://user-images.githubusercontent.com/34345309/113596269-10299f00-9608-11eb-9f0b-f222915a0110.png)


El segundo es un validate, el cual validará que el valor ingresado en un campo numérico esté entre 0 y 100, y no esté en blanco:

```
function run(){
const val = context['responses#self'][0];
if (!val) return [{ cmd: 'RESULT', result: false, value: 'Debe ingresar al menos un valor.' }];
if (val < 0) return [{ cmd: 'RESULT', result: false, value: 'Valor es menor al mínimo permitido (0).' }];
if (val > 100) return [{ cmd: 'RESULT', result: false, value: 'Valor es mayor al máximo permitido (100).' }];
else return [{ cmd: 'RESULT', result: true }];
}
```

![image](https://user-images.githubusercontent.com/34345309/113596180-ee301c80-9607-11eb-8857-5802d01ab269.png)
![image](https://user-images.githubusercontent.com/34345309/113596222-fc7e3880-9607-11eb-8e4c-2d0c0b04e9a3.png)

**Comment by guillevalin** [comment]
Espero se entienda @Mauriceac @acedward

**Comment by Mauriceac** [comment]
[Debería estar listo.](https://github.com/Cotalker/documentation/pull/41)

*Gracias @guillevalin, las explicaciones me salvaron.*

Me quedaron algunas dudas:
- Esto es operativo? Es que intenté copiar y pegar el código (en prod y dev) sin resultados y a veces con mensajes de error. Lo más probable es que hice algo mal.

- Usé alguna terminología que no estoy 100% seguro que sea adecuada. 
Por ejemplo: 
  - "Context Variables" para hablar de los "parameters".
  - "Coding Guide" como el título, quizás hay algo más preciso.
  - Como no logré echarlo andar, no pude ver como el resultado final se ve, supongo que "casillas" son "fields".

**Comment by acedward** [comment]
@Mauriceac Oh, I didn't see this - once you start the PR - it's easier to to continue the conversation over there - because the feedback will be given there

**Comment by acedward** [comment]
Yes, this is hard to get working - I had to use the API to setup some values-  let's wait until @guillevalin gets it fixed.+

**Comment by guillevalin** [comment]
@acedward @Mauriceac ya está funcionando :), aquí está la prueba de preload:
![image](https://user-images.githubusercontent.com/34345309/115290622-c2da2100-a121-11eb-9667-66571c17f4db.png)

y aquí la de validate:
![image](https://user-images.githubusercontent.com/34345309/115290955-295f3f00-a122-11eb-9f30-f594df397601.png)

Ambas pruebas están en el formulario "questionExec Demo" en el grupo "Tareas" con la cuenta builder@cotalker.com del entorno de desarrollo.
