### ISSUE TITLE
Bug report: Diferencias en comportamiento Offline vs Online. 

### ISSUE THREAD

**Issue by tachiforero** [Cotalker/documentation#800]
### Affected system

Cotalker iOS Application

### Affected environment

Production

### Details

![image](https://user-images.githubusercontent.com/78934535/160183346-0886b345-f358-4620-b53c-23f797b8bb13.png)
![image](https://user-images.githubusercontent.com/78934535/160183377-4739f58d-c83a-4d37-84cd-870f8cffd571.png)
![image](https://user-images.githubusercontent.com/78934535/160183393-ba24a29a-773e-4a95-a521-9ad9122765e1.png)

### Steps to reproduce

usuario: [gasco@tratton.cl](mailto:gasco@tratton.cl)

Activando Offline desde aplicación móvil 

### Expected result

Se requiere poder enviar un formulario de "cierre de orden" para los flujos de "**demo mantenimiento energético** y “**demo patrullaje de redes de gas”**

Estos formularios se encuentran específicamente en la etapa: 
1. Asignación patrullaje (del flujo demo mantenimiento) con el fomrulario: "formulario cierre de tramo"

y en la etapa 

1. Pendientes (del flujo demo patrullaje de redes...) con el formulario "cierre de orden"

**Comment by agallardol** [comment]
@tachiforero , podrías añadir la versión de la app en que estás?

**Comment by tachiforero** [comment]
Hola Alfred! chuta pensé que lo había puesto! Es la versión: 17.7.4(125)

**Comment by tachiforero** [comment]
**Hola Alfred!

Si, ahora estoy en la última versión:**
![WhatsApp Image 2022-03-31 at 2 49 05 PM](https://user-images.githubusercontent.com/78934535/161118357-af446b8c-2d37-463a-8ce9-8b88b7593483.jpeg)

**y sin si activo el offline no se ven las tareas dentro de sus estados ( aparecen todas sin categoría) y si selecciono una no me muestra nada.** 

![WhatsApp Image 2022-03-31 at 2 48 51 PM](https://user-images.githubusercontent.com/78934535/161118972-5ee92a23-1a1a-4a0e-8ac7-ebad497a9d78.jpeg)

![WhatsApp Image 2022-03-31 at 2 47 31 PM](https://user-images.githubusercontent.com/78934535/161118551-60dff8fb-61e4-4e79-a29f-e3e2c31a2d80.jpeg)

**Asi se ve sin offline**
![WhatsApp Image 2022-03-31 at 2 48 00 PM](https://user-images.githubusercontent.com/78934535/161118517-59e3c572-2ba8-446b-98bb-177c0887d96d.jpeg)

Quedo atenta por si necesitas algo mas

**Comment by acedward** [comment]
corregido
