### ISSUE TITLE
Auto completado de access roles en creación de usuarios no funciona correctamente

### ISSUE THREAD

**Issue by AlejandroLoraG** [Cotalker/documentation#802]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

14.4.2

### Hola a tod@s! Espero se encuentren de maravillas y tengan una hermosa semana sin tantos bugsitos! 💕✌️

El auto completado de access roles para creación de usuario se queda pegado en la primera opción de access role que uno agrega. Luego al intentar buscar otro access role, el auto completado sigue mostrandome solo la primera opcion seleccionada previamente.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/51095635/160419413-ee448915-df45-402f-904a-8729fca2928b.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/51095635/160419626-0353546d-3bb4-4846-9fa1-047e0e005b6a.png">

Muchas gracias por tanto!
Saludooooos 🥰

### Steps to reproduce

1. Crear 2 access roles personalizados
2. Crear usuario
3. Agregar a este usuario estos 2 access roles
4. Repetir

### Expected result

Debiese aparecerme el acess role que estoy buscando.

**Comment by acedward** [comment]
¿Dónde estas viendo este comportamiento?
Actualizamos en todos los entornos con el nuevo input de access roles

<img width="555" alt="image" src="https://user-images.githubusercontent.com/3951895/160424240-9ccb3746-163f-48ba-974f-b2811d0d7572.png">

**Comment by agallardol** [comment]
Done, disponible en 17.8.3 en unos minutos
