### ISSUE TITLE
ISSUE: Los campos de la tasks (información, note, etc), que estén todos colapsados 

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#803]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.8.2 (228)

### Details

Hola a todos

Al revisar la información de la tasks, desde el channel tasks, me percaté que no todas las secciones se encuentran "colapsadas" y si los campos de la tasks cuentan con varios schemasinstances, no se visualizarizarán de mejor manera ya que "visualmente", la barra de scroll se encuentra un poco oculta y a la vez mueve una parte de la información, dejando como fijo las secciones "notas" y "Archivos

Adjunto varios SS

**1.- En el momento de abrir la información de la tasks**
<img width="380" alt="image" src="https://user-images.githubusercontent.com/61419471/160415333-f1ec18f4-21a9-4b0a-b875-5e34e63d8225.png">

2.- En el momento de ver los schemas de una tasks
<img width="380" alt="image" src="https://user-images.githubusercontent.com/61419471/160416557-35a897aa-9b30-4158-b796-45d4959845bf.png">

3.- En el momento de hacer scroll para ver la información de los schemasinstances
<img width="381" alt="image" src="https://user-images.githubusercontent.com/61419471/160416802-4c3a3795-cafe-4162-a71f-444c159a57f7.png">

4.- En el momento que el scroll no permite bajar para ver los archivos.(quizas sea por al dimensión de la pantalla
<img width="383" alt="image" src="https://user-images.githubusercontent.com/61419471/160417222-7025cd23-4252-4dff-981c-8322bdf2699f.png">

### Steps to reproduce

1.- Entrar a una tasks que cuenta con "X" schemasinstances
2.- Utilizar el scroll
3.- Ver resultado

### Expected result

1.- Inicialmente todas las secciones se encuentren contraidas y cada vez que veo una se expande mientras el restos se encuentren colapsadas. En el caso que quiera cambiar a otra secciones se repita el proceso (expande la que escojo y colapso la anterior.

y/o

2.- el scroll sea un poco más notorio y a la vez considere las secciones notes y files.

Gracias=>

### Additional data

No aplica

**Comment by acedward** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3951895/160423483-89cc4407-0086-48e4-b334-8df6124e4fac.png">

Efectivamente tenemos un problema con el doble scroll.
