### ISSUE TITLE
Bug report: Expresión válida arroja COTLang inválido en el editor de rutinas

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#805]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Latest Staging

### Details

Tengo este resultado para un COTLang válido:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/34345309/160706912-ab605c23-b87f-4745-9325-493c234c6d88.png">

Esto ocurre al utilizar el nuevo operador $IFNULL en una expresión que espera un diccionario. El COTLang en cuestión es el siguiente:
`($JOIN##```{"service_order":{"order_type":"```#($VALUE#answer|data|[find=>identifier=so_order_type]|process|0)#```","client":"```#($VALUE#answer|data|[find=>identifier=so_client]|process|0)#```","name":"```#($VALUE#answer|data|[find=>identifier=so_order_name]|process|0)#```","description":"```#($VALUE#answer|data|[find=>identifier=so_order_description]|process|0)#```","products":```#($IFNULL#($VALUE#answer|data|[find=>identifier=so_add_product]|process|0)#```{"uuids": []}```)|[json=>parse]|uuids|[toString=>JSON]#```,"performers":```#($IFNULL#($VALUE#answer|data|[find=>identifier=so_add_performers]|process|0)#```{"uuids": []}```)|[json=>parse]|uuids|[toString=>JSON]#```}}```)|[json=>parse]`

### Steps to reproduce

Ingresar el COTLang mencionado en la sección de "Extensions" de la acción "Crear tarea".

### Expected result

Debería ser aceptado como COTLang válido.

**Comment by MiikeVi** [comment]
Logré reproducir en staging, pero al parecer está corregido en dev

**Comment by MiikeVi** [comment]
Corregido en staging
