### ISSUE TITLE
Bug report: En la infra de coopeuch no se visualiza la versión PBPDF 3.0.0 en las rutinas

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#817]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

 Versión 17.9.2 (233)

### Details

Actualmente en la infra de la cia: 5d8a72c83375414a707f1d97 no visualiza el bot PBPDF version 3.0.0, sólo a 2.0.0 o primera version.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/61419471/161588619-87d26ae0-43f6-4433-b167-c06be1aa803b.png">

Esto nos afecta en el momento de usar el pdf en las implementaciones y actualmente sólo lo hemos cambiado por BD.

En el caso que actualizamos en la BD y luego vemos la rutina, ésta no se visualizará arrojando el siguiente mensaje:

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/61419471/161588861-b9da1742-6e20-4a58-92c6-2d25ce5fa2b9.png">

### Steps to reproduce

1.- Ir a la infra del cliente 5d8a72c83375414a707f1d97
2.- Crear un pdf
3.- Ver al máximo de las versiones que cuenta
4.- Cambiar la versión por BD
5.- Ver la rutina

### Expected result

Que se pueda ver la última versión del PBPDF en el Web Admin

### Additional data

Company: 5d8a72c83375414a707f1d97

**Comment by acedward** [comment]
Esto debe ser un problema de infra dedicada por favor comunicarse con GV.
