### ISSUE TITLE
Bug report: Public Surveys redireccionan a pantalla de login.

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#824]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging, Development

### Details

Configuré un formulario público:
![image](https://user-images.githubusercontent.com/34345309/162074164-8beb60fa-6c7a-4db1-87e5-b98579c0924e.png)

Al intentar usar el link provisto por el admin en un browser incógnito me redirige a la página de inicio de sesión.

### Steps to reproduce

1. Crear un public survey
2. Intentar acceder al link público

### Expected result

Poder enviar formularios públicos.

**Comment by AcencioMauricioIcinf** [comment]
Closed for now: Issue cannot be replicated anymore in the current settings
