### ISSUE TITLE
Bug report: Formulario de inicio y cambio de estado no se ven en offline mode

### ISSUE THREAD

**Issue by agallardol** [Cotalker/documentation#841]
### Affected system

Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production, Staging, Development

### App version

17.9.5

### Details

Al estar en modo offline no aparecen los formularios de Inicio y los de cambio de estado:
![Screen Shot 2022-04-13 at 17 07 03](https://user-images.githubusercontent.com/4631063/163270734-5b12ef6a-c068-4276-af8c-3f7479b1365e.png)

### Steps to reproduce

1. Iniciar sesión en tratton
2. Sincronizar la app para modo offline
3. Ir al grupo "Demo mantenimiento energético"
4. Intentar usar el formulario de inicio o el de cambio de estado

### Expected result

Que aparezcan los formularios de inicio y cambio de estado

**Comment by AcencioMauricioIcinf** [comment]
Fix available on release 17.9.6
