### ISSUE TITLE
What's New: Task View as Default View

### ISSUE THREAD

**Issue by Mauriceac** [Cotalker/documentation#844]
## Summary
Workflow groups will be displayed in task view by default.

## Who and how does it help
This user interface layout will help users have an overall view of tasks. The channel workspace will be hidden when not in use, giving more space to display tasks and their details.

![2022-04-14_14-42-17](https://user-images.githubusercontent.com/47286214/163455952-1ce7d790-16f3-421b-bf1a-251872329bc5.png)

## Changes for Users
The general layout will be changed when viewing workflow groups. The _group panel_, with the list of tasks, folders, and the action button (FAB) will not be displayed as accustomed. 

## Changes for Admins & Developers
In workflow group settings, admins will still be able to set the _traditional view_ as default.

![image](https://user-images.githubusercontent.com/47286214/163455796-45358677-f823-4499-b5f6-fe85c9241ef9.png)

## Modification / Creation of new sections.
- [x] Getting started > The Basics > UI Layout
- [x] Getting started > The Basics > Groups
- [x] Getting started > The Basics > Channel Workspace
- [ ]  Getting started > The Basics > Basic Tools > Actions Buttons
- [x] Getting started > The Basics > Basic Tools > Tasks
- [ ] Products > ALL WORKFLOWS!!!!
- [ ] Tutorials > Basic > Create a Workflow
- [ ] Tutorials > Basic > Task View
- [x]  Models > COTGroup (viewSettings NOT deprecated. See example below.)

_COTGroup update:_
```json
"viewSettings": {
        "initialView": "task" // options are: "task" or "group"
    },
```

## (Supplementary information)
Cotalker task link: https://web.cotalker.com/tasks/625598396ce3cd0007668584/list?groupId=625598396ce3cd0007668584&task=6255d172f96ccf4428320e14

**Comment by AcencioMauricioIcinf** [comment]
:+1:
