### ISSUE TITLE
Bug report:  Al crear task vista activa no queda en el nuevo elemento 

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#849]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

17.9.6 

### Details

Al crear una task en la vista de tareas o en la vista de canales, no queda la ventana activa en la tarea recién creada por lo que es dificil para el usuario continuar el flujo si es que ya tiene otros elementos creados.

**Vista canales**

https://user-images.githubusercontent.com/50208672/163842562-3dcc8d46-f273-4f2d-931e-15b120b8034a.mov

**Vista task**

https://user-images.githubusercontent.com/50208672/163845668-1e2a1994-76ec-41df-8c64-9e8137ed87a9.mov

### Steps to reproduce

Crear una nueva task en un worflow

### Expected result

Que luego de crear la tarea, la ventana activa quede dentro de la tarea recién creada, independientemente si es vista de task o vista de channels.

**Comment by AcencioMauricioIcinf** [comment]
> @AcencioMauricioIcinf @eduborgono este fix esta solo en dev?

Lo siento, para dejar funcionando una funcionalidad en el servicio offline, tuve que deshacer esto específicamente en la creación de tareas en móvil

**Comment by jdurandpaz** [comment]
@AcencioMauricioIcinf oka, de todas formas en web tampoco esta funcionando correctamente, voy a subir un video

**Comment by AcencioMauricioIcinf** [comment]
@jdurandpaz  Pasa a menudo? Estuve probando con y sin fix el problema y ahora, en el branch master me funciona bastante bien (ya no se produce el problema)

**Comment by jdurandpaz** [comment]
al menos en staging pasa igual que como se muestra en el video que subió @maramire , si quieres lo revisamos en discord

**Comment by AcencioMauricioIcinf** [comment]
Nuevo fix en camino a main, faltaba añadir un switch en queryparams para registrar un cambio de url

**Comment by AcencioMauricioIcinf** [comment]
Fix ya está en main, si alguien lo puede probar en prod

**Comment by AlexBaader** [comment]
Holaaaa! En staging sigue con problemas. Se crean nuevas tareas y no se abre el canal de forma automática. 
Adjunto video!

https://user-images.githubusercontent.com/98488087/187764876-ccfdfa6d-08b8-4a35-b54f-6be220ff947f.mov

**Comment by jdurandpaz** [comment]
@AcencioMauricioIcinf
