### ISSUE TITLE
Bug report: Buscador no aparece

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#851]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Se realiza una búsqueda y se hace click sobre un resultado / cambia grupo / selecciona canal
deja de funcionar el buscador (no aparece) 

Queda en un estado corrupto que solo se logra salir haciendo refresh

[Video](https://drive.google.com/file/d/1KPnu--rXS8d-Drdo5XgesnVB45edg6ln/view?usp=sharing)

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/3951895/163883385-14d95633-e12c-4b1b-bafd-835a7610e8a6.png">

### Steps to reproduce

Realizar búsqueda
Hacer click sobre resultado
Realizar búsqueda 
Eventualmente deja de funcionar.

### Expected result

Que el buscador siempre aparezca

**Comment by eduborgono** [comment]
fix: https://github.com/Cotalker/cotalker-webclient/pull/2868

**Comment by agallardol** [comment]
Corregido en 17.9.7
