### ISSUE TITLE
Documentation > Como activar el modo offline

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#852]
# Sección to be revised
Documentation > _____ > _____

# Objective
Task to be accomplished.

# Details
Further details about the task.

# Other
Any extra information or optional tasks.

# Priority
High, Medium or Low

**Comment by jdurandpaz** [comment]
@Mauriceac la idea es poder documentar como activar el modo offline desde el punto de vista de un usuario. Yo tengo el siguiente documento con una explicación muy básica https://docs.google.com/document/d/1c-k3MSGNjiLa0W8PvNg94gmAST75unLrHxR6azflkP4/edit

**Comment by Mauriceac** [comment]
Algún deadline?

**Comment by jdurandpaz** [comment]
@Mauriceac ideal esta semana ya que mañana activaremos la fuincionalidad en una company en productivo

**Comment by Mauriceac** [comment]
Listo! Tengo un primera versión del feature subido.

Aquí está el link del What's New: https://doc.cotalker.com/blog/2022/04/20/offline-mode
Aquí está el link de la Documentación: https://doc.cotalker.com/docs/documentation/client/offline

Cualquier feedback es bienvenido. 

NOTA: _Hay algunas cosas que a mi no me funcionaron pero las documenté como salían en los apuntes._

**Comment by jdurandpaz** [comment]
@Mauriceac

![giphy (1)](https://user-images.githubusercontent.com/50208672/164273677-24986f32-8951-458a-860d-b9f2b078f0bc.gif)
