### ISSUE TITLE
Bug report: pb-get-channel-messages is wrongly sending data

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#853]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### App version

15.0.0

### Details

The bot is being built with the data field "answer" instead of "surveyId", this causes an inevitable error.
![image](https://user-images.githubusercontent.com/45186006/163941621-7d86d300-bbb3-4803-9eff-07d8cc918988.png)
![image](https://user-images.githubusercontent.com/45186006/163941640-9479f38c-3cc5-454c-ba8d-914b63ec18bc.png)
![image](https://user-images.githubusercontent.com/45186006/163941648-0a0b8d0e-c54f-4783-8bf8-fe4e9122bcd7.png)

### Steps to reproduce

1. Through the admin bot builder try creating a routine that uses pb-get-channel-messages and see how it builds the data

### Expected result

Bot should build its data field with "surveyId" instead of "answer"

**Comment by acedward** [comment]
Fixed.
