### ISSUE TITLE
BUG: Precargado de múltiples propiedades en Question Exec

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#856]
### Discussed in https://github.com/Cotalker/documentation/discussions/855

<div type='discussions-op-text'>

<sup>Originally posted by **maramire** April 19, 2022</sup>
Holaa, buenas

Estoy intentando precargar propiedades en un multiple choice, pero no me deja precargar más de una propiedad. Este es mi código del question Exec (donde transacciones es un array de id's de propiedades):

function run(){
    const commands = [];
    const property = context['property#channel'].find(k => k.propertyType === "controversias_assets");
    const transacciones = property.schemaInstance.transacciones;
    console.log(JSON.stringify(transacciones))
    commands.push(
        {
        cmd: 'SET_RESPONSES',
        value: JSON.stringify(transacciones)
        }
    );
    commands.push(
      { 
      cmd: 'SET_READONLY',
      value: 'true' 
      }
    );
    return commands;
}

Esto es lo que me retorna la llamada de red:
![image](https://user-images.githubusercontent.com/31930273/164057778-a12ba170-cece-43a5-bb03-693d93cc177f.png)

Probé precargando solo una propiedad y funcionaba, pero al mandar un array de id's me devuelve el error antes mencionado.

Se agradece cualquier ayuda!

</div>

**Comment by acedward** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/3951895/164076578-f6a8cf9b-6e0e-408f-8d5a-fe8d9f882c4e.png">

**Comment by acedward** [comment]
Más detalles en https://github.com/Cotalker/documentation/discussions/855
