### ISSUE TITLE
Typo in endpoint path for publicSurvey

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#862]
# Sección to be revised
Api Swagger > publicSurvey

# Objective
Wrong documentation. The path for publicSurvey is public-surveys

# Details
Is a typo

# Other
Direct Link: https://www.cotalker.com/swagger/core/?key=woubtjf4olr0t4zgutuwn6scbcm6hd3qh1cgl5obmohpbm3mfublnwcvv67lodgjvd3h86s9ppshtvmf95gepsqh6nizq9liu7f#/publicSurvey/getPublicSurvey

# Priority
I don't know how many people use the documentation, but if a partner use it, I think is a high.

**Comment by Mauriceac** [comment]
@ValeMP I don't think I'm the one indicated to carry out this correction. I don't have access to the code that automatically generates the Swagger API documentation. But I can ask and see how we can fix this.

**Comment by Mauriceac** [comment]
Issue fixed.
Thanks @eduborgono !!!!
You're the best!
![2022-04-22_14-39-23](https://user-images.githubusercontent.com/47286214/164774886-081ccb85-d836-42f4-b406-b419ab208c6d.png)
