### ISSUE TITLE
Bug report: Display erroneo en compañía cliente gestión documental

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#863]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.9.6

### Details

Al abrir tareas desde vista de lista con filtro predeterminado de "Todos los productos" donde se ven en este cliente task con inicio colapsado, al abrir una task cualquiera, el esperable es que muestre primero el "ARCHIVO" asociado a esa task. Sin emabrgo, se está mostrando la ventana de "CHAT" predeterminadamente en ciertos casos lo que no permitiría al usuario final ver el procedimiento inicialmente a menos que conozca que tiene que cambiar de pestaña.

### Steps to reproduce

1. Abrir gestión documental de cliente bancario
2. Ingresar a cualquier canal (ej: Cierre generación)
3. Ingresar a alguna task dentro de este canal
4. Verificar vista inicial de la task. Si es canal de "Chat" lo primero que se ve, eso está mal

### Expected result

1. En paso 4 de lo anterior, debería verse inicialmente el "ARCHIVO" asociado como primera vista al abrir cada task

**Comment by agallardol** [comment]
Corregido en versiones previas al cliente actual
