### ISSUE TITLE
Bug report: No se puede levantar un formulario de tipo action button

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#866]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.9.7 (238)

### Details

En el flujo de operaciones se encuentra <img width="800" alt="image" src="https://user-images.githubusercontent.com/61419471/164780354-fb4e9204-1c9e-4d01-89c1-60b833d01b01.png">

Donde el formulario "(GP) Crear tarea al proyecto", corresponde a un formulario de canal y formulario de inicio de una submáquina "tareas ops", como se muestra en la siguiente imágen
<img width="888" alt="image" src="https://user-images.githubusercontent.com/61419471/164780931-ccd380c5-2dfe-426b-af45-18103714e4fa.png">

Antes de la versión funcionaba de manera correcta

### Steps to reproduce

1.- Ingresar al grupo indicado
2.- Entrar a un canal de proyecto
3.- Ingresar el formulario indicado
4.- Esperar los resultados

### Expected result

Se debería mostrar el formulario para la ejecución, como se muestra en la imagen:

![Uploading image.png…]()

### Additional data

NOo aplica

**Comment by agallardol** [comment]
Available in 17.9.8
