### ISSUE TITLE
Bug report: Funcion f_worktime no cumple con las horas de contrato

### ISSUE THREAD

**Issue by PanchoAguilar** [Cotalker/documentation#867]
### Affected system

Cotalker Web Application

### Affected system (other)

Metabase

### Affected environment

Production

### Details

f_worktime es una función sql que toma las horas de trabajo para medir cuantas horas de trabajo se han invertido entre 2 fechas.
f_worktime toma las horas de trabajo entre las 10:00 y las 18:00 hrs.
La aplicación actual de f_worktime es en metabase "Soporte" para contar las horas de trabajo que demora la resolucion de un ticket
![image](https://user-images.githubusercontent.com/104232411/164801533-d66bd8de-c09b-4666-9675-285931776678.png)
Tras análisis en contrato soporte junto a David Ehrenfeld las horas que deberian estar allí deberian ser desde las 9:00 hasta las 18:00
De esta manera se podran obtener "sla" reales de los tiempos que esta tomando resolver tickets y aseguramos un paso a mas a la fiabilidad de los datos 

### Steps to reproduce

1. encontrar funcion sql f_worktime
2. modificar 10 am por 9 am

### Expected result

que tome las horas de 9 a 18 horas por dia entre 2 fechas distintas

**Comment by agallardol** [comment]
@PanchoAguilar podrías cerrar este issue cuando esté todo listo?

**Comment by PanchoAguilar** [comment]
mañana jueves espero cerrarla!

**Comment by agallardol** [comment]
@PanchoAguilar cómo te fue con esto?

**Comment by agallardol** [comment]
Merged y en production
