### ISSUE TITLE
Bug report: metabase no está creando compañias nuevas en postgres|metabase 

### ISSUE THREAD

**Issue by Sadaka1234** [Cotalker/documentation#871]
### Affected system

Cotalker Api

### Affected system (other)

selfservice

### Affected environment

Production

### Affected environment (other)

cotalker-playground

### Details

En algunos casos, al crear la compañia a traves del svc-exporter-importer, la compañia no se crea en Postgres, lo cual a su vez genera que no aparezca en metabase. Hoy dos compañias fueron creadas y ambas tubieron este problema.

El error genera que metabase se reinicie y aparece el siguiente error en los logs:

![image](https://user-images.githubusercontent.com/29810844/165406061-7124dc8a-cc9c-46af-b3eb-d7af29fc3439.png)
![image](https://user-images.githubusercontent.com/29810844/165406016-2f1aef9f-64b7-4f7e-8a94-f333b3790c58.png)
![image](https://user-images.githubusercontent.com/29810844/165608397-ab8f4116-21eb-48f4-8011-4bbf34d30585.png)

No se ha podido reproducir a voluntad, pero el error de la primera imagen sale sin parar hasta que finalmente tira el segundo error. Se cree que esto podria generar que no se sincronize bien ni se genere la nueva compañia. Esto debido a que en algunos casos, se genera la compañia en metabase, pero sin tablas.

Esto está pasando en el ambiente de playground, y causa que algunas compañias se creen sin dashboards

### Steps to reproduce

Crear una compañia en ambiente de demo/productivo a traves del landing o por api

### Expected result

Compañia se crea correctamente en postgres y metabase, lo cual permite generar dashboards

### Additional data

Los logs se pueden revisar en svc-sql

**Comment by martinmiranda14** [comment]
Solucionado problema en development
