### ISSUE TITLE
Bug report: Me gustaría reportar un posible bug: la burbujita roja de las notificaciones no me aparece en iphone y me acabo de enterar que sí aparece en android. Pensé que no exisitía. Puede ser un bug.

### ISSUE THREAD

**Issue by VicenteCaridi** [Cotalker/documentation#873]
### Affected system

Cotalker iOS Application

### Affected environment

Production

### Details

Me gustaría reportar un posible bug: la burbujita roja de las notificaciones no me aparece en iphone y me acabo de enterar que sí aparece en android. Pensé que no existía. Puede ser un bug.

### Steps to reproduce

No lo sé

### Expected result

Que aparezca la burbujita también en iPhone.

**Comment by AcencioMauricioIcinf** [comment]
Hola Vicente. ¿Podrías por favor decir dónde encontraste que no aparecen las burbujas de notificaciones?

**Comment by AcencioMauricioIcinf** [comment]
Issue mayor reportado en #1099

**Comment by VicenteCaridi** [comment]
Hola Mauricio!

En mi celular (iphone) me llegan las notificaciones, pero no se acumulan en
una burbujita roja como en el resto de apps.

Adjunto ejemplo.



Saludos,
