### ISSUE TITLE
Bug report: Buscador no funcionando cómo se espera para cliente gestión documental

### ISSUE THREAD

**Issue by DavidEhrenfeld** [Cotalker/documentation#877]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.9.9

### Details

Al intentar buscar títulos de procedimientos (notas) 100% literales, el buscador no está encontrando lo buscado. No es que solamente no los encuentre en 1er lugar de la búsqueda, sino que al "ver más" tampoco encuentra el texto literal buscado.

### Steps to reproduce

1. Entrar con cuenta admin de cliente que utiliza gestión documental
2. Buscar procedimiento cuyo título es: "Transferencias y Pagos No Reconocidos Vía Web  (Con Ley de Fraude)"
3. Verificar si encuentra ese procedimiento que debiese tener númeración #422 
4. Si no lo encuentra, ingresar en búsqueda solamente la palabra "Transferencias" y buscar #422 en la lista de resultados

### Expected result

El resultado esperable (y que ocurría anteriormente) es que al ingresar un título coincidente en un 100% con el título de una tarea o procedimiento (nota asociada a la tarea), se entregue en 1er lugar de la lista de resultados. Al parecer el buscador no está reconociendo peso a palabras continuas y desde vista usuario pareciera como si retornara resultados en base a palabras sueltas solamente como "transferencia", "pagos", "no", "reconocidos", "via", "web", pero no está asignandole peso a encontrar siquiera la concatenación de "transferencias y pagos" como 3 palabras concatenadas continuas.

**Comment by DavidEhrenfeld** [comment]
No sé porque quedó como link el número de procedimiento (debiese ser # 422 dentro de compañía cliente, no dentro de issue github)

**Comment by agallardol** [comment]
Implementamos una mejora para esto durante Junio
