### ISSUE TITLE
Bug report: Survey not saving correctly when a group is assigned in Access -> Group Permission's field.

### ISSUE THREAD

**Issue by digutier** [Cotalker/documentation#881]
### Affected system

Cotalker Web Application

### Affected environment

Development

### App version

15.0.0 (1228)

### Details

While creating or editing a survey, when the user assigns a group in **Access -> Group Permission** and press **save**, an error message will appear saying that the **groupPermission** property must be a string, but an array with a string inside is provided.
![image](https://user-images.githubusercontent.com/66893053/166584022-2acd7520-2e34-4d24-8b22-9e0c5007888c.png)
Is important to note that if the user clears the Group Permission field during the process, the same error will appear but it will show an empty array instead.

### Steps to reproduce

1. Enter to a view of creating/editing a survey.
2. Inside Access -> Group Permission select a group. (you need a created group for this)
3. Save. **Now** the error **occurs**.

### Expected result

After pressing the **'Save'** button the request should finish successfully without errors applying the correspondant access. A **workaround** for this case should be taking the string inside the array instead when assigning the value of **groupPermission** property.

**Comment by agallardol** [comment]
Disponible en 17.10.4
