### ISSUE TITLE
Bug report: 'Last modified' value not showing correctly for Collections and Elements.

### ISSUE THREAD

**Issue by digutier** [Cotalker/documentation#882]
### Affected system

Cotalker Web Application

### Affected environment

Development

### App version

15.0.0 (1228)

### Details

This issue consists in two parts:
- **Collection issue:** When the user tries to edit a collection from Admin, the 'Last modified' value **does not change**, keeping it's **original value** of when created. For example, if i try to modify a Collection created on **January 12th**, the PATCH response **mantains the same values** between 'createdAt' and 'modifiedAt'. (I just modified on **May 3rd** 'ARUBSTIVO' collection name to 'ARBUSTIVO2')
![issue last modified](https://user-images.githubusercontent.com/66893053/166612828-3370b930-7fee-4dad-bfff-34819ca24f66.png)
- **Element issue:** In this case, when the user creates/edits an Element, the 'Last modified' value is **partially correct**. The associated date is correct but the **hour format is not**. It is like AM/PM but without the 'AM' or 'PM' when it should be a 24-hour format. For example, if i edit an element now on **May 3rd at 21:54**, the 'Last modified' date is correct but the hour says 09:53. (I just modified 'ARAUCARIA ARAUCANA' element name to 'ARAUCARIA ARAUCANA2')
![issue last modified 2](https://user-images.githubusercontent.com/66893053/166613665-06a89274-dcf6-4602-b69f-39c9c0ffcc5e.png)

### Steps to reproduce

Collection issue:
1. Go to Admin -> Database.
2. Edit a Collection and check if the 'Last modified' value changed.

Element issue:
1. Go to Admin -> Database -> (enter to any Collection)
2. Edit an Element and check if the 'Last modified' hour format is correct.

### Expected result

- For the collection case, when editing the expected result is to see the correct 'Last modified' value representing **the current date and hour**.
- On the other hand, when creating/editing the expected result is to see the **correct hour format** for 'Last modified' value.

**Comment by agallardol** [comment]
Disponible 02/08/2022
