### ISSUE TITLE
Selector de filtro predeterminado en taskgroup

### ISSUE THREAD

**Issue by soporte-cotalker** [Cotalker/documentation#885]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### App version

17.10.2

### Details

Al entrar al administrador, editor de taskGroup, el selector de filtro predeterminado muestra todos los filtros del usuarios (privados y publicos), y solo se deberían mostrar filtros publicos (activos).

### Steps to reproduce

1.- entrar a administrador
2.- editar/crear taskgroup

### Expected result

Se muestran todos los filtros de usuarios, deberían mostrarse solo los filtros publicos.

**Comment by acedward** [comment]
Duplicado en https://github.com/Cotalker/documentation/issues/886
