### ISSUE TITLE
Bug report: Entrar a task con un filtro que no existe (o existe pero es privado de otro usuario) genera un error en el modulo de tareas

### ISSUE THREAD

**Issue by ccarrascor** [Cotalker/documentation#886]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application, Cotalker Api

### Affected environment

Production, Staging, Development

### App version

17.10.2

### Details

Al entrar con un filtro especifico al modulo de tareas, si este no existe o existe pero es privado de otro usuario, se tiene un error y no se carga nada.

### Steps to reproduce

1. Entrar a modulo de tareas con un filtro que no existe (id erronea), o bien entrar con el id de un filtro privado de otro usuario.

### Expected result

Si el filtro no existe, deberia cargar las tareas como si no existiera dicho filtro.

**Comment by digutier** [comment]
Disponible en 17.10.8
