### ISSUE TITLE
Bug report: no se actualiza desde cero el "serial" de la task al hacer el clean de la compañía

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#890]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Holaa! Me podrían ayudar con este issue porfa :)

Cuando hago un clean de la compañía con el comando:
[REDACTED]
No se actualiza el valor del serial desde 1.

Tenía varias tareas creadas en la compañía, luego ejecuté el comando y el retorno fue el siguiente:
```
{"status":true,"message":"","data":{"accessroles":24,"analyticslogs":185,"answers":185,"apitokens":0,"audit-log":0,"bots":14,"calendars":0,"calendarrestrictions":0,"messages":1264,"channels":52,"filemetas":17,"groups":11,"jobtitles":7,"notifications":117,"unreadmessages":55,"pbscripts":7,"properties":276,"propertytypes":66,"publicsurveys":2,"questions":454,"redirects":0,"sessions":189,"smslas":1,"smstates":41,"smstatechanges":69,"smstatemachines":10,"surveychats":234,"surveys":46,"taskfilters":8,"contacts":0,"users":46,"userrecoveries":0,"schedules":103,"logs":103,"cotalker-sql":1,"elastic":1,"task-products-sq_service_quotations":24,"task-products-ordenes_de_servicios":4,"task-products-am_asset_managments":0,"task-products-purchase_orders":2,"task-products-pm_preventive_maintenances":0,"task-products-m_work_orders":0,"task-products-cm_corrective_maintenances":0,"task-products-m_quotes":0,"task-products-am_inventory_acquisitions":8,"sequences":1,"taskgroups":9,"companies":1}}% 
```

Luego, la compañía se vacío, creé una nueva tarea, pero no se crea con "serial"=1, sino que sigue en la quedó antes. Por ejemplo, creé la primera tarea y me salió con el serial=122 (que era el siguiente número si no se hubiera borrado nada), tal como se muestra en la imagen
<img width="803" alt="image" src="https://user-images.githubusercontent.com/73865460/166973064-e4c9b370-28f5-46e2-b2c6-f249a3e82c7d.png">
Verificando, la llamada de red para buscar a la task: https://staging.cotalker.com/api/tasks/35f15cbdde0b290007618f65/task/6273ff26f88f2428b08cb673
me trae en el objeto `"serial": 122,`

### Steps to reproduce

1. Borrar una compañía
2. Crear una task
3. Ver que el serial no comienza de 1.

### Expected result

Que la primera tarea creada tenga `"serial": 1,`

**Comment by acedward** [comment]
@CVargasGando este es un problema del tooling interno y no de la plataforma.
Esto debe ser atendido por el equipo interno.

**Comment by acedward** [comment]
@Sadaka1234 si quieren corregir esto, por favor hablen conmigo, @martinmiranda14 o @eduborgono
