### ISSUE TITLE
Bug report: Incompatibilidad de  Microsoft Edge con Cotalker 

### ISSUE THREAD

**Issue by AlexBaader** [Cotalker/documentation#897]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Affected environment (other)

production 

### App version

17.10.6

### Details

No permite iniciar sesión en Microsoft Edge. 
Una vez en la página, al intentar ingresar a la cuenta, aparece una advertencia que dice " this browser does not support Cotalker".
Esto ocurre tanto en windows como en Mac.

### Steps to reproduce

Ingresar a Cotalker web e intentar iniciar sesión. 
El sistema no te dejará continuar por incompatibilidad con el navegador. 

### **Windows**

![image](https://user-images.githubusercontent.com/98488087/167512651-1bd976c4-0445-40f0-99a6-34233a16eb9c.png)

### **Mac**

![image](https://user-images.githubusercontent.com/98488087/167512721-74306986-dbbf-4d82-b4b2-2710edb48e06.png)

### Expected result

Poder usar Cotalker en Edge

**Comment by agallardol** [comment]
Ya revisamos esto internamente con operaciones
