### ISSUE TITLE
Bug report: Al enviar formulario con survey+survey la sub answer de este survey+survey no se crea

### ISSUE THREAD

**Issue by AlejandroLoraG** [Cotalker/documentation#899]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0

### Hola a tod@s! Espero estén teniendo una maravillosa semana 🥰

Traigo un bug curioso. En un formulario tengo una question de tipo survey+survey. Al momento de enviar este formulario con esta question la answer de este survey+survey no existe! Es decir, al buscar el UUID de esta sub answer en base de datos, no encuentro nada. Adjunto imágenes.

Formulario padre:
![image](https://user-images.githubusercontent.com/51095635/167666496-0b88717a-d920-4681-9e8c-9cdb68b7ae9c.png)

Formulario hijo:
![image](https://user-images.githubusercontent.com/51095635/167666670-d8eb367d-64bb-4411-b604-05c779f90266.png)

Vista real:
![image](https://user-images.githubusercontent.com/51095635/167667589-2ae817c5-a6b9-4dd9-9890-ef7e1b6d9944.png)

Al ser enviado:
![image](https://user-images.githubusercontent.com/51095635/167667678-6c5727f5-ed64-4d0b-b778-c058dde7cc8c.png)

Contexto survey trigger:
![image](https://user-images.githubusercontent.com/51095635/167667813-890fef1d-1491-4d4d-82f8-313ab0bca309.png)

Al buscar el UUID en BD:
![image](https://user-images.githubusercontent.com/51095635/167668074-0b34df27-e348-4e9c-bc33-d66b257dd4c4.png)

No sé muy bien la réplica de esto! Así que cualquier cosa hablen conmigo. Alelo!

Muchas gracias por tanto, saludos!!! 🧡

### Steps to reproduce

1... No he podido replicarlo. 
2... Hablen con alelo.

### Expected result

Debiese crearse el answer correctamente.

**Comment by acedward** [comment]
@jdurandpaz @AlejandroLoraG pueden poner un mensaje antes del survey survey. Que no sea el primer campo.

**Comment by jdurandpaz** [comment]
listo! , eso sí no pude probar porque el QA ya iba a partir

**Comment by jdurandpaz** [comment]
si esto soluciona el bug, podríamos hacer que los forms siempre lleven el título obligatoriamente

**Comment by agallardol** [comment]
Bkn @jdurandpaz. Cerraré este issue por ahora, en el futuro podemos evaluar si revisitar esto (es súper costoso revisar ahora).

**Comment by Mauriceac** [comment]
## Mientras tanto:

https://doc.cotalker.com/docs/documentation/admin/survey/components/survey/

![2022-05-13_16-40-32](https://user-images.githubusercontent.com/47286214/168386379-f0e41356-317a-461d-86cb-2e28b4482464.png)

**Comment by digutier** [comment]
Resuelto y disponible en 17.10.11
