### ISSUE TITLE
Bug report: Invite user to the task: Automation logs show error, but the stage run successfully

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#906]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Trabajando con el pbbot PBTaskAddEditor v 2.2.0 de tipo access Role, cada vez que se ejecuta bien me retorna un 500 en el automatation log, lo cual no deja que continúe la rutina. 

El error que aparece es este:
```
  {
    "key": "invitar_postventa",
    "name": "PBTaskAddEditor",
    "status": "ERROR",
    "result": {
      "errors": [
        "STATUS CODE: 500\nBODY: {\"error\":\"Error: Task not found\",\"status\":false}"
      ]
    },
    "nextBot": "enviar_mensaje",
    "iteration": 2
  }
```

Y la rutina es la siguiente:
```
  },
  "invitar_postventa": {
    "name": "PBTaskAddEditor",
    "version": "2.2.0",
    "variables": [],
    "data": {
      "type": "accessRole",
      "task": "627c1fe53124230007289f4f",
      "taskGroup": "6273ed0624b573277bbed14e",
      "accessRole": "Post Venta - Presupuestos"
    },
    "next": {
      "SUCCESS": "enviar_mensaje",
      "ERROR": "enviar_mensaje"
    }
```

Además la explicación de que dato debe ir en el access role está mal, dado que no es el id del acceso rol sino su nombre.

<img width="565" alt="Captura de Pantalla 2022-05-11 a la(s) 16 57 45" src="https://user-images.githubusercontent.com/42095617/167946359-9e541365-1595-481b-b5a1-fc9596f1f80f.png">

### Steps to reproduce

1. Crear una rutina de invite user 
2. Ejecuta la rutina y visualiza los Logs

### Expected result

Si es que la etapa es exitosa, que retorne un 200 o un success con el json de la task

**Comment by digutier** [comment]
Hola, probando el caso asociado al issue, no se detectaron problemas al respecto que tenga que ver con el "Task not found". No se pudo ver el caso particular (por la antigüedad del issue). Se hicieron varios tests al respecto y se llega a la conclusión de que no hay un error. Sin embargo, de igual forma se hace la sugerencia del cambio del bot para que diga "nombre" en vez de "id" para evitar confusión. Ese cambio está pendiente aún.

**Comment by digutier** [comment]
Resuelto en release-3.2.7
