### ISSUE TITLE
Bug report: Socket no actualiza vista tareas al hacer cambios de estados.

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#910]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Última versión productiva

### Details

Al cambiar de estado una tarea de "Backlog" a "Solved", no se actualiza su visualización para aparecer en la agrupación correspondiente:
![image](https://user-images.githubusercontent.com/34345309/168499295-d8cb4af1-dd66-4da4-a7cb-e294807bfc58.png)

### Steps to reproduce

1. Abrir una tarea en la vista tarea agrupadas por estado.
2. Cambiar de estado una tarea
3. La tarea seguirá apareciendo en la agrupación original.

### Expected result

Que la tarea aparezca en la agrupación correcta.

**Comment by AlexBaader** [comment]
holaaa! este bug nos está afectando con un cliente 😅

**Comment by agallardol** [comment]
Solved. Disponible en 17.13.9
