### ISSUE TITLE
Bug report: DOMPurifier, setear links con target="_blank" 

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#914]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected system (other)

Sanitizador HTML

### Affected environment

Production, Staging

### App version

17.10.9

### Details

Para una implementación necesitamos abrir unos links de imágenes de un message html. las imágenens se abren en el mismo iframe ya que el purificador limpió el target="_blank" me imagino por las siguientes razones expresadas acá:
[Artículo de seguridad de links target blank](https://web.dev/external-anchors-use-rel-noopener/)
Lamentablemente esta imagen reemplaza el mensaje en la vista.
En [esta discussion](https://github.com/cure53/DOMPurify/issues/317) entregan una solución para que todos los links tengan apertura en _blank de forma segura con _noopener_.

### Steps to reproduce

Enviar por text/system algún mensaje tipo system que contenga una url con target _blank, ver que no persiste ese atributo

### Expected result

links declarados con _blank debiesen dejar abrir en otra pestaña

**Comment by jdurandpaz** [comment]
issue esta afectando a dos clientes en productivo

**Comment by AcencioMauricioIcinf** [comment]
@Yiakman @jdurandpaz pueden volver a revisar si esto sigue pasando? Lo revisé hace poco, y en los links sí aparece el tag `target="_blank"`, y sí, se abre en otra pestaña. Esto en prod.

**Comment by AlexBaader** [comment]
Hola @AcencioMauricioIcinf! en Esmax seguimos con el problema 😅. Al enviar un html con el link adentro, la pestaña se abre dentro del mismo. 
<img width="772" alt="Captura de Pantalla 2022-07-22 a la(s) 15 31 29" src="https://user-images.githubusercontent.com/98488087/180514216-c3f3a6db-0efd-44b1-a9eb-fd6feaf5be89.png">

Al hacer click en el link de la ot, la abre dentro del html y no en una pestaña aparte. 

<img width="778" alt="Captura de Pantalla 2022-07-22 a la(s) 15 31 54" src="https://user-images.githubusercontent.com/98488087/180514251-fd4a385a-44d5-47ec-8a04-1f23f1e17e54.png">

**Comment by agallardol** [comment]
Corregido, disponible desde el 02/08/2022
