### ISSUE TITLE
Bug report: Question Exec: SET_RESPONSE of multiple choice not working when you save a survey

### ISSUE THREAD

**Issue by ValeMP** [Cotalker/documentation#918]
### Affected system

Cotalker Web Application

### Affected system (other)

backend

### Affected environment

Staging

### App version

15.0.0

### Details

Estoy trabajando con formularios autocompletables, en donde a través de un validate relleno otros campos del formulario. Uno de los campos es un selector múltiple que cuando se rellena, en el forntend se observa como si ha sido seleccionado, pero cuando se envía el form aparece como si no se ha seleccionado nada.

Disclaimer: También estoy haciendo llamadas de red en el question exec

Imágenes de referencia:
<img width="607" alt="Captura de Pantalla 2022-05-19 a la(s) 19 22 52" src="https://user-images.githubusercontent.com/42095617/169420077-5246a5a0-9b1f-422d-9454-cce9beb50bec.png">

<img width="609" alt="Captura de Pantalla 2022-05-19 a la(s) 19 23 02" src="https://user-images.githubusercontent.com/42095617/169420058-7422ac07-dc2a-4c43-ad5f-0a807656cd96.png">

### Steps to reproduce

1. Crear un formulario que sea de set responses de un formulario de selector multiple
2. Dejar los campos de selector múltiple como obligatorio
3.Responder el formulario y observar que no se puede guardar

### Expected result

Debería permitir enviar el formulario y debería capturar que el campo esta respondido.

### Additional data

Aqui les pego el código de la question exec:
```
async function run(){
    sleep(10000);
   const commands = [];
    const serie = context['responses#self'];
  console.log("serie", serie);
    if (serie.length != 0) {
    const response = await networkRequest(`https://staging.cotalker.com/api/v2/properties/?codes=m_` + serie, {headers: {"admin":"true", "Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWYyZGI2ZTc4NWQxNzljMWQ0NWYwMWEiLCJyb2xlIjoidXNlciIsImNvbXBhbnkiOiI1ZjNlN2RhYTYxOGNlNjAwMDhiMGFlMjQiLCJkYXRlIjoxNjUxMTYwMTExNDI4LCJpcnQiOnRydWUsImlhdCI6MTY1MTE2MDExMSwiZXhwIjoxNjUzNzUyMTExfQ.hNG4l5-HWMeCyQis7cUyrxxN9y1-YRKZ8_GiXfbYiAM"}});
     console.log("response ", response);
     const property = response.data.properties;
    console.log("property ", property);
  if (property.length != 0)
 {
     commands.push( { cmd: 'RESULT', result: true });
       if (property[0].schemaInstance.material_brand) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_brand", value: property[0].schemaInstance.material_brand });}
     if (property[0].schemaInstance.material_model) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_model", value: property[0].schemaInstance.material_model });}
      if (property[0].schemaInstance.material_accumulated_depreciation) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_deprec", value: property[0].schemaInstance.material_accumulated_depreciation });}
         if (property[0].schemaInstance.material_accumulated_monthly) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_monthly_deprec", value: property[0].schemaInstance.material_accumulated_monthl });}
       if (property[0].schemaInstance.material_denomination_1) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_denom1", value: String(property[0].schemaInstance.material_denomination_1) });}
              if (property[0].schemaInstance.material_denomination_2) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_denom2", value: String(property[0].schemaInstance.material_denomination_2) });}
        if (property[0].schemaInstance.material_useful_life) { commands.push({ cmd: 'SET_RESPONSES', target: "activo_lifeexpect", value: property[0].schemaInstance.material_useful_life });}
    console.log("Body ", commands)
      return commands;
 }}
      commands.push(
    { cmd: 'RESULT', result: true, value: "Material aun no ingresado" }
        )
     return commands;                        }
```

Los denomination son los campos de selector múltiple.

**Comment by digutier** [comment]
Resuelto y disponible en 17.10.12
