### ISSUE TITLE
Bug report: endpoint para limpiar compañía no termina de ejecutarse

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#920]
### Affected system

Cotalker Api

### Affected environment

Staging

### Details

Hoola team! espero que tengan un gran día lunes :)

Quería pedirles ayuda con el endpoint para limpiar una compañía: 
curl -XDELETE https://staging.cotalker.com/api/v3/exporter-importer/remover/${id_compañia}

Al ejecutarlo se queda pegado en alguna parte y no termina de ejecutarse:
![image](https://user-images.githubusercontent.com/73865460/169830840-25e11550-9ad5-4267-ac51-f7dc6c469320.png)

Si corto la ejecución y entro a la compañía, algunas cosas se alcanzaron a eliminar, por lo que al parecer llega a algún punto en el que se queda pegado y no termina de limpiar la compañía :(

Agradezco su genial ayuda 🙏

### Steps to reproduce

Ejecutar el comando para limpiar la compañía y ver que no se termina de ejecutar :(

### Expected result

que se ejecute el comando y se borre toda la compañía

**Comment by ValeMP** [comment]
No volvió a pasar hasta la fecha

**Comment by martinmiranda14** [comment]
Bug no se puede replicar de manera consistente
