### ISSUE TITLE
What's New: Asynchronosity within Question Exec

### ISSUE THREAD

**Issue by Mauriceac** [Cotalker/documentation#927]
## Summary
Question Exec is now asynchronous. `await` is used to control the Javascript flow cycle.

This permits the use of Network Requests to gather information from other websites and post the data onto the survey fields. For example, survey form fields can be filled out with autofill (autocomplete) using _external data_, e.g., Tax Id.

## Who and how does it help

Examples:
Users will fill out survey forms easier because fields will be autocompleted.
Developers will be able to set up a survey field's _external data_.

## Changes for Users

Examples:
Users can automatically fill in fields with _external data_ on survey forms.
A _play_ button is added to the field to fill in with the previously-entered data.

## Changes for Admins & Developers
Question exec

## Expected release date
Now.

## Modification / Creation of new sections.
Update: Admin > Survey > Automation (Question Exec)
Update Getting Started > Survey
What's New: Survey Forms with Autofill (Autocomplete)

## (Supplementary information)
See Service Quotation Product for examples (survey: conditional display & automation)

**Comment by gmoplaza** [comment]
Sobre el uso de exec asincronico:
- La función run() debe ser de tipo asincrónica.
     async function run () { /* yourCode; */ return []; }
     
<img width="559" alt="image" src="https://user-images.githubusercontent.com/9313324/171286756-328d9af9-24b4-4d8e-9f40-ade51d5eb6dd.png">

**Comment by gmoplaza** [comment]
networkRequest(url, { headers, method, body })

**Comment by gmoplaza** [comment]
Sobre SET_RESPONSE
https://doc.cotalker.com/docs/documentation/automation/question_exec/#questionexec-function

La funcionalidad antes solo permitía actualizar el valor de la misma respuesta que tenía configurado un question exec. Ahora es posible cambiarle el valor a una question hermana.

```javascript
return [
  { 
    cmd: 'SET_RESPONSES', 
    value: 'valor_que_queremos_setear', 
    target: 'self' | 'identifier_de_la_pregunta_hermana'
  }
];
```

**Comment by gmoplaza** [comment]
{ token: true } esto le indica a exec, que en esta llamada en particular se quiere usar el token del usuario que ESTA LOGEADO.

**Comment by gmoplaza** [comment]
Nuevo contexto!
user#company: El id de la compañia del usuario que está logeado

**Comment by guillevalin** [comment]
@gmoplaza podrías explicarle brevemente a @Mauriceac como funcionan los SET_RESPONSES dependiendo del tipo de question? se me había olvidado como hacerlo para un survey+listquestion y tuve que mirar el código del webclient jaja

**Comment by Mauriceac** [comment]
@guillevalin, @gmoplaza  Tengo unas notas en #939

Por lo que entiendo, 
1. SET_RESPONSE rellena el campo de un survey. 
2. El formato de esa respuesta debe ir de acuerdo al Question Content Type (components).
3. Hice un survey con todos los content types (components).
4. Busqué en COTAnswerData todos los campos `process`, que supongo es el "raw data" que se ingresa en el los campos de un survey, por lo cual serían lo que va en SET_RESPONSE

¿Está bien?
