### ISSUE TITLE
Bug report: tasks no se ven en la vista de channels (pero sí en la de tasks)

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#934]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

Hola! les traigo un bello bug un viernes en la tarde jajaja no me maten 😫

Creé una compañía en production con el exporter-importer. Al crear tasks, no se me ven las tasks en la vista de channels, pero sí en la vista de tasks, como se ve en las imágenes:
- vista de channels:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/73865460/170798507-5d340356-a087-4448-825a-0e1de7bf9368.png">
- vista de tasks: 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/73865460/170798668-0282be32-fa95-40df-b2fb-6cc1edd2b894.png">

Corroborando, sí trae el channel, por lo que al parecer el problema es solo de frontend:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/73865460/170798724-984e0f03-0b10-4de4-8960-4b70b5ce5e36.png">

### Steps to reproduce

1. crear compañía en prod con el exporter importer (o pedirme las credenciales de esta)
2. crear una task y observar que no se ve en la vista de channels pero sí en la de tasks

### Expected result

que las tareas se vean en la vista de channels 🙌

**Comment by ValeMP** [comment]
a mi me pasa en dev

**Comment by acedward** [comment]
Entiendo que este era un problema sólo que pasaba en la compañia instalada porque no se borraba toda la data.
