### ISSUE TITLE
What's New: User's jobtitle update

### ISSUE THREAD

**Issue by ccarrascor** [Cotalker/documentation#935]
## Summary
Job titles will be able to have access roles and elements (properties). These access roles and elements will be seen at the user's admin crud as uneditable chips (in the respective field).

## Who and how does it help
A jobtitle will give an user permissions and elements (that also grant access to features) according to their role. 
It will be a more efficient way to grant permissions to users. 

## Changes for Users
Even if an user dont have a accessrole or element assigned to him, if their jobtitle has them, the user virtually will also have it. Example: The user doesn't have any access role that grants him access to the admin, but we assign a job title that has an access role with admin access, the user will have the access.

## Changes for Admins & Developers
Updated jobtitle interface in Administrative Panel > Jobtitles > Edit/New: Two new panels with selectors for access roles and elements (select a collection, and then select the elements)
<img width="968" alt="Screen Shot 2022-05-30 at 10 24 52" src="https://user-images.githubusercontent.com/28242796/171012439-6d2fe23d-3670-4ccf-915a-702e86212393.png">

Updated user interface in Administrative Panel > Users > Edit/New: Access roles and elements fields have a new kind of chip (Gray chips that are uneditable)
<img width="963" alt="Screen Shot 2022-05-30 at 10 25 40" src="https://user-images.githubusercontent.com/28242796/171012465-da51d8ab-8d21-4a5b-8671-92f27aacf97a.png">

## Expected release date
Hopefully next week.

## Modification / Creation of new sections.
Update Jobtitle Documentation
Update User Documentation

## (Supplementary information)
The access roles part is already in production.
Elements is a WIP.

**Comment by Mauriceac** [comment]
Write warning: elements must be set manually. Refer to SME meeting for details.
