### ISSUE TITLE
Bug report: CCJS, Backtik "`" conflicts with COTLang

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#936]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected system (other)

svc-scheduler-process

### Affected environment

Production

### App version

17.10.13

### Details

Backtick is used for string concatenation in JS in the form
```Javascript
const happen = "fail"
const result = `this will ${fail}`
```
There's the requierement of wrapping all the CCJS src input in triple backticks "\`\`\`" to escape all the characters inside that may cause COTLang to attempt to parse, but still fails on single backticks. The ideal solution would be to stop requiring the triple backtick and cotlang to completely ignore the code inside the src.

### Steps to reproduce

Try building a CCJS with this
```Javascript
const happen = "fail"
const result = `this will ${fail}`
```
See it fail

### Expected result

Backtick concatenation wont cause the step to fail

**Comment by ValeMP** [comment]
También lo sufro ):

**Comment by agallardol** [comment]
Corrección disponible a partir del 01/08/2022
