### ISSUE TITLE
Documentation > Question Exec

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#939]
# Sección to be revised
Documentation > Automation > Question Exec

# Objective
SET_RESPONSES is not documented on the values allowed by question type.

# Details
Today I wanted to preload a survey+listquestion with a default value, and I didn't know how to populate the response array value.

It could be useful to document the format for each question type, for example:
survey+property: Array<Property ID>
survey+text: String
survey+textnumber: Integer
survey+listquestion: Array<Value codes>

etc..

# Other
N/A

# Priority
Medium

**Comment by Mauriceac** [comment]
Connect with #927
