### ISSUE TITLE
Bug report: upload file en mobile

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#942]
### Affected system

Cotalker Android Application

### Affected environment

Production

### App version

17.10.17

### Details

Fotos de formularios se están subiendo con URL local al answer, no se visualizan en el cliente móvil ni web

![image](https://user-images.githubusercontent.com/45186006/171900826-1a8df0ad-e580-488f-ba38-fad4c7c0d013.png)

answer "_id" : ObjectId("629a1f3bde202f0008880323")
"identifier" : "activo_photos",

### Steps to reproduce

Levantar formulario con campo de imágenes en cliente móvil.
Subir imágenes, revisar url

### Expected result

URL debiese ser del bucket de cotalker y no del localhost capacitor

### Additional data

Company: Terpel Panamá (en prod)

{
    "email": "admin@terpelpanama.cotalker.com",
    "password": "h7KAnUWBGb"
  },

**Comment by agallardol** [comment]
Done
