### ISSUE TITLE
Bug report: User status no se visualiza en UI

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#947]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.10.14 (255)

### Details

En cliente con infra dedicada no se esta viendo disponible el user status y se requiere dentro de su flujo,  ya que existen reglas de negocio asociadas.

### Steps to reproduce

Ingresar a la implementación y verificar que no se puede cambiar el user status.

### Expected result

Que aparezca en la UI el estado y se pueda cambiar.

**Comment by agallardol** [comment]
Done
