### ISSUE TITLE
Bug report: Cambios de estado no se reflejan automáticamente y requieren refresh manual

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#949]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.10.14 (255)

### Details

Se quita usuario de tarea con usuario admin

<img width="807" alt="image" src="https://user-images.githubusercontent.com/50208672/172422862-1a338f53-48fd-40f1-8a71-857a8a81d388.png">

En la vista del usuario removido , se sigue viendo la tarea: 

<img width="460" alt="image" src="https://user-images.githubusercontent.com/50208672/172422980-34a38c82-503a-42a1-ac51-54ed961c0fac.png">

Si se refresca manualmente la ventana el aviso desaparece

![Uploading image.png…]()

### Steps to reproduce

1. Ingresar a grupo telesoporte
2. Cambiar una tarea de estado

### Expected result

Que se reflejen los cambios sin necesitar refresh manual

**Comment by agallardol** [comment]
Done

**Comment by agallardol** [comment]
Hicimos el refactor, estará disponible soon en 17.11.8
