### ISSUE TITLE
Bug report: bug visual - Tareas desaparecen al haber actualizaciones en la vista de tasks

### ISSUE THREAD

**Issue by SeIturra** [Cotalker/documentation#954]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

17.10.19 (260)

### Details

Cuando se actualiza la vista de tasks debido a un cambio de estado o por eliminar una task, a veces, el canal donde uno está se elimina del listado de tareas.

[Video del bug - sólo cuentas Cotalker Premium](https://drive.google.com/file/d/1P9qShqBRlsUhehKlTlhUGYmopYD5aSBv/view?usp=sharing)

### Steps to reproduce

1. Estar en la vista de tareas.
2. Desactivar una tarea y rápidamente posicionarse en otra.
3. La tarea **que no fue desactivada** desaparecerá del listado.

Al refrescar la página, las tareas quedan en su estado correcto de visualización.

* Consideración: También pasa en otros casos como cambio de estado como se ve en el video anterior.

### Expected result

Las tareas no desactivadas no deberían desaparecer.

**Comment by agallardol** [comment]
Resolviendo

**Comment by agallardol** [comment]
Done

**Comment by agallardol** [comment]
Reabrimos dado que la corrección de este bug generó algunos sideeffects y tuvimos que revertir.
