### ISSUE TITLE
Bug report: No se puede crear una oportunidad 

### ISSUE THREAD

**Issue by ConsuValdivia** [Cotalker/documentation#960]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Details

En sales team a la hora de querer crear una oportunidad no se puede (se hace click pero no "pasa nada")

### Steps to reproduce

1. Ir a Sales Team
2. Apretar el +
3. no pasa nada :(

### Expected result

Que se puedan crear oportunidades :)

**Comment by guillevalin** [comment]
Era un problema de configuración. Por alguna razón el formulario de inicio estaba inactivo.
