### ISSUE TITLE
Bug report: Workflow Global Permission don't apply to JobTitle inherited access roles

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#964]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected environment

Production

### App version

17.11.0

### Details

When a global permission (for example, followers permissions) is configured, the effect is not applied to users with those permissions inherited by jobTitle, but works with accessroles explicitly  declared in that user.

Configuration:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/45186006/173137287-a43a5beb-496b-42c2-b103-d22c1eced58b.png">
<img width="939" alt="image" src="https://user-images.githubusercontent.com/45186006/173137495-072faa1c-009d-496a-9964-5283c56c8f3f.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/45186006/173137589-aff72b72-c76c-4815-bf11-07b2832fa787.png">
<img width="953" alt="image" src="https://user-images.githubusercontent.com/45186006/173137655-6148ff97-b68e-4f7c-b22e-44f6db427ef2.png">

Task view still doesn't show tasks:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/45186006/173137831-96b9e81c-00fb-4197-8c92-68ef4320d93a.png">

Explicitly declare  access role to user:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/45186006/173138237-143eb2ff-c7c3-4d26-af0b-a2f7fadc1312.png">
And it works:
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/45186006/173138350-734ab2c2-b179-4f2d-af5b-452477c2ff85.png">

PD, still this only works with the taskview, in channels this is not applied (channels are deprecated so this step is not crucial):
<img width="354" alt="image" src="https://user-images.githubusercontent.com/45186006/173138535-f354b616-4313-4653-9b8e-3412ef75c479.png">

### Steps to reproduce

Follow the details to see an example

### Expected result

Feature working as expected to inherited by jobtitle access roles

**Comment by DavidEhrenfeld** [comment]
Holas, esto pega en continuidad también. Nos pasó un caso en que se asignó cargo a nuevo usuario y no entregó los permisos heredados del jobtitle
