### ISSUE TITLE
Bug report: Existe un error en el pbchante state, no deja cambiar de estado una tasks

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#966]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.11.0 (262)

### Details

Hoy al realizar una prueba en un flujo arrojó un error del cambio de estado que es el siguiente:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/61419471/173424785-4cbef14c-8cd2-475d-8561-8a108af0b1e1.png">
mensaje de error: `0: "STATUS CODE: 500 BODY: {"status":false,"error":"Error: 629950dded126d000901f068"}"`

### Steps to reproduce

1.- Crear u bot de cambiar etapa dentro de una sm
2.- revisar resultado

### Expected result

Debería funcionar bien

**Comment by chantezan** [comment]
temporal ya no sigue sucediendo, por ende no se pudo replicar tampoco
