### ISSUE TITLE
Bug report: Algunas tareas no cargan el icono

### ISSUE THREAD

**Issue by martinmiranda14** [Cotalker/documentation#967]
### Affected system

Cotalker Web Application

### Affected environment

Production

### Affected environment (other)

coopeuch-qa

### Details

Algunas tareas no muestran el icono 
![tarea2](https://user-images.githubusercontent.com/29107230/173428596-c7705118-ac6d-45ce-940f-7dd9342055f6.png)
![img1](https://user-images.githubusercontent.com/29107230/173428610-71fec1d2-8d34-44b9-8e21-5faf6e2068d0.png)

### Steps to reproduce

Definir nombre de la tarea del formato que no muestra el icono

### Expected result

Que ambas tareas muestren icono

### Additional data

Request URL: http://qa.cotalkercoopeuch.com:10000/api/users/20/po/627d59528351340008a4d554/kx.png
Request Method: GET
Status Code: 304 OK
Request URL: http://qa.cotalkercoopeuch.com:10000/api/users/20//627bbc2a8351340008a311ed/kx.png
Request Method: GET
Status Code: 404 Not Found

**Comment by agallardol** [comment]
Corregido, disponible desde 02/08/2022
