### ISSUE TITLE
Bug report: Grupo reportes no funciona

### ISSUE THREAD

**Issue by jdurandpaz** [Cotalker/documentation#974]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging

### Affected environment (other)

Cliente infra dedicada 

### App version

17.7.5 (221)

### Details

![image](https://user-images.githubusercontent.com/50208672/174103906-097acbce-22b9-42b2-baed-290ca737af3d.png)

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/50208672/174103858-2f52be31-7842-48a0-9f47-2e90af2e7989.png">

### Steps to reproduce

Ingresar al grupo reportes e intentar ocupar alguna de las secciones.

### Expected result

Que se puedan utilizar las secciones , por ej revisar descargar de base de datos los elementos de una colección.

**Comment by agallardol** [comment]
Corregido en infra dedicada qa
Quedará corregido en prod para el siguiente paso a production de dicha infra
