### ISSUE TITLE
Bug report: Ciertos mensajes con links no se envían

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#980]
### Affected system

Cotalker Web Application, Cotalker Api

### Affected environment

Production

### App version

Latest

### Details

Al enviar un mensaje con este cuerpo por el chat, se queda pending hasta eventualmente obtener un error 504 "Gateway Timeout":

`
curl 'https://www.cotalker.com/api/messages/multi' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"' \
  -H 'DNT: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer **REDACTED**' \
  -H 'build: cotalker' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: https://web.cotalker.com/' \
  -H 'device: universal-web' \
  -H 'lang: en' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
  -H 'app: 17.11.6 (269)' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"cmd":[{"message":{"_id":"62b0956e33f1d1bbff05d610","content":"https://docs.google.com/document/d/1Lzt2nxI87m6c-EUcBLVHiLHFTnReA1gx/edit","contentType":"text/plain","channel":"62703f7da019ca0007273e9b","modifiedAt":"2022-06-20T15:42:38.533Z","sentBy":"5a5533f1407011dc14d1bbff","createdAt":1655739758533,"isSaved":2,"reply":[]},"_id":"62b0956e33f1d1bbff05d610","method":"POST"}]}' \
  --compressed
`

### Steps to reproduce

Se dejó cURL para reproducir el error (no solo pasa por el cliente web, si no que por API).

Solicitar token para realizar la prueba (se ocultó por motivos de privacidad).

### Expected result

Que se pueda enviar el mensaje correctamente indistintametne del link que posea.

**Comment by agallardol** [comment]
Corregido, disponible desde 02/08/2022
