### ISSUE TITLE
Bug report: Formulario no se oculta correctamente según reglas de control form

### ISSUE THREAD

**Issue by AlejandroLoraG** [Cotalker/documentation#981]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

15.0.0

### Buen día a tod@s! Espero tengan un hermoso día. 🥰

Al parecer no se están actualizando correctamente los formularios cuando las reglas del control form se activan.

Tengo 4 formularios en un mismo estado. Estos formularios tienen reglas distintas para cuando aparecer y cuando no (parametros que lee los control forms -> img 1 y 2). Siempre habrá uno y solo uno presente (img 3 y 4), por lo tanto, cuando se esconde uno, se muestra el otro.
Al cambiar el parametro correspondiente según el survey trigger (img 5) **a veces** el formulario no se esconde y el parametro de la task no se visualiza según el cambio (img 6). Para corregir el problema a nivel de usuario debo recargar el canal, al hacer esto se visualiza el parametro de la task cambiado y el formulario que se debe mostrar según corresponde (resultado esperado, img 7).

Img 1
![fig 1](https://user-images.githubusercontent.com/51095635/175048287-067eaca8-8d52-40c7-b3d0-aec5abfaf060.png)

Img 2
![image](https://user-images.githubusercontent.com/51095635/175048462-8cd48661-56d8-4fbe-b9e3-0080f80ee682.png)

Img 3
![image](https://user-images.githubusercontent.com/51095635/175049115-de205939-cc7e-4e77-933e-bba01dbcbafc.png)

Img 4
![image](https://user-images.githubusercontent.com/51095635/175048978-60e53a99-2b62-4655-a234-71e00bda6698.png)

Img 5
![image](https://user-images.githubusercontent.com/51095635/175049847-6860e0df-1342-4812-bef5-e085216d66cf.png)

Img 6
![image](https://user-images.githubusercontent.com/51095635/175050736-683367d6-38cb-4030-a8bd-5d1fe0b226a3.png)

Img 7
![image](https://user-images.githubusercontent.com/51095635/175052183-c46d9389-2a88-48b4-85a9-114b990f373d.png)

(Formulario 1)
```javascript
function run() {
  const task = context['channel#task'];
  if (!task) return [ { cmd: 'HIDDEN', value: false } ]
  
  const isPelp = task.extensions.c_work_order.ot_provider === 'p1110033'
  const workDone = task.extensions.c_work_order.work_done === true

  if (!workDone && !isPelp) {
    return [ { cmd: 'HIDDEN', value: false } ]
  } else {
    return [ { cmd: 'HIDDEN', value: true} ]
  }
}
```

(Formulario 2)
```javascript
function run() {
  const task = context['channel#task'];
  if (!task) return [ { cmd: 'HIDDEN', value: false } ]

  const isPelp = task.extensions.c_work_order.ot_provider === 'p1110033'
  const workDone = task.extensions.c_work_order.work_done === true
  if (!workDone && isPelp) {
    return [ { cmd: 'HIDDEN', value: false } ]
  } else {
    return [ { cmd: 'HIDDEN', value: true} ]
  }
}
```

(Formulario 3)
```javascript
function run() {
  const task = context['channel#task'];
  if (!task) return [ { cmd: 'HIDDEN', value: false } ]
  
  const isPelp = task.extensions.c_work_order.ot_provider === 'p1110033'
  const workDone = task.extensions.c_work_order.work_done === true
  if (workDone && !isPelp) {
    return [ { cmd: 'HIDDEN', value: false } ]
  } else { 
    return [ { cmd: 'HIDDEN', value: true} ]
  }
}
```

(Formulario 4)
```javascript
function run() {
  const task = context['channel#task'];
  if (!task) return [ { cmd: 'HIDDEN', value: false } ]
  
  const isPelp = task.extensions.c_work_order.ot_provider === 'p1110033'
  const workDone = task.extensions.c_work_order.work_done === true
  if (workDone && isPelp) {
    return [ { cmd: 'HIDDEN', value: false } ]
  } else {
    return [ { cmd: 'HIDDEN', value: true} ]
  }
}
```

### Steps to reproduce

1. Crear control forms con lógica alternante, es decir, según un parametro de task.extensions muestra este o el otro.
2. Crear un formulario que gatille el cambio de este parametro de task.extensions.
3. Gatillar este proceso hasta que ocurra el bug.
4. Contactar a alelo para mas detalles.

### Expected result

El front debiese refrescar la vista según corresponda y no tener que hacer reload del channel para que los cambios se vean reflejados.

**Comment by agallardol** [comment]
Pasaremos durante el día a staging
