### ISSUE TITLE
Bug report: Error in saving form state change with two or more permisssions

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#983]
### Affected system

Cotalker Web Application

### Affected environment

Production, Staging, Development

### App version

17.11.6

### Details

Saving an sm state with a state change using two or more permissions causes that the data won't be rendered the next time the user tries to edit that state. This is important because the implementers may lose some routines due to this.

### Steps to reproduce

1. Create an smState in the admin
2.  Add a surveyTrigger routine and a couple state change
3. Configure two permissions for one
4. Save
5. Return to edit the state, the previous config will not be displayed

### Expected result

Correctly handling and saving the case

**Comment by agallardol** [comment]
Disponible en staging. Próximamente en 17.11.8
