### ISSUE TITLE
Bug report: sendMessage con <a href="https://..." target="_blank"> no considera el target

### ISSUE THREAD

**Issue by CVargasGando** [Cotalker/documentation#985]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### Details

Holaa team!

Vengo a molestarlos con otro favor porfis 👀🙏
Lo que quiero hacer es enviar un mensaje con un link, y que al apretarlo este link se abra en otra ventana (no en la misma), y para esto usé target=_blank

Para esto en el PBmessage mando un contenido que se resumen en lo siguiente:
Click < a href="/tasks/${taskGroups._id}/calendar?groupId=${taskGroups._id}&type=month&filter=${filterId}" target="_blank">aqui</a >

Al enviarlo y revisar los elementos del html, se ve lo siguiente:
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/73865460/175405748-9b061438-9c88-4269-9746-d3fcb29e6b99.png">
Donde lo que se ve en el elemento es:
< a href="/tasks/61c3b3f45de9d200098a4615/calendar?groupId=61c3b3f45de9d200098a4615&amp;type=month&amp;filter=62b383d0ffc720379ef9e3b5">aquí.</a> 

Se puede ver que el target="_blank" no está :(

### Steps to reproduce

1. Hacer un pbMessage que mande un link de la forma <a href ... target="_blank> para que se abra en otra ventana al hacer click en el link
2. Probarlo y notar que no se abre en otra ventana, esto porque el target se elimina en el elemento del html. 

### Expected result

Que al hacer click en el link este se abra en otra ventana. 
Una opción podría ser hacer que por defecto se abra en otra ventana (actualmente por defecto se abre en la misma ventana), u otra opción sería que considere el "target = _blank" en el elemento del html (actualmente no lo considera, lo "elimina")

Muchas gracias team! son lo mejor 😍🙌

**Comment by agallardol** [comment]
Corregido, disponible desde el 02/08/2022
