### ISSUE TITLE
Bug report: No se ejecuta de manera correcta el pbtaskaddeditor de tipo remove

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#997]
### Affected system

Cotalker Web Application

### Affected environment

Production

### App version

Versión 17.11.8 (271)

### Details

Cuando se utilza el PBtaskaddeditor, para remover un usuario de una tasks, en los log, se ejecuta de manera correcta, pero no la acción de sacar un usuario de una tarea.

Adjunto ss de la rutina
<img width="681" alt="image" src="https://user-images.githubusercontent.com/61419471/177170524-b61f0885-ec47-4a54-a1f4-8deb5b743d54.png">

Adjunto ss del log
<img width="742" alt="image" src="https://user-images.githubusercontent.com/61419471/177170857-dedfa61d-fc68-4cd8-b280-3aba06ff19c6.png">

Adjunto el scheduler log: 62c2f3721e7133ec27d683fc

### Steps to reproduce

1.- Crear una rutina con pbtaskaddeditor de tipo remove y user
2.- Ejecutar rutina

### Expected result

DEberia sacar el usuario de la tasks de manera correcta

**Comment by DavidEhrenfeld** [comment]
Esto que se reporta está afectando a cliente en productivo (GS) que está probando solución inicial donde sus reparadores, si no aceptan la orden de reparación, deben salir del canal. Asi mismo cuando completan y cierran orden de servicio para no visualizar liquidación de orden con valores que entrega parte final del flujo. En resumen, podría tener impacto en insatisfacción de cliente por no quedar conforme con lo entregado
