### ISSUE TITLE
Bug report: No aparece la opción azure en un cliente con infraestructura dedicada

### ISSUE THREAD

**Issue by NicolasPLG** [Cotalker/documentation#999]
### Affected system

Cotalker Web Application

### Affected environment

Staging

### App version

Versión 17.11.0 (262)

### Details

Queremos probar azure con un correo entregado por el cliente para poder acceder a cotalker, desde un ambiente qa. El cliente cuenta con infra dedica. Sin embargo no aparece en las opciones de logueo

Adjunto SS

<img width="426" alt="image" src="https://user-images.githubusercontent.com/61419471/177220929-1ec03ab9-4cdf-4057-a980-9cf7803759bb.png">

El id del cliente es: 5d8a72c83375414a707f1d97

### Steps to reproduce

1.- ingresar a la infra dedicada según credenciales
2.- ver la opción de azure si aparece
3.- Consultar conmigo si requieren mayor información

### Expected result

Debe aparecer para realizar pruebas con correo corporativo del cliente

### Additional data

company: 5d8a72c83375414a707f1d97

**Comment by agallardol** [comment]
Corregido,, se configuró la compañía para habilitar login con azure
